"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { PlaybookCard, PlaybookGrid, PlaybookHero, PlaybookMetric, PlaybookMetrics, PlaybookPage, PlaybookPill } from "@/components/ui";

type Scholarship={id:string;partner_id:string;organization_name:string;opportunity_type:string;title:string;description:string;location:string|null;external_url:string|null;deadline:string|null;compensation_summary:string|null;eligibility:string[];requirements:string[];tags:string[];published_at:string};
type CatalogResponse={opportunities?:Scholarship[];error?:string};

function applicationHref(item:Scholarship){const query=new URLSearchParams({opportunityId:item.id,opportunityName:item.title,opportunityType:"scholarship"});if(item.deadline)query.set("deadline",item.deadline);return `/application-workspaces?${query.toString()}`;}

export default function ScholarshipsPage(){
 const[items,setItems]=useState<Scholarship[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");
 useEffect(()=>{let active=true;void fetch("/api/marketplace/opportunities",{cache:"no-store"}).then(async response=>{const body=await response.json() as CatalogResponse;if(!response.ok)throw new Error(body.error||"Scholarships could not be loaded.");if(active)setItems((body.opportunities||[]).filter(item=>item.opportunity_type==="scholarship"));}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Scholarships could not be loaded.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return items.filter(item=>!needle||`${item.title} ${item.organization_name} ${item.description} ${(item.tags||[]).join(" ")}`.toLowerCase().includes(needle));},[items,query]);
 const withDeadlines=items.filter(item=>Boolean(item.deadline)).length;
 return <PlaybookPage>
  <PlaybookHero eyebrow="Academic · Opportunity" title="Scholarship Finder" subtitle="Browse real scholarship listings from Playbook's human-reviewed Opportunity Marketplace. Scholarship discovery uses the same canonical catalog and Application Workspace as every other opportunity type." />
  <PlaybookMetrics><PlaybookMetric label="Published scholarships" value={loading?"…":String(items.length)}/><PlaybookMetric label="With deadlines" value={loading?"…":String(withDeadlines)}/><PlaybookMetric label="Application system" value="Shared Workspace"/></PlaybookMetrics>
  <section style={truth}><PlaybookPill>Canonical Marketplace</PlaybookPill><h2 style={truthTitle}>Real listings only.</h2><p style={truthCopy}>Scholarships appear here only after the same human publication review used by the Opportunity Marketplace. Playbook does not turn AI suggestions into fake scholarship listings.</p></section>
  <section style={section}>
   <div style={toolbar}><label style={label}>Search scholarships<input aria-label="Search scholarships" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Scholarship, organization, topic…" style={input}/></label><Link href="/opportunities" style={secondary}>All opportunities →</Link></div>
   {error?<div role="alert" style={alert}>{error}</div>:null}
   <p role="status" aria-live="polite" style={status}>{loading?"Loading published scholarships…":`${visible.length} scholarship${visible.length===1?"":"s"} found.`}</p>
   {loading?<PlaybookCard eyebrow="Scholarships" title="Loading catalog"><p style={copy}>Connecting to the governed Marketplace Opportunity Catalog…</p></PlaybookCard>:visible.length===0?<PlaybookCard eyebrow="Scholarships" title="No published scholarships in this view"><p style={copy}>{items.length?"Try a different search.":"No scholarship listing has completed human publication review yet. Playbook will not fabricate listings to fill this page."}</p></PlaybookCard>:<PlaybookGrid min={340}>{visible.map(item=><PlaybookCard key={item.id} eyebrow={item.organization_name} title={item.title}><div style={pills}>{item.deadline?<PlaybookPill>Deadline {item.deadline}</PlaybookPill>:<PlaybookPill>Open deadline</PlaybookPill>}{item.compensation_summary?<PlaybookPill>{item.compensation_summary}</PlaybookPill>:null}</div><p style={copy}>{item.description}</p>{item.eligibility?.length?<section><h3 style={subhead}>Eligibility</h3><ul style={list}>{item.eligibility.map(value=><li key={value}>{value}</li>)}</ul></section>:null}{item.requirements?.length?<section><h3 style={subhead}>Requirements</h3><ul style={list}>{item.requirements.map(value=><li key={value}>{value}</li>)}</ul></section>:null}<div style={actions}><Link href={applicationHref(item)} style={primary}>Start Application Workspace →</Link>{item.external_url?<Link href={item.external_url} target="_blank" rel="noreferrer" style={secondary}>Official listing ↗</Link>:null}</div></PlaybookCard>)}</PlaybookGrid>}
  </section>
 </PlaybookPage>;
}
const truth:React.CSSProperties={maxWidth:1180,margin:"0 auto 24px",padding:"clamp(20px,4vw,32px)",borderRadius:"8px 28px 8px 28px",background:"#081D34",color:"#FFF"};const truthTitle:React.CSSProperties={margin:"10px 0 8px",fontSize:"clamp(24px,4vw,34px)"};const truthCopy:React.CSSProperties={color:"#C9D8E8",lineHeight:1.65};const section:React.CSSProperties={maxWidth:1180,margin:"0 auto 34px"};const toolbar:React.CSSProperties={display:"flex",alignItems:"end",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginBottom:12};const label:React.CSSProperties={display:"grid",gap:6,fontWeight:850,color:"#334155",flex:"1 1 320px"};const input:React.CSSProperties={border:"1px solid #CBD5E1",borderRadius:12,padding:"11px 12px",font:"inherit"};const status:React.CSSProperties={minHeight:24,color:"#475569"};const alert:React.CSSProperties={padding:14,borderRadius:12,background:"#FEF2F2",color:"#991B1B"};const copy:React.CSSProperties={color:"#475569",lineHeight:1.65};const pills:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",marginBottom:10};const subhead:React.CSSProperties={fontSize:14,color:"#0F172A",marginBottom:4};const list:React.CSSProperties={color:"#475569",lineHeight:1.55,paddingLeft:20};const actions:React.CSSProperties={display:"flex",gap:9,flexWrap:"wrap",marginTop:16};const base:React.CSSProperties={display:"inline-flex",alignItems:"center",borderRadius:999,padding:"10px 14px",fontWeight:900,textDecoration:"none"};const primary:React.CSSProperties={...base,background:"#F97316",color:"#FFF"};const secondary:React.CSSProperties={...base,border:"1px solid #CBD5E1",background:"#FFF",color:"#0F172A"};
