import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import {
  Artifacts,
  RuntimeArtifactOwnership,
  artifactDigest,
} from "../kernel";
import type {
  ReconciledArtifactEvidence,
  ReconciliationClassification,
} from "./types";

interface ArtifactFacts {
  currentGate: string | null;
  selectedGate: string | null;
}

function readJson(rootDir: string, relativePath: string): unknown {
  const target = path.join(rootDir, relativePath);
  if (!existsSync(target)) {
    return undefined;
  }
  try {
    return JSON.parse(readFileSync(target, "utf8")) as unknown;
  } catch {
    return null;
  }
}

function gateId(value: unknown): string | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const record = value as Record<string, unknown>;
  const direct = record.gate ?? record.gateId ?? record.selectedGate;
  if (typeof direct === "string") {
    return direct === "NONE" || direct === "UNKNOWN"
      ? null
      : direct;
  }
  if (direct && typeof direct === "object") {
    const id = (direct as Record<string, unknown>).id;
    return typeof id === "string" ? id : null;
  }
  return null;
}

function status(value: unknown): string | null {
  return value &&
    typeof value === "object" &&
    typeof (value as Record<string, unknown>).status === "string"
    ? ((value as Record<string, unknown>).status as string)
    : null;
}

function classify(
  relativePath: string,
  value: unknown,
  facts: ArtifactFacts
): { classification: ReconciliationClassification; reasons: string[] } {
  if (value === undefined) {
    return {
      classification: "invalid",
      reasons: ["Artifact is missing."],
    };
  }
  if (value === null || typeof value !== "object") {
    return {
      classification: "invalid",
      reasons: ["Artifact is not valid JSON object evidence."],
    };
  }
  const artifactGate = gateId(value);
  if (relativePath === "pbos/state/engine-state.json") {
    const currentGate =
      typeof (value as Record<string, unknown>).currentGate ===
      "string"
        ? ((value as Record<string, unknown>).currentGate as string)
        : null;
    return currentGate === facts.selectedGate
      ? { classification: "valid", reasons: [] }
      : {
          classification: "stale",
          reasons: [
            `Engine state gate ${currentGate ?? "none"} does not match planning gate ${facts.selectedGate ?? "none"}.`,
          ],
        };
  }
  if (relativePath === Artifacts.planning) {
    return artifactGate === facts.currentGate
      ? { classification: "valid", reasons: [] }
      : {
          classification: "stale",
          reasons: [
            `Planning gate ${artifactGate ?? "none"} does not match engine state ${facts.currentGate ?? "none"}.`,
          ],
        };
  }
  if (relativePath === Artifacts.validation) {
    if (artifactGate !== facts.selectedGate) {
      return {
        classification: "superseded",
        reasons: [
          `Validation gate ${artifactGate ?? "none"} was superseded by planning gate ${facts.selectedGate ?? "none"}.`,
        ],
      };
    }
    return status(value) === "PASS"
      ? { classification: "valid", reasons: [] }
      : {
          classification: "recoverable",
          reasons: ["Validation must be regenerated by runtime-validator."],
        };
  }
  if (relativePath === Artifacts.execution) {
    if (artifactGate !== facts.selectedGate) {
      return {
        classification: "superseded",
        reasons: [
          `Execution gate ${artifactGate ?? "none"} was superseded by planning gate ${facts.selectedGate ?? "none"}.`,
        ],
      };
    }
    if (facts.selectedGate === null && status(value) !== "BLOCKED") {
      return {
        classification: "invalid",
        reasons: ["Execution must be BLOCKED when no gate is selected."],
      };
    }
    return { classification: "valid", reasons: [] };
  }
  if (relativePath === Artifacts.repositoryContext) {
    return {
      classification: "recoverable",
      reasons: [
        "Repository context must be regenerated after runtime reconciliation.",
      ],
    };
  }
  return {
    classification: "invalid",
    reasons: ["Artifact classification is not governed."],
  };
}

export function inspectArtifactConsistency(
  rootDir = process.cwd()
): ReconciledArtifactEvidence[] {
  const statePath = "pbos/state/engine-state.json";
  const state = readJson(rootDir, statePath) as
    | Record<string, unknown>
    | undefined;
  const planning = readJson(rootDir, Artifacts.planning);
  const facts: ArtifactFacts = {
    currentGate:
      typeof state?.currentGate === "string"
        ? state.currentGate
        : null,
    selectedGate: gateId(planning),
  };
  const targets = [
    Artifacts.validation,
    Artifacts.execution,
    Artifacts.planning,
    Artifacts.repositoryContext,
    statePath,
  ];
  return targets.map((relativePath) => {
    const value = readJson(rootDir, relativePath);
    const governance = Object.values(
      RuntimeArtifactOwnership
    ).find(({ path: artifactPath }) => artifactPath === relativePath);
    const ownership =
      relativePath === statePath
        ? {
            owner: "engine-state-manager",
            producer: "saveState",
          }
        : governance;
    const result = ownership
      ? classify(relativePath, value, facts)
      : {
          classification: "invalid" as const,
          reasons: ["Canonical artifact ownership is ambiguous."],
        };
    return {
      path: relativePath,
      owner: ownership?.owner ?? "unknown",
      producer: ownership?.producer ?? "unknown",
      classification: result.classification,
      reasons: result.reasons,
      previousDigest:
        value === undefined ? null : artifactDigest(value),
      currentDigest: null,
      previousArtifact: value ?? null,
      regenerated: false,
    };
  });
}
