"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { PlaybookCard, PlaybookGrid, PlaybookHero, PlaybookMetric, PlaybookMetrics, PlaybookPage, PlaybookPill } from "@/components/ui";

type SavedSchool={id:string;college_name:string;college_type:string|null;status:string|null;deadline:string|null;notes:string|null};

export default function DreamSchoolsPage(){
 const router=useRouter();const[schools,setSchools]=useState<SavedSchool[]>([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[busy,setBusy]=useState("");
 async function load(){const auth=await supabase.auth.getUser();if(!auth.data.user){router.replace("/login");return;}const result=await supabase.from("college_list").select("id,college_name,college_type,status,deadline,notes").eq("user_id",auth.data.user.id).order("created_at",{ascending:false});if(result.error)setMessage(result.error.message);else setSchools((result.data||[]) as SavedSchool[]);setLoading(false);}
 useEffect(()=>{void load();},[]);
 async function markDream(school:SavedSchool){setBusy(school.id);const auth=await supabase.auth.getUser();if(!auth.data.user){setBusy("");return;}const result=await supabase.from("college_list").update({college_type:"dream"}).eq("id",school.id).eq("user_id",auth.data.user.id);if(result.error)setMessage(result.error.message);else{setMessage(`${school.college_name} is now a Dream School.`);await load();}setBusy("");}
 async function removeDream(school:SavedSchool){setBusy(school.id);const auth=await supabase.auth.getUser();if(!auth.data.user){setBusy("");return;}const result=await supabase.from("college_list").update({college_type:"saved"}).eq("id",school.id).eq("user_id",auth.data.user.id);if(result.error)setMessage(result.error.message);else{setMessage(`${school.college_name} remains saved but is no longer marked as a Dream School.`);await load();}setBusy("");}
 const dream=schools.filter(s=>s.college_type==="dream");const candidates=schools.filter(s=>s.college_type!=="dream");
 return <PlaybookPage><PlaybookHero eyebrow="Academic · College Planning" title="Dream Schools" subtitle="Turn the schools that matter most into a focused planning set without creating a second college list. Dream School is a priority state on your canonical saved-school record."/><PlaybookMetrics><PlaybookMetric label="Dream schools" value={loading?"…":String(dream.length)}/><PlaybookMetric label="Other saved schools" value={loading?"…":String(candidates.length)}/><PlaybookMetric label="Authority" value="College List"/></PlaybookMetrics>{message&&<p role="status" aria-live="polite" style={status}>{message}</p>}<section style={section}><div style={header}><div><p style={eyebrow}>Priority schools</p><h2 style={heading}>My Dream Schools</h2></div><Link href="/college-search" style={secondary}>College Search →</Link></div>{dream.length===0?<PlaybookCard eyebrow="Dream Schools" title="Choose the schools that inspire you most"><p style={copy}>Save schools in College Search, then mark the strongest possibilities as Dream Schools here.</p></PlaybookCard>:<PlaybookGrid min={320}>{dream.map(s=><PlaybookCard key={s.id} eyebrow={s.status||"considering"} title={s.college_name}><PlaybookPill>Dream School</PlaybookPill>{s.deadline&&<PlaybookPill>Deadline {s.deadline}</PlaybookPill>}<div style={actions}><Link href={`/application-workspaces?${new URLSearchParams({opportunityName:s.college_name,opportunityType:"college"}).toString()}`} style={primary}>Application Workspace →</Link><button type="button" disabled={busy===s.id} onClick={()=>void removeDream(s)} style={secondaryButton}>Remove Dream priority</button></div></PlaybookCard>)}</PlaybookGrid>}</section>{candidates.length>0&&<section style={section}><p style={eyebrow}>Saved schools</p><h2 style={heading}>Promote a school to Dream status</h2><PlaybookGrid min={300}>{candidates.map(s=><PlaybookCard key={s.id} eyebrow={s.status||"saved"} title={s.college_name}><button type="button" disabled={busy===s.id} onClick={()=>void markDream(s)} style={primary}>Mark as Dream School</button></PlaybookCard>)}</PlaybookGrid></section>}</PlaybookPage>;
}
const section:React.CSSProperties={maxWidth:1180,margin:"0 auto 30px"};const header:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,flexWrap:"wrap",marginBottom:14};const eyebrow:React.CSSProperties={margin:0,color:"#EA580C",fontSize:11,fontWeight:900,textTransform:"uppercase",letterSpacing:".1em"};const heading:React.CSSProperties={margin:"6px 0 14px",color:"#0F172A",fontSize:"clamp(27px,4vw,40px)"};const copy:React.CSSProperties={color:"#475569",lineHeight:1.65};const status:React.CSSProperties={maxWidth:1180,margin:"0 auto 18px",color:"#475569"};const actions:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",marginTop:16};const base:React.CSSProperties={display:"inline-flex",alignItems:"center",borderRadius:999,padding:"10px 14px",fontWeight:900,textDecoration:"none",cursor:"pointer"};const primary:React.CSSProperties={...base,border:0,background:"#F97316",color:"#fff"};const secondary:React.CSSProperties={...base,border:"1px solid #CBD5E1",background:"#fff",color:"#0F172A"};const secondaryButton:React.CSSProperties={...secondary};
