import { digestValue } from "../context";
import { createAthleteIdentity, createAthleticProfile } from "./athlete";
import type { AthleticInput, AthleticProvenance, AthleticReport } from "./contracts";
import { createMobilityPathways } from "./mobility";
import { createAthleticOrganizations } from "./organizations";
import { createPerformanceEvidence } from "./performance";
import { assessAthleteReadiness } from "./readiness";
import { createRecruitingAlignments } from "./recruiting";
import { createRepresentations } from "./representation";
import { createAthletesAbroadPrograms } from "./summit";
import { validateAthleticInput } from "./validation";
export function createAthleticReport(input: AthleticInput): AthleticReport {
  const context = validateAthleticInput(input);
  const sourceReportIds = [...input.identityReports.map(({ reportId }) => reportId), ...input.portfolioReports.map(({ reportId }) => reportId), ...input.masteryReports.map(({ reportId }) => reportId), ...input.credentialReports.map(({ reportId }) => reportId), ...input.opportunityReports.map(({ reportId }) => reportId), ...input.ecosystemReports.map(({ reportId }) => reportId)].sort();
  const evidenceReferences = [...new Set([...input.athleteIdentityDraft.evidenceReferences, ...input.athleticPortfolioDraft.evidenceReferences, ...input.performanceEvidenceDrafts.map(({ sourceReference }) => sourceReference), ...input.organizationDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.recruitingOpportunityDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.mobilityDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.representationDrafts.flatMap(({ relationshipEvidenceReferences }) => relationshipEvidenceReferences), ...input.athletesAbroadProgramDrafts.flatMap(({ evidenceReferences, consentEvidenceReferences }) => [...evidenceReferences, ...consentEvidenceReferences])])].sort();
  const provenance: AthleticProvenance = { runtimeContextDigest: context.contextDigest, athleteOwnerIdentity: input.athleteIdentityDraft.ownerIdentity, sourceReportIds, sourceReferences: [...new Set([input.athleteIdentityDraft.sourceReference, ...input.performanceEvidenceDrafts.map(({ sourceReference }) => sourceReference), ...input.recruitingOpportunityDrafts.map(({ sourceReference }) => sourceReference)])].sort(), evidenceReferences, generatedAt: input.generatedAt, authorizedActor: input.athleteIdentityDraft.ownerIdentity };
  const athleteIdentity = createAthleteIdentity(input.athleteIdentityDraft, provenance);
  const evidenceInventory = createPerformanceEvidence(input.performanceEvidenceDrafts, athleteIdentity, provenance);
  const body = { generatedAt: input.generatedAt, runtimeContextDigest: context.contextDigest, athleteProfile: createAthleticProfile(input.athleticPortfolioDraft, athleteIdentity, provenance), athleteIdentity, evidenceInventory, organizations: createAthleticOrganizations(input.organizationDrafts, provenance), opportunities: input.recruitingOpportunityDrafts.map((opportunity) => ({ ...opportunity, rosterNeeds: [...opportunity.rosterNeeds].sort(), requirements: [...opportunity.requirements].sort(), contactInformation: [...opportunity.contactInformation].sort(), evidenceReferences: [...opportunity.evidenceReferences].sort() })).sort((a, b) => a.opportunityId.localeCompare(b.opportunityId)), recruitingAlignments: createRecruitingAlignments(athleteIdentity, input.recruitingOpportunityDrafts), mobilityPathways: createMobilityPathways(input.mobilityDrafts, athleteIdentity), representations: createRepresentations(input.representationDrafts, athleteIdentity), athletesAbroadPrograms: createAthletesAbroadPrograms(input.athletesAbroadProgramDrafts), relationships: input.representationDrafts.map(({ relationshipId }) => relationshipId).sort(), readinessIndicators: assessAthleteReadiness(input, athleteIdentity, evidenceInventory), limitations: ["Athletic intelligence does not rank athletes, calculate value, replace coaches or scouts, or decide recruiting, eligibility, admission, contracts, employment, or representation.", "Alignment, readiness, and mobility records are informational and cannot guarantee scholarships, contracts, roster positions, or international outcomes."], provenanceBundle: provenance };
  return { reportId: `PBOS-ATH-REPORT-${digestValue(body).slice(0, 16).toUpperCase()}`, ...body };
}
