import { runSentinel } from "./SentinelEngine";

export function renderSentinelReport() {
  const report = runSentinel();
  const now = new Date().toISOString();

  return `# Playbook Sentinel Report

Generated by Playbook Sentinel.

## Generated At

${now}

## Platform Health

${report.healthScore}%

## Status

${report.status}

## Summary

- Passed checks: ${report.passed}
- Failed checks: ${report.failed}

## Checks

${report.checks.map(check => `- ${check.passed ? "✅" : "❌"} ${check.name}`).join("\n")}

## Meaning

Sentinel monitors whether critical Playbook OS subsystems exist and remain connected.

Sentinel does not replace tests or builds.

It adds platform-health awareness on top of tests, builds, Archivist, and Cartographer.
`;
}
