import { scanProject } from "./ProjectScanner";

function list(items: string[]) {
  if (!items.length) return "- None detected";
  return items.map((item) => `- ${item}`).join("\n");
}

export function renderCurrentArchitecture() {
  const scan = scanProject();
  const now = new Date().toISOString();

  return `# Current Architecture

Generated by Playbook Cartographer.

## Generated At

${now}

## System

Playbook Intelligence OS

## Current Milestone

Alpha 1.0

## Counts

- Total files: ${scan.files.length}
- Engines: ${scan.engines.length}
- Repositories: ${scan.repositories.length}
- Events: ${scan.events.length}
- SDK modules: ${scan.sdk.length}
- Components: ${scan.components.length}
- Pages: ${scan.pages.length}
- Migrations: ${scan.migrations.length}
- Tests: ${scan.tests.length}
- Docs: ${scan.docs.length}

## Core Flow

Playbook Record  
↓  
Playbook Graph  
↓  
Event Bus  
↓  
Engines  
↓  
Repositories  
↓  
Experience Layer  
↓  
Compass Guidance

## Major Layers

### Core Platform

- Playbook Record
- Scholar Record
- Trust Layer
- Playbook Graph
- Event Bus
- Engine Layer
- Repository Layer
- Playbook SDK

### Intelligence Layer

- Academic Intelligence
- Transcript Knowledge Graph
- Academic DNA
- Opportunity Graph
- Opportunity Marketplace
- Compass Core

### Experience Layer

- Dashboard Guidance
- Scholar Record Recommendations
- Opportunity Marketplace
- Compass UI
- Design System

`;
}

export function renderEngineCatalog() {
  const scan = scanProject();
  return `# Engine Catalog

Generated by Playbook Cartographer.

## Engines

${list(scan.engines)}
`;
}

export function renderRepositoryCatalog() {
  const scan = scanProject();
  return `# Repository Catalog

Generated by Playbook Cartographer.

## Repositories

${list(scan.repositories)}
`;
}

export function renderEventCatalog() {
  const scan = scanProject();
  return `# Event Catalog

Generated by Playbook Cartographer.

## Event Files

${list(scan.events)}
`;
}

export function renderComponentCatalog() {
  const scan = scanProject();
  return `# Component Catalog

Generated by Playbook Cartographer.

## Components

${list(scan.components)}
`;
}

export function renderSystemMap() {
  const scan = scanProject();

  return `# System Map

Generated by Playbook Cartographer.

## Architecture Map

Playbook SDK  
├── Academic Intelligence  
├── Opportunity Graph  
├── Compass Core  
├── Trust Layer  
├── Playbook Record  
├── Timeline  
├── Events  
└── Repositories  

## Detected Pages

${list(scan.pages)}

## Detected Migrations

${list(scan.migrations)}

## Detected Tests

${list(scan.tests)}
`;
}

export function renderDataModel() {
  const scan = scanProject();

  return `# Data Model

Generated by Playbook Cartographer.

## Supabase Migrations

${list(scan.migrations)}

## Known Core Tables

- playbook_records
- achievements
- evidence
- evidence_packs
- verifications
- reflections
- outcomes
- timeline_events
- opportunity_matches
- trust_reports
- scholar_vault_items
`;
}
