import { digestValue, type PBOSRuntimeContext } from "../context";
import type { EcosystemInput } from "./contracts";
import { EcosystemError, ecosystemFailure } from "./errors";

function validContext(context: PBOSRuntimeContext): boolean { const body = { ...context }; delete (body as Partial<PBOSRuntimeContext>).contextDigest; return context.documentInventory.length > 0 && context.contextDigest === digestValue(body); }
export function validateEcosystemInput(input: EcosystemInput): PBOSRuntimeContext {
  if (!input.runtimeContext || !validContext(input.runtimeContext)) throw new EcosystemError([ecosystemFailure("INVALID_CONTEXT", "A valid constitutional Runtime Context is required.")]);
  if (!input.authorizedPersonIds.includes(input.profile.personId) || !input.profile.permissions.includes("PROFILE")) throw new EcosystemError([ecosystemFailure("PRIVACY_VIOLATION", "Personal ecosystem data requires profile authorization.")]);
  if (input.hiddenConnectionRequested || input.relationshipDrafts.some((relationship) => relationship.hidden)) throw new EcosystemError([ecosystemFailure("HIDDEN_CONNECTION", "Connections must be visible to authorized participants.")]);
  if (input.fabricatedRelationshipRequested) throw new EcosystemError([ecosystemFailure("FABRICATED_RELATIONSHIP", "Relationships cannot be created without evidence and consent.")]);
  if (input.rankingRequested) throw new EcosystemError([ecosystemFailure("RANKING_PROHIBITED", "Ecosystem data cannot rank people or communities.")]);
  if (input.influenceScoreRequested) throw new EcosystemError([ecosystemFailure("INFLUENCE_SCORE_PROHIBITED", "PBOS cannot calculate social influence or popularity scores.")]);
  if (Number.isNaN(Date.parse(input.generatedAt))) throw new EcosystemError([ecosystemFailure("MISSING_EVIDENCE", "A valid report timestamp is required.")]);
  const digest = input.runtimeContext.contextDigest;
  if (!input.opportunityReports.length || !input.knowledgeReports.length || !input.credentialReports.length || input.opportunityReports.some((report) => report.runtimeContextDigest !== digest) || input.knowledgeReports.some((report) => report.runtimeContextDigest !== digest) || input.credentialReports.some((report) => report.runtimeContextDigest !== digest || report.recipientIdentity !== input.profile.personId)) throw new EcosystemError([ecosystemFailure("PRIVACY_VIOLATION", "Intelligence inputs must match the authorized person and active context.")]);
  const knownEvidence = new Set([...input.profile.evidenceReferences, ...input.opportunityReports.flatMap((report) => report.evidenceBundle), ...input.knowledgeReports.flatMap((report) => report.evidenceBundle), ...input.credentialReports.flatMap((report) => report.evidenceBundle)]);
  const referencedEvidence = [...input.entityDrafts.flatMap((entity) => entity.evidenceReferences), ...input.relationshipDrafts.flatMap((relationship) => relationship.evidenceReferences), ...input.mentorshipDrafts.flatMap((mentorship) => mentorship.evidenceReferences), ...input.supportNetworkDrafts.flatMap((network) => network.evidenceReferences), ...input.resourceDrafts.flatMap((resource) => resource.evidenceReferences)];
  if (!referencedEvidence.length || referencedEvidence.some((reference) => !knownEvidence.has(reference))) throw new EcosystemError([ecosystemFailure("MISSING_EVIDENCE", "Ecosystem records may only cite authorized, validated evidence.")]);
  if (!input.entityDrafts.length || input.entityDrafts.some((entity) => entity.verificationStatus !== "VERIFIED" || !entity.ownership || !entity.sourceReference || !entity.permissions.length || !entity.limitations.length)) throw new EcosystemError([ecosystemFailure("UNKNOWN_ENTITY", "Entities require verified identity, ownership, provenance, permissions, and limitations.")]);
  const names = new Set(input.entityDrafts.map(({ name }) => name));
  if (!names.has(input.profile.entityName) || input.relationshipDrafts.some((relationship) => !names.has(relationship.sourceEntityName) || !names.has(relationship.targetEntityName)) || input.mentorshipDrafts.some((mentorship) => !names.has(mentorship.mentorName) || !names.has(mentorship.menteeName))) throw new EcosystemError([ecosystemFailure("UNKNOWN_ENTITY", "Relationships and mentorships may only reference verified entities.")]);
  if (input.relationshipDrafts.some((relationship) => relationship.consentStatus !== "CONSENTED" || !relationship.evidenceReferences.length || !relationship.permissions.includes("RELATIONSHIP") || Number.isNaN(Date.parse(relationship.startDate)))) throw new EcosystemError([ecosystemFailure("UNAUTHORIZED_RELATIONSHIP", "Relationships require consent, evidence, permission, and start date.")]);
  if (input.mentorshipDrafts.some((mentorship) => mentorship.relationshipStatus === "ACTIVE" && mentorship.consentStatus !== "CONSENTED")) throw new EcosystemError([ecosystemFailure("UNAUTHORIZED_RELATIONSHIP", "Active mentorship requires participant consent.")]);
  const entityByName = new Map(input.entityDrafts.map((entity) => [entity.name, entity]));
  if (input.mentorshipDrafts.some((mentorship) => !mentorship.evidenceReferences.length || entityByName.get(mentorship.mentorName)?.entityType !== "MENTOR" || entityByName.get(mentorship.menteeName)?.entityType !== "PERSON")) throw new EcosystemError([ecosystemFailure("UNAUTHORIZED_RELATIONSHIP", "Mentorships require evidence and verified mentor and person roles.")]);
  const resourceNames = new Set(input.resourceDrafts.map(({ name }) => name));
  if (input.supportNetworkDrafts.some((network) => !names.has(network.personName) || network.supporterNames.some((name) => !names.has(name)) || network.organizationNames.some((name) => !names.has(name)) || network.resourceNames.some((name) => !resourceNames.has(name)) || !network.permissions.includes("SUPPORT_NETWORK"))) throw new EcosystemError([ecosystemFailure("UNKNOWN_ENTITY", "Support networks may only use disclosed, permissioned entities and resources.")]);
  const organizationNames = new Set(input.entityDrafts.filter(({ entityType }) => ["ORGANIZATION", "INSTITUTION", "PARTNER"].includes(entityType)).map(({ name }) => name));
  if (input.resourceDrafts.some((resource) => resource.verificationStatus !== "VERIFIED" || !organizationNames.has(resource.providerName))) throw new EcosystemError([ecosystemFailure("FABRICATED_ORGANIZATION", "Resources require a verified organizational provider.")]);
  return input.runtimeContext;
}
