import { Artifacts, type ArtifactName } from "./artifacts";

export interface RuntimeArtifactGovernance {
  path: string;
  owner: string;
  producer: string;
  consumers: string[];
  persistence: "durable" | "replaceable";
  cleanup: "governed-transition" | "replace-on-next-run";
}

export const RuntimeArtifactOwnership: Record<
  ArtifactName,
  RuntimeArtifactGovernance
> = {
  repository: {
    path: Artifacts.repository,
    owner: "repository-intelligence",
    producer: "pbos repository",
    consumers: ["context", "validator", "execution"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  planning: {
    path: Artifacts.planning,
    owner: "constitutional-planner",
    producer: "planConstitutionalGate",
    consumers: ["validator", "execution", "status"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  constitutionalPlanning: {
    path: Artifacts.constitutionalPlanning,
    owner: "constitutional-planner",
    producer: "planConstitutionalGate",
    consumers: ["status", "evidence"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  validation: {
    path: Artifacts.validation,
    owner: "runtime-validator",
    producer: "pbos validator",
    consumers: ["context", "planner", "execution"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  execution: {
    path: Artifacts.execution,
    owner: "execution-engine",
    producer: "pbos execute",
    consumers: ["context", "workflow", "evidence"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  executionContract: {
    path: Artifacts.executionContract,
    owner: "execution-contract",
    producer: "generateExecutionContract",
    consumers: ["work-package", "authorization", "execution"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  workPackage: {
    path: Artifacts.workPackage,
    owner: "work-package",
    producer: "generateCodexWorkPackage",
    consumers: ["authorization", "execution"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionAuthorization: {
    path: Artifacts.executionAuthorization,
    owner: "execution-authorization",
    producer: "generateExecutionAuthorization",
    consumers: ["authorization-decision", "execution"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionAuthority: {
    path: Artifacts.executionAuthority,
    owner: "execution-authority",
    producer: "createExecutionAuthority",
    consumers: ["execution-admission", "founder-operating-loop", "evidence"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionAuthorityLedger: {
    path: Artifacts.executionAuthorityLedger,
    owner: "execution-authority-ledger",
    producer: "execution authority correlation",
    consumers: ["operator", "execution-admission", "audit"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionApproval: {
    path: Artifacts.executionApproval,
    owner: "execution-approval-authority",
    producer: "pbos approve",
    consumers: ["execution-authority", "assignment", "admission", "operator"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionFabricAuthorization: {
    path: Artifacts.executionFabricAuthorization,
    owner: "execution-authorization-authority",
    producer: "pbos approve",
    consumers: ["assignment", "admission", "execution-fabric", "operator"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionAssignment: {
    path: Artifacts.executionAssignment,
    owner: "execution-assignment",
    producer: "pbos assign",
    consumers: ["execution-admission", "execution-fabric", "operator"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionEvidence: {
    path: Artifacts.executionEvidence,
    owner: "execution-evidence",
    producer: "ExecutionFabricRunner",
    consumers: ["validation", "certification", "lifecycle-advancement", "operator"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  executionTelemetry: {
    path: Artifacts.executionTelemetry,
    owner: "execution-provider-telemetry",
    producer: "Codex execution provider adapter",
    consumers: ["operator", "execution-fabric", "observability", "audit"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  milestoneAdvancement: {
    path: Artifacts.milestoneAdvancement,
    owner: "milestone-lifecycle-governance",
    producer: "Execution Fabric advancement",
    consumers: ["kernel-planner", "status", "operator", "audit"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  repositoryContext: {
    path: Artifacts.repositoryContext,
    owner: "repository-context",
    producer: "generateRepositoryContextArtifact",
    consumers: ["planner", "execution"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  contextRefresh: {
    path: Artifacts.contextRefresh,
    owner: "repository-context",
    producer: "pbos context",
    consumers: ["planner", "status", "context-audit"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  contextRefreshApproval: {
    path: Artifacts.contextRefreshApproval,
    owner: "context-refresh-authority",
    producer: "pbos approve-refresh",
    consumers: ["repository-context", "mission-control", "governance-audit"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  trustedBuildContext: {
    path: Artifacts.trustedBuildContext,
    owner: "context-activation-authority",
    producer: "pbos context-activate",
    consumers: ["planner", "execution-admission", "status", "evidence"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  changeBoundary: {
    path: Artifacts.changeBoundary,
    owner: "change-boundary-authority",
    producer: "pbos change-boundary",
    consumers: ["context-activation", "context-audit", "mission-control"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  launchApproval: {
    path: Artifacts.launchApproval,
    owner: "authority-ledger",
    producer: "pbos approve-boundary",
    consumers: ["context-activation", "mission-control", "governance-audit"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  artifactReconciliation: {
    path: Artifacts.artifactReconciliation,
    owner: "artifact-reconciliation",
    producer: "pbos reconcile-artifacts",
    consumers: ["status", "context", "governance-audit"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  lifecycleGovernance: {
    path: Artifacts.lifecycleGovernance,
    owner: "lifecycle-governance",
    producer: "pbos govern-lifecycle",
    consumers: ["completion", "promotion", "planner", "status"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  planningHandoff: {
    path: Artifacts.planningHandoff,
    owner: "planning-handoff",
    producer: "pbos planning-handoff",
    consumers: ["constitutional-planner", "governance-audit", "operator"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  workflow: {
    path: Artifacts.workflow,
    owner: "workflow-engine",
    producer: "pbos workflow",
    consumers: ["doctor", "evidence"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  doctor: {
    path: Artifacts.doctor,
    owner: "doctor-engine",
    producer: "pbos doctor",
    consumers: ["operator"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  manifest: {
    path: Artifacts.manifest,
    owner: "runtime-kernel",
    producer: "runtime initialization",
    consumers: ["runtime-kernel"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  promotion: {
    path: Artifacts.promotion,
    owner: "release-promotion",
    producer: "pbos promote",
    consumers: ["completion", "planner"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  activation: {
    path: Artifacts.activation,
    owner: "gate-lifecycle",
    producer: "pbos activate",
    consumers: ["lifecycle-audit", "evidence"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  completion: {
    path: Artifacts.completion,
    owner: "gate-lifecycle",
    producer: "pbos complete",
    consumers: ["lifecycle-audit", "evidence"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  runtimeState: {
    path: Artifacts.runtimeState,
    owner: "runtime-phase-manager",
    producer: "runtime phase transitions",
    consumers: ["runtime-phase-manager", "doctor"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  repositoryAnalysis: {
    path: Artifacts.repositoryAnalysis,
    owner: "repository-inspector",
    producer: "repository inspection",
    consumers: ["operator", "evidence"],
    persistence: "replaceable",
    cleanup: "replace-on-next-run",
  },
  executionHistory: {
    path: Artifacts.executionHistory,
    owner: "execution-history",
    producer: "execution history reporter",
    consumers: ["operator", "evidence"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  kernelExecutionHistory: {
    path: Artifacts.kernelExecutionHistory,
    owner: "kernel-runtime",
    producer: "PBOSKernelRuntime.execute",
    consumers: ["kernel-runtime", "certification", "operator", "recovery"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  volumeCertification: {
    path: Artifacts.volumeCertification,
    owner: "volume-certification",
    producer: "pbos certify-volume",
    consumers: ["constitutional-governance", "promotion-review"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  volumePromotion: {
    path: Artifacts.volumePromotion,
    owner: "volume-promotion",
    producer: "pbos promote-volume",
    consumers: ["volume-certification", "constitutional-governance"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  interfaceCertification: {
    path: Artifacts.interfaceCertification,
    owner: "interface-certification",
    producer: "pbos certify-volume",
    consumers: ["volume-certification", "volume-promotion"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
  interfaceMeasurement: {
    path: Artifacts.interfaceMeasurement,
    owner: "interface-measurement",
    producer: "pbos certify-volume",
    consumers: ["interface-certification", "constitutional-governance"],
    persistence: "durable",
    cleanup: "governed-transition",
  },
};
