import { digestValue } from "../context";
import type { LearnerDevelopment, LearningInput, LearningReport } from "./contracts";
import { createMasteryIndicators } from "./mastery";
import { createCompetencies, createSkills } from "./models";
import { createPathways } from "./pathways";
import { createMilestones, createReflections } from "./progress";
import { createRecommendations } from "./recommendations";
import { validateLearningInput } from "./validation";

export function createLearningReport(input: LearningInput): LearningReport { const { context, evidence } = validateLearningInput(input); const competencies = createCompetencies(input.competencyDrafts, input.learner.learnerId, evidence, context.contextDigest); const skills = createSkills(input.skillDrafts, input.learner.learnerId, evidence, context.contextDigest); const milestones = createMilestones(input.milestoneDrafts); const reflections = createReflections(input.reflectionDrafts, input.learner.learnerId); const masteryIndicators = createMasteryIndicators(competencies, skills, evidence); const pathways = createPathways(input.pathwayDrafts, competencies, milestones); const recommendations = createRecommendations(input.recommendationDrafts, input.learner.learnerId, competencies); const learner: LearnerDevelopment = { ...input.learner, evidenceHistory: evidence.map(({ evidenceId }) => evidenceId).sort(), agencyStatement: "The learner and authorized humans retain learning decision authority.", potentialAssessment: null }; const evidenceBundle = [...new Set([...evidence.map(({ evidenceId }) => evidenceId), ...input.knowledgeReports.flatMap((report) => report.evidenceBundle), ...input.strategyReports.flatMap((report) => report.evidenceBundle), ...input.simulationReports.flatMap((report) => report.evidenceBundle)])].sort(); const body = { generatedAt: input.generatedAt, runtimeContextDigest: context.contextDigest, learner, learnerEvidence: [...evidence].sort((a, b) => a.evidenceId.localeCompare(b.evidenceId)), competencies, skills, milestones, reflections, masteryIndicators, pathways, recommendations, evidenceBundle, limitations: ["Developmental indicators do not define potential, intelligence, worth, eligibility, or future success.", "Recommendations require learner choice and authorized human guidance."] }; return { reportId: `PBOS-LEARN-${digestValue(body).slice(0, 16).toUpperCase()}`, ...body }; }
