export type DocOwner =
  | "human"
  | "archivist"
  | "cartographer"
  | "sentinel"
  | "doc-governor"
  | "compass";

export type DocStatus =
  | "canonical"
  | "generated"
  | "frozen"
  | "deprecated"
  | "draft"
  | "archive";

export type DocLifecycle =
  | "active"
  | "planned"
  | "deprecated"
  | "archived";

export interface DocMetadata {
  title: string;
  doc_type: string;
  owner: DocOwner;
  status: DocStatus;
  canonical: boolean;
  auto_update: boolean;
  lifecycle: DocLifecycle;
}

export function parseFrontMatter(content: string): {
  metadata: Partial<DocMetadata>;
  body: string;
} {
  if (!content.startsWith("---")) {
    return { metadata: {}, body: content };
  }

  const end = content.indexOf("---", 3);
  if (end === -1) return { metadata: {}, body: content };

  const raw = content.slice(3, end).trim();
  const body = content.slice(end + 3).trim();

  const metadata: Record<string, any> = {};

  raw.split("\n").forEach((line) => {
    const [key, ...rest] = line.split(":");
    if (!key || !rest.length) return;

    const value = rest.join(":").trim();

    if (value === "true") metadata[key.trim()] = true;
    else if (value === "false") metadata[key.trim()] = false;
    else metadata[key.trim()] = value;
  });

  return { metadata, body };
}

export function inferDocMetadata(file: string, content: string): DocMetadata {
  const parsed = parseFrontMatter(content);
  const title =
    parsed.metadata.title ||
    content.match(/^#\s+(.+)$/m)?.[1] ||
    file.split("/").pop() ||
    "Untitled";

  const lower = file.toLowerCase();

  const inferredType =
    lower.includes("roadmap") ? "roadmap" :
    lower.includes("vision") ? "vision" :
    lower.includes("design") ? "design" :
    lower.includes("architecture") ? "architecture" :
    lower.includes("adr") || lower.includes("decision") ? "decision" :
    lower.includes("release") || lower.includes("changelog") || lower.includes("version") ? "release" :
    lower.includes("ledger") || lower.includes("log") ? "ledger" :
    lower.includes("history") || lower.includes("journal") ? "history" :
    lower.includes("sdk") ? "sdk" :
    "general";

  const owner =
    content.toLowerCase().includes("generated by playbook cartographer") ? "cartographer" :
    content.toLowerCase().includes("generated by playbook sentinel") ? "sentinel" :
    content.toLowerCase().includes("generated by playbook doc governor") ? "doc-governor" :
    lower.includes("daily_logs") || lower.includes("ledger") ? "archivist" :
    "human";

  const status =
    lower.includes("alpha_1") || lower.includes("snapshot") ? "frozen" :
    owner !== "human" ? "generated" :
    lower.includes("deprecated") ? "deprecated" :
    "canonical";

  return {
    title: String(title),
    doc_type: String(parsed.metadata.doc_type || inferredType),
    owner: (parsed.metadata.owner as any) || owner,
    status: (parsed.metadata.status as any) || status,
    canonical: parsed.metadata.canonical ?? (status === "canonical" || status === "frozen"),
    auto_update: parsed.metadata.auto_update ?? (owner !== "human"),
    lifecycle: (parsed.metadata.lifecycle as any) || (status === "deprecated" ? "deprecated" : "active"),
  };
}
