import { runDocGovernor } from "./DocGovernor";

function list(files: string[]) {
  if (!files.length) return "- None";
  return files.map(file => `- ${file}`).join("\n");
}

export function renderDocumentationIndex() {
  const report = runDocGovernor();

  return `# Playbook Documentation Index

Generated by Playbook Doc Governor.

## Documentation Health

${report.healthScore}%

## Summary

- Total docs: ${report.totalDocs}
- Human-authored docs: ${report.humanDocs}
- Generated docs: ${report.generatedDocs}
- Empty / thin docs: ${report.emptyDocs.length}
- Duplicate topic candidates: ${report.duplicateCandidates.length}

## Categories

${Object.entries(report.byCategory).map(([category, docs]) => `### ${category}

${docs.map(doc => `- ${doc.file} (${doc.words} words)`).join("\n")}
`).join("\n")}

## Empty / Thin Docs

${list(report.emptyDocs.map(doc => doc.file))}

## Duplicate Topic Candidates

${report.duplicateCandidates.length === 0 ? "- None" : report.duplicateCandidates.map(group => `### ${group.category}

Count: ${group.count}

${list(group.files)}
`).join("\n")}

## Guidance

- Use this index before creating new documentation.
- Merge duplicate roadmap, vision, milestone, and strategy documents when possible.
- Generated docs should be regenerated, not manually edited.
- Frozen snapshots should not be overwritten.
`;
}

export function renderDocumentationHealthReport() {
  const report = runDocGovernor();

  return `# Documentation Health Report

Generated by Playbook Doc Governor.

## Health Score

${report.healthScore}%

## Risks

### Empty / Thin Docs

${list(report.emptyDocs.map(doc => doc.file))}

### Duplicate Topic Candidates

${report.duplicateCandidates.length === 0 ? "- None" : report.duplicateCandidates.map(group => `- ${group.category}: ${group.count} files`).join("\n")}

## Recommended Actions

1. Fill or remove empty docs.
2. Merge duplicate docs by topic.
3. Keep one canonical roadmap.
4. Keep one canonical vision document.
5. Keep one canonical architecture index.
6. Let Cartographer regenerate generated architecture docs.
7. Let Archivist update logs and release records.
`;
}
