import { runDocGovernor } from "./DocGovernor";

function list(files: string[]) {
  if (!files.length) return "- None";
  return files.map(file => `- ${file}`).join("\n");
}

export function renderDocRegistry() {
  const report = runDocGovernor();

  return `# Documentation Registry

Generated by Playbook Doc Governor.

| Document | Type | Owner | Status | Canonical | Auto Update | Lifecycle |
|---|---|---|---|---|---|---|
${report.docs.map(doc =>
  `| ${doc.file} | ${doc.metadata.doc_type} | ${doc.metadata.owner} | ${doc.metadata.status} | ${doc.metadata.canonical ? "Yes" : "No"} | ${doc.metadata.auto_update ? "Yes" : "No"} | ${doc.metadata.lifecycle} |`
).join("\n")}
`;
}

export function renderDocumentationIndex() {
  const report = runDocGovernor();

  return `# Playbook Documentation Index

Generated by Playbook Doc Governor.

## Documentation Health

${report.scores.overall}%

## Score Breakdown

- Metadata quality: ${report.scores.metadata}%
- Thin-doc score: ${report.scores.thinDocs}%
- Duplicate-risk score: ${report.scores.duplicateRisk}%
- Stale-doc score: ${report.scores.staleDocs}%
- Canonical coverage: ${report.scores.canonicalCoverage}%

## Summary

- Total docs: ${report.docs.length}
- Canonical docs: ${report.canonicalDocs.length}
- Generated docs: ${report.generatedDocs.length}
- Frozen docs: ${report.frozenDocs.length}
- Thin docs: ${report.thinDocs.length}
- Duplicate topic candidates: ${report.duplicateCandidates.length}
- Stale docs: ${report.staleDocs.length}

## Categories

${Object.entries(report.byType).map(([type, docs]) => `### ${type}

${docs.map(doc => `- ${doc.file} (${doc.words} words, ${doc.metadata.status})`).join("\n")}
`).join("\n")}
`;
}

export function renderDocumentationHealthReport() {
  const report = runDocGovernor();

  return `# Documentation Health Report

Generated by Playbook Doc Governor.

## Overall Health

${report.scores.overall}%

## Score Breakdown

- Metadata quality: ${report.scores.metadata}%
- Thin-doc score: ${report.scores.thinDocs}%
- Duplicate-risk score: ${report.scores.duplicateRisk}%
- Stale-doc score: ${report.scores.staleDocs}%
- Canonical coverage: ${report.scores.canonicalCoverage}%

## Thin Docs

${list(report.thinDocs.map(doc => doc.file))}

## Duplicate Topic Candidates

${report.duplicateCandidates.length === 0 ? "- None" : report.duplicateCandidates.map(group => `### ${group.docType}

Count: ${group.count}

Canonical candidates:
${list(group.canonical)}

All files:
${list(group.files)}
`).join("\n")}

## Stale Docs

${list(report.staleDocs.map(doc => doc.file))}

## Recommended Actions

1. Add metadata to canonical docs.
2. Merge duplicate docs into canonical docs.
3. Move reviewed duplicates to docs/DEPRECATED.
4. Keep generated docs auto-generated.
5. Keep frozen snapshots unchanged.
`;
}

export function renderMergeRecommendations() {
  const report = runDocGovernor();

  return `# Documentation Merge Recommendations

Generated by Playbook Doc Governor.

${report.duplicateCandidates.length === 0 ? "- No merge recommendations." : report.duplicateCandidates.map(group => {
  const target =
    group.docType === "roadmap" ? "docs/PRODUCT_ROADMAP.md" :
    group.docType === "vision" ? "docs/VISION/VISION.md" :
    group.docType === "architecture" ? "docs/PLAYBOOK_OS.md or docs/ARCHITECTURE/CURRENT_ARCHITECTURE.md" :
    group.docType === "design" ? "docs/DESIGN/PLAYBOOK_DESIGN_SYSTEM.md" :
    group.docType === "decision" ? "docs/ADR/ADR_LOG.md" :
    group.docType === "release" ? "CHANGELOG.md and docs/LEDGER/RELEASE_HISTORY.md" :
    "Review manually";

  return `## ${group.docType}

Recommendation: merge related content into ${target}

Confidence: ${group.count >= 5 ? "High" : "Medium"}

Files:
${list(group.files)}
`;
}).join("\n")}
`;
}

export function renderDocLifecycle() {
  return `# Documentation Lifecycle

Generated by Playbook Doc Governor.

## Lifecycle States

### Draft

New document. May be incomplete.

### Canonical

Primary source of truth for a topic.

### Generated

Automatically created by Archivist, Cartographer, Sentinel, or Doc Governor.

### Frozen

Historical snapshot. Do not overwrite.

### Deprecated

Merged or replaced. Keep temporarily for review.

### Archived

Preserved for history but no longer active.

## Ownership

- human: edited intentionally
- archivist: historical logs
- cartographer: architecture maps
- sentinel: health reports
- doc-governor: documentation intelligence
- compass: future guidance drafts

## Rule

Before creating a new document, check DOCUMENTATION_INDEX and DOC_REGISTRY.
`;
}
