import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const DOC_ROOT = path.join(ROOT, "docs");

const IGNORE = [".next", "node_modules", ".git", "coverage", "dist", "build"];

function walk(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];

  return fs.readdirSync(dir).flatMap((item) => {
    if (IGNORE.includes(item)) return [];

    const full = path.join(dir, item);
    const stat = fs.statSync(full);

    if (stat.isDirectory()) return walk(full);

    return full.endsWith(".md") ? [full.replace(ROOT + "/", "")] : [];
  });
}

export function scanDocs() {
  const files = walk(DOC_ROOT);

  const docs = files.map((file) => {
    const content = fs.readFileSync(file, "utf8");
    const words = content.trim().split(/\s+/).filter(Boolean).length;
    const title = content.match(/^#\s+(.+)$/m)?.[1] || path.basename(file);

    return {
      file,
      title,
      words,
      isEmpty: words < 40,
      isGenerated:
        content.toLowerCase().includes("generated by playbook cartographer") ||
        content.toLowerCase().includes("generated by playbook sentinel") ||
        file.includes("DAILY_LOGS"),
      category: classifyDoc(file, title),
    };
  });

  return docs;
}

function classifyDoc(file: string, title: string) {
  const key = `${file} ${title}`.toLowerCase();

  if (key.includes("roadmap")) return "roadmap";
  if (key.includes("vision")) return "vision";
  if (key.includes("milestone")) return "milestones";
  if (key.includes("release") || key.includes("changelog") || key.includes("version")) return "release";
  if (key.includes("decision") || key.includes("adr")) return "decision";
  if (key.includes("architecture") || key.includes("system") || key.includes("graph")) return "architecture";
  if (key.includes("design")) return "design";
  if (key.includes("history") || key.includes("journal")) return "history";
  if (key.includes("ledger") || key.includes("log")) return "ledger";
  if (key.includes("intelligence") || key.includes("compass") || key.includes("academic") || key.includes("opportunity")) return "intelligence";

  return "general";
}
