import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { EcosystemReport } from "../ecosystem";
import type { IdentityReport } from "../identity";
import type { RoleInput } from "./contracts";
import { createRoleReport } from "./engine";
import { RoleError } from "./errors";

function input(): RoleInput {
  const content = "canonical role authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-816", title: "Role Governance", version: "1.0.0", location: "docs/PPS/PPS-816.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-816", location: "docs/PPS/PPS-816.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const digest = runtimeContext.contextDigest;
  const evidence = ["role:scholar", "role:founder", "approval:scholar", "approval:founder"];
  const identityReports = [{ reportId: "IDENT-1", runtimeContextDigest: digest, identityState: { personReference: "PERSON-1" }, ownershipInformation: { ownerIdentity: "PERSON-1" }, verificationStatus: [{ status: "VERIFIED" }], provenanceEvidence: evidence, consentHistory: [{ consentId: "CONSENT-SCHOLAR", status: "GRANTED", purpose: "personal-scholar-experience", authorizedRecipient: "PERSON-1", expiresAt: "2027-01-01T00:00:00.000Z", evidenceReferences: ["role:scholar"] }, { consentId: "CONSENT-FOUNDER", status: "GRANTED", purpose: "personal-founder-experience", authorizedRecipient: "PERSON-1", expiresAt: "2027-01-01T00:00:00.000Z", evidenceReferences: ["role:founder"] }] }] as unknown as IdentityReport[];
  const ecosystemReports = [{ reportId: "ECO-1", runtimeContextDigest: digest, ecosystemEntities: [], relationships: [], evidenceBundle: evidence }] as unknown as EcosystemReport[];
  return { runtimeContext, identityReports, ecosystemReports, compassReports: [], academicReports: [], athleticReports: [], portfolioReports: [], opportunityReports: [], roleAssignments: [{ personIdentity: "PERSON-1", roleType: "SCHOLAR", organizationIdentity: null, relationshipId: null, requestedPermissions: ["VIEW", "CONNECT", "EXPORT"], purpose: "personal-scholar-experience", verificationStatus: "VERIFIED", consentRequired: true, consentId: "CONSENT-SCHOLAR", authorizationEvidence: ["role:scholar"], requestedAt: "2026-07-25T00:00:00.000Z" }, { personIdentity: "PERSON-1", roleType: "FOUNDER", organizationIdentity: null, relationshipId: null, requestedPermissions: ["VIEW", "SHARE", "EXPORT"], purpose: "personal-founder-experience", verificationStatus: "VERIFIED", consentRequired: true, consentId: "CONSENT-FOUNDER", authorizationEvidence: ["role:founder"], requestedAt: "2026-07-25T00:00:00.000Z" }], approvals: [{ approvalId: "APPROVAL-SCHOLAR", personIdentity: "PERSON-1", roleType: "SCHOLAR", organizationIdentity: null, approvedPermissions: ["VIEW", "CONNECT", "EXPORT"], approvalScope: "ROLE_VERIFICATION", approverIdentity: "ROLE-REVIEWER", approvedAt: "2026-07-25T00:00:00.000Z", evidenceReferences: ["approval:scholar"], status: "APPROVED" }, { approvalId: "APPROVAL-FOUNDER", personIdentity: "PERSON-1", roleType: "FOUNDER", organizationIdentity: null, approvedPermissions: ["VIEW", "SHARE", "EXPORT"], approvalScope: "ROLE_VERIFICATION", approverIdentity: "ROLE-REVIEWER", approvedAt: "2026-07-25T00:00:00.000Z", evidenceReferences: ["approval:founder"], status: "APPROVED" }], generatedAt: "2026-07-26T00:00:00.000Z", authorizedPersonIdentities: ["PERSON-1"], inferredRoleRequested: false, permissionBypassRequested: false, authorityCreationRequested: false, privacyBypassRequested: false, institutionalDecisionRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(RoleError); return (error as RoleError).failures.map(({ code }) => code); } }
describe("PBOS governed Role OS", () => {
  it("keeps roles identity-bound in deterministic reports", () => { const first = createRoleReport(input()); expect(createRoleReport(input())).toEqual(first); expect(first.roleRecords.every(({ identityBound }) => identityBound)).toBe(true); });
  it("preserves explicit permissions without authority creation", () => { expect(createRoleReport(input()).roleRecords[0]).toMatchObject({ createsAuthority: false, permanentIdentityLabel: false }); });
  it("enforces consent evidence", () => { const role = createRoleReport(input()).roleRecords.find(({ roleType }) => roleType === "SCHOLAR")!; expect(role.provenance).toMatchObject({ consentId: "CONSENT-SCHOLAR", authorizationEvidence: ["role:scholar"] }); });
  it("derives deterministic role-scoped dashboards", () => { const dashboard = createRoleReport(input()).dashboards.find(({ roleType }) => roleType === "SCHOLAR")!; expect(dashboard).toMatchObject({ enabledEngines: ["ACADEMIC", "COMPASS", "IDENTITY", "OPPORTUNITY", "PORTFOLIO"], derivedFromRoleAuthority: true, crossRolePermissionMerge: false }); });
  it("supports separate multiple roles", () => { const profile = createRoleReport(input()).multiRoleProfiles[0]; expect(profile.roleIds).toHaveLength(2); expect(profile.rolesKeptSeparate).toBe(true); expect(Object.keys(profile.permissionsByRole)).toHaveLength(2); });
  it("rejects unauthorized access", () => { const value = input(); value.authorizedPersonIdentities = []; expect(codes(() => createRoleReport(value))).toContain("UNAUTHORIZED_ACCESS"); });
  it("rejects inferred roles", () => { const value = input(); value.inferredRoleRequested = true; expect(codes(() => createRoleReport(value))).toContain("INFERRED_ROLE"); });
  it("rejects permission bypass", () => { const value = input(); value.permissionBypassRequested = true; expect(codes(() => createRoleReport(value))).toContain("PERMISSION_BYPASS"); });
  it("rejects authority creation", () => { const value = input(); value.authorityCreationRequested = true; expect(codes(() => createRoleReport(value))).toContain("AUTHORITY_CREATION"); });
  it("rejects privacy violations", () => { const value = input(); value.privacyBypassRequested = true; expect(codes(() => createRoleReport(value))).toContain("PRIVACY_VIOLATION"); });
});
