import { digestValue } from "../context";
import { createAcademicAdvisors } from "./advisors";
import { createAGTracking } from "./ag";
import type { AcademicInput, AcademicProvenance, AcademicReport, ScholarAthleteAcademicSupport } from "./contracts";
import { createCoursework } from "./coursework";
import { createFinancialReadiness } from "./financial";
import { createAcademicIdentity, createInstitutions } from "./models";
import { createAcademicPathways } from "./pathways";
import { assessAcademicReadiness } from "./readiness";
import { evaluateRequirements } from "./requirements";
import { validateAcademicInput } from "./validation";
export function createAcademicReport(input: AcademicInput): AcademicReport {
  const context = validateAcademicInput(input); const student = input.academicIdentityDraft.studentIdentity;
  const sourceReportIds = [...input.identityReports.map(({ reportId }) => reportId), ...input.learningReports.map(({ reportId }) => reportId), ...input.masteryReports.map(({ reportId }) => reportId), ...input.credentialReports.map(({ reportId }) => reportId), ...input.opportunityReports.map(({ reportId }) => reportId), ...input.athleticReports.map(({ reportId }) => reportId)].sort();
  const evidence = [...new Set([...input.academicIdentityDraft.evidenceReferences, ...input.institutionDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.courseworkDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.requirementDrafts.flatMap(({ requiredEvidence }) => requiredEvidence), ...input.agRequirementDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.financialMilestoneDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.milestones.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.advisorDrafts.flatMap(({ relationshipEvidenceReferences }) => relationshipEvidenceReferences)])].sort();
  const provenance: AcademicProvenance = { runtimeContextDigest: context.contextDigest, studentOwnerIdentity: student, sourceReportIds, sourceReferences: [...new Set([input.academicIdentityDraft.sourceReference, ...input.institutionDrafts.map(({ sourceReference }) => sourceReference), ...input.financialMilestoneDrafts.map(({ sourceReference }) => sourceReference)])].sort(), evidenceReferences: evidence, generatedAt: input.generatedAt, authorizedActor: student };
  const academicProfile = createAcademicIdentity(input.academicIdentityDraft, provenance); const coursework = createCoursework(input.courseworkDrafts, student, provenance); const requirements = evaluateRequirements(input.requirementDrafts, coursework); const advisors = createAcademicAdvisors(input.advisorDrafts, student); const normalizedMilestones = input.milestones.map((milestone) => ({ ...milestone, requirementIds: [...milestone.requirementIds].sort(), evidenceReferences: [...milestone.evidenceReferences].sort() })).sort((a, b) => a.milestoneId.localeCompare(b.milestoneId));
  const scholarAthleteSupport: ScholarAthleteAcademicSupport | null = input.athleticReports.length ? { supportId: `PBOS-ACAD-ATH-${digestValue({ student, athleticReportIds: input.athleticReports.map(({ reportId }) => reportId).sort(), requirements: requirements.map(({ requirementId }) => requirementId).sort() }).slice(0, 16).toUpperCase()}`, studentIdentity: student, eligibilityRequirementIds: requirements.filter(({ requirementType }) => requirementType === "ATHLETIC_ELIGIBILITY").map(({ requirementId }) => requirementId).sort(), academicMilestoneIds: normalizedMilestones.map(({ milestoneId }) => milestoneId).sort(), balanceConsiderations: ["Coordinate academic workload and athletic commitments with authorized human advisors."], supportAdvisorIds: advisors.map(({ advisorRecordId }) => advisorRecordId).sort(), athleticEvidenceReferences: [...new Set(input.athleticReports.flatMap(({ provenanceBundle }) => provenanceBundle.evidenceReferences))].sort(), eligibilityDecisionMade: false } : null;
  const body = { generatedAt: input.generatedAt, runtimeContextDigest: context.contextDigest, academicProfile, institutions: createInstitutions(input.institutionDrafts, provenance), coursework, requirements, pathways: createAcademicPathways(academicProfile, requirements), agTracking: createAGTracking(input.agRequirementDrafts, coursework), financialReadiness: createFinancialReadiness(input.financialMilestoneDrafts), milestones: normalizedMilestones, advisors, readinessIndicators: assessAcademicReadiness(input, coursework, requirements), scholarAthleteSupport, evidence, limitations: ["Academic intelligence does not alter grades or records, rank students, infer intelligence, replace advisors, or decide admission, eligibility, graduation, credentials, aid, or scholarships.", "Pathway and readiness outputs describe current evidence and cannot guarantee outcomes."], provenance };
  return { reportId: `PBOS-ACAD-REPORT-${digestValue(body).slice(0, 16).toUpperCase()}`, ...body };
}
