import { digestValue, type PBOSRuntimeContext } from "../context";
import type { AcademicInput } from "./contracts";
import { AcademicError, academicFailure } from "./errors";
function validContext(context: PBOSRuntimeContext): boolean { const body = { ...context }; delete (body as Partial<PBOSRuntimeContext>).contextDigest; return context.documentInventory.length > 0 && context.contextDigest === digestValue(body); }
export function validateAcademicInput(input: AcademicInput): PBOSRuntimeContext {
  if (!input.runtimeContext || !validContext(input.runtimeContext)) throw new AcademicError([academicFailure("INVALID_CONTEXT", "A valid constitutional Runtime Context is required.")]);
  const student = input.academicIdentityDraft.studentIdentity;
  if (!input.authorizedStudentIdentities.includes(student) || input.privacyBypassRequested) throw new AcademicError([academicFailure("UNAUTHORIZED_ACCESS", "Academic data requires student authorization.")]);
  if (input.fabricatedCourseworkRequested) throw new AcademicError([academicFailure("FABRICATED_COURSEWORK", "Coursework and grades cannot be fabricated.")]);
  if (input.alteredGradeRequested) throw new AcademicError([academicFailure("ALTERED_RECORD", "PBOS cannot alter grades, transcripts, or academic records.")]);
  if (input.unsupportedRequirementRequested) throw new AcademicError([academicFailure("UNSUPPORTED_REQUIREMENT", "Academic requirements require an identified authority source.")]);
  if (input.guaranteedOutcomeRequested) throw new AcademicError([academicFailure("GUARANTEED_OUTCOME", "Admission, graduation, scholarships, aid, and eligibility cannot be guaranteed.")]);
  if (input.rankingRequested) throw new AcademicError([academicFailure("RANKING_PROHIBITED", "PBOS cannot rank students.")]);
  if (input.intelligenceInferenceRequested) throw new AcademicError([academicFailure("INFERENCE_PROHIBITED", "PBOS cannot infer intelligence or student value.")]);
  if (input.institutionalDecisionRequested) throw new AcademicError([academicFailure("INSTITUTIONAL_DECISION_PROHIBITED", "PBOS cannot decide grades, admission, eligibility, graduation, or institutional records.")]);
  if (Number.isNaN(Date.parse(input.generatedAt))) throw new AcademicError([academicFailure("MISSING_EVIDENCE", "A valid report timestamp is required.")]);
  const digest = input.runtimeContext.contextDigest;
  const identity = input.identityReports.find(({ identityState }) => identityState.personReference === student);
  if (!identity || identity.runtimeContextDigest !== digest || identity.ownershipInformation.ownerIdentity !== student || !identity.ownershipInformation.personOwnsRecord) throw new AcademicError([academicFailure("OWNERSHIP_VIOLATION", "A student-owned Identity report is required.")]);
  if (!input.learningReports.length || !input.masteryReports.length || !input.credentialReports.length || !input.opportunityReports.length ||
    input.learningReports.some((report) => report.runtimeContextDigest !== digest || report.learner.learnerId !== student) || input.masteryReports.some((report) => report.runtimeContextDigest !== digest || report.learnerId !== student) || input.credentialReports.some((report) => report.runtimeContextDigest !== digest || report.recipientIdentity !== student) || input.opportunityReports.some((report) => report.runtimeContextDigest !== digest) || input.athleticReports.some((report) => report.runtimeContextDigest !== digest || report.athleteIdentity.ownerIdentity !== student)) throw new AcademicError([academicFailure("PRIVACY_VIOLATION", "Academic intelligence inputs must match the student and active context.")]);
  if (!input.academicIdentityDraft.permissions.length || !input.academicIdentityDraft.sourceReference || !input.academicIdentityDraft.evidenceReferences.length) throw new AcademicError([academicFailure("MISSING_EVIDENCE", "Academic identity requires permissions and provenance.")]);
  const knownEvidence = new Set([...identity.provenanceEvidence, ...input.learningReports.flatMap(({ evidenceBundle }) => evidenceBundle), ...input.masteryReports.flatMap(({ evidenceBundle }) => evidenceBundle), ...input.credentialReports.flatMap(({ evidenceBundle }) => evidenceBundle), ...input.opportunityReports.flatMap(({ evidenceBundle }) => evidenceBundle), ...input.athleticReports.flatMap(({ provenanceBundle }) => provenanceBundle.evidenceReferences)]);
  const referenced = [...input.academicIdentityDraft.evidenceReferences, ...input.institutionDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.courseworkDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.requirementDrafts.flatMap(({ requiredEvidence }) => requiredEvidence), ...input.agRequirementDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.financialMilestoneDrafts.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.milestones.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.advisorDrafts.flatMap(({ relationshipEvidenceReferences }) => relationshipEvidenceReferences)];
  if (!referenced.length || referenced.some((reference) => !knownEvidence.has(reference))) throw new AcademicError([academicFailure("MISSING_EVIDENCE", "Every academic artifact must cite authorized evidence provenance.")]);
  const institutions = new Map(input.institutionDrafts.map((institution) => [institution.institutionIdentity, institution]));
  if (!input.institutionDrafts.length || input.institutionDrafts.some((institution) => institution.verificationStatus !== "VERIFIED" || !institution.sourceReference || !institution.authorityScope.length || !institution.evidenceReferences.length)) throw new AcademicError([academicFailure("UNSUPPORTED_REQUIREMENT", "Institutions require verified identity, authority scope, and evidence.")]);
  if (!input.courseworkDrafts.length || input.courseworkDrafts.some((course) => !institutions.has(course.institutionIdentity) || course.credits < 0 || !course.evidenceReferences.length || (course.recordClass === "VERIFIED_INSTITUTIONAL_RECORD" && !course.sourceAuthority) || (course.status === "COMPLETED" && course.recordClass !== "VERIFIED_INSTITUTIONAL_RECORD"))) throw new AcademicError([academicFailure("FABRICATED_COURSEWORK", "Completed coursework requires a verified institution, evidence, credits, and source authority.")]);
  const courseNames = new Set(input.courseworkDrafts.map(({ courseName }) => courseName));
  const requirementIds = new Set(input.requirementDrafts.map(({ requirementId }) => requirementId));
  if (!input.requirementDrafts.length || input.requirementDrafts.some((requirement) => !institutions.has(requirement.authoritySource) || !requirement.category || !requirement.requiredEvidence.length || !requirement.completionCriteria.length || !requirement.limitations.length || requirement.applicableCourseNames.some((name) => !courseNames.has(name)))) throw new AcademicError([academicFailure("UNSUPPORTED_REQUIREMENT", "Requirements require verified authority, criteria, evidence, limitations, and known coursework.")]);
  if (input.agRequirementDrafts.some((ag) => !institutions.has(ag.sourceAuthority) || !ag.requiredCourseNames.length || !ag.evidenceReferences.length)) throw new AcademicError([academicFailure("UNSUPPORTED_REQUIREMENT", "A-G requirements require an institutional authority, courses, and evidence.")]);
  if (input.financialMilestoneDrafts.some((milestone) => Number.isNaN(Date.parse(milestone.dueAt)) || !milestone.sourceReference || !milestone.evidenceReferences.length)) throw new AcademicError([academicFailure("MISSING_EVIDENCE", "Financial readiness milestones require a source, deadline, and evidence.")]);
  if (input.milestones.some((milestone) => Number.isNaN(Date.parse(milestone.targetAt)) || milestone.requirementIds.some((id) => !requirementIds.has(id)) || !milestone.evidenceReferences.length || milestone.institutionalCompletionDecision !== false)) throw new AcademicError([academicFailure("FALSE_COMPLETION", "Milestones require known requirements, evidence, dates, and no institutional completion decision.")]);
  const now = Date.parse(input.generatedAt);
  if (input.advisorDrafts.some((advisor) => { const consent = identity.consentHistory.find((item) => item.consentId === advisor.consentId && item.status === "GRANTED" && item.authorizedRecipient === advisor.advisorIdentity && item.purpose === "academic-advising" && (!item.expiresAt || Date.parse(item.expiresAt) > now)); return advisor.identityVerificationStatus !== "VERIFIED" || !advisor.permissions.includes("VIEW") || !advisor.permissions.includes("CONNECT_ADVISOR") || !advisor.relationshipEvidenceReferences.length || !consent || advisor.relationshipEvidenceReferences.some((reference) => !consent.evidenceReferences.includes(reference)); })) throw new AcademicError([academicFailure("UNAUTHORIZED_ADVISOR", "Advisors require verified identity, explicit permissions, active consent, and relationship evidence.")]);
  return input.runtimeContext;
}
