import { digestValue } from "../context";
import type { MobilityInput, MobilityJourney, MobilityReadiness, MobilityReadinessStatus, MobilityReport } from "./contracts";
import { validateMobilityInput } from "./validation";
const id = (prefix: string, value: unknown): string => `${prefix}-${digestValue(value).slice(0, 16).toUpperCase()}`;
export function createMobilityReport(input: MobilityInput): MobilityReport {
  const context = validateMobilityInput(input); const sourceReportIds = [...input.identityReports, ...input.academicReports, ...input.athleticReports, ...input.portfolioReports, ...input.opportunityReports, ...input.ecosystemReports, ...input.communicationReports].map(({ reportId }) => reportId).sort();
  const journeys: MobilityJourney[] = input.journeyDrafts.map((draft) => { const knownRequirementIds = draft.requirementIds.filter((requirementId) => input.requirements.some(({ requirementId: id }) => id === requirementId)); const completedPreparation = draft.transition.preparationActivities.filter(({ classification }) => classification === "FACT").map(({ statement }) => statement).sort(); const missingInformation = draft.transition.possibleBarriers.filter(({ classification }) => classification === "INFORMATION_GAP").map(({ statement }) => statement).sort(); const status: MobilityReadinessStatus = missingInformation.length ? "INFORMATION_NEEDED" : completedPreparation.length >= knownRequirementIds.length ? "READY_FOR_REVIEW" : completedPreparation.length ? "IN_PROGRESS" : "PREPARING"; const readinessBody = { transitionGoal: draft.goal, status, knownRequirementIds: [...knownRequirementIds].sort(), completedPreparation, missingInformation, evidenceReferences: [...draft.evidenceReferences].sort(), limitations: ["Readiness is informational and never guarantees placement, admission, employment, or success."], informationalOnly: true as const, guaranteesSuccess: false as const }; const readiness: MobilityReadiness = { readinessId: id("PBOS-MOBILITY-READY", readinessBody), ...readinessBody }; const evidenceReferences = [...draft.evidenceReferences].sort(); const body = { ...draft, requirementIds: [...draft.requirementIds].sort(), supportRelationshipIds: [...draft.supportRelationshipIds].sort(), opportunityIds: [...draft.opportunityIds].sort(), documentIds: [...draft.documentIds].sort(), evidenceReferences, ownerIdentity: draft.personIdentity, ownershipStatus: "PERSON_OWNED_PBOS_STEWARD" as const, readiness, athleticDecisionMade: false as const, admissionDecisionMade: false as const, employmentDecisionMade: false as const, placementGuaranteed: false as const, provenance: { runtimeContextDigest: context.contextDigest, sourceReportIds, evidenceReferences, generatedAt: input.generatedAt, authorizedActor: draft.personIdentity } }; return { journeyId: id("PBOS-MOBILITY-JOURNEY", body), ...body }; }).sort((a, b) => a.journeyId.localeCompare(b.journeyId));
  const evidenceBundle = [...new Set([...journeys.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.requirements.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.supports.flatMap(({ evidenceReferences }) => evidenceReferences), ...input.documents.flatMap(({ evidenceReferences }) => evidenceReferences)])].sort();
  const body = { generatedAt: input.generatedAt, runtimeContextDigest: context.contextDigest, personIdentities: [...new Set(journeys.map(({ personIdentity }) => personIdentity))].sort(), journeys, origins: journeys.map(({ origin }) => origin), destinations: journeys.map(({ destination }) => destination), requirements: [...input.requirements].sort((a, b) => a.requirementId.localeCompare(b.requirementId)), readiness: journeys.map(({ readiness }) => readiness), opportunityIds: [...new Set(journeys.flatMap(({ opportunityIds }) => opportunityIds))].sort(), supportResources: [...input.supports].sort((a, b) => a.relationshipId.localeCompare(b.relationshipId)), documents: [...input.documents].sort((a, b) => a.documentId.localeCompare(b.documentId)), evidenceBundle, limitations: ["Mobility outputs are advisory and person-controlled; human authorities decide admissions, recruiting, contracts, employment, and institutional outcomes.", "International documentation is informational and is not immigration or legal advice."] };
  return { reportId: id("PBOS-MOBILITY-REPORT", body), ...body };
}
