import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { CommunicationReport } from "../communication";
import type { EcosystemReport } from "../ecosystem";
import type { IdentityReport } from "../identity";
import type { OpportunityReport } from "../opportunity";
import type { MobilityInput } from "./contracts";
import { createMobilityReport } from "./engine";
import { MobilityError } from "./errors";

function input(category: MobilityInput["journeyDrafts"][number]["category"] = "INTERNATIONAL_TRANSITION"): MobilityInput {
  const content = "canonical mobility authority"; const runtimeContext = compileContext({ sources: [{ identifier: "PPS-818", title: "Mobility Governance", version: "1.0.0", location: "docs/PPS/PPS-818.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-818", location: "docs/PPS/PPS-818.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const digest = runtimeContext.contextDigest; const evidence = ["journey:1", "requirement:1", "support:1", "document:1"];
  const identityReports = [{ reportId: "IDENT-1", runtimeContextDigest: digest, identityState: { personReference: "PERSON-1" }, ownershipInformation: { ownerIdentity: "PERSON-1" }, provenanceEvidence: evidence }] as unknown as IdentityReport[];
  const opportunityReports = [{ reportId: "OPP-REPORT-1", runtimeContextDigest: digest, opportunityInventory: [{ opportunityId: "OPP-1" }], evidenceBundle: evidence }] as unknown as OpportunityReport[];
  const ecosystemReports = [{ reportId: "ECO-1", runtimeContextDigest: digest, evidenceBundle: evidence, relationships: [{ relationshipId: "REL-1", consentStatus: "CONSENTED", status: "ACTIVE" }] }] as unknown as EcosystemReport[];
  const communicationReports = [{ reportId: "COMM-1", runtimeContextDigest: digest, evidenceBundle: evidence, messages: [{ messageId: "MSG-1" }] }] as unknown as CommunicationReport[];
  return { runtimeContext, identityReports, academicReports: [], athleticReports: [], portfolioReports: [], opportunityReports, ecosystemReports, communicationReports, journeyDrafts: [{ personIdentity: "PERSON-1", category, origin: { country: "United States", region: "California", locality: "Oakland", organizationIdentity: null, verified: true, sourceAuthority: "SOURCE-ORIGIN", evidenceReferences: ["journey:1"] }, destination: { country: "Spain", region: "Catalonia", locality: "Barcelona", organizationIdentity: "ORG-1", verified: true, sourceAuthority: "SOURCE-DESTINATION", evidenceReferences: ["journey:1"] }, goal: category === "ATHLETIC_TRANSITION" ? "Explore a verified overseas team pathway" : "Explore an international education and development pathway", timeline: { startsAt: "2026-08-01T00:00:00.000Z", targetAt: "2027-08-01T00:00:00.000Z" }, evidenceReferences: ["journey:1"], requirementIds: ["REQ-1"], supportRelationshipIds: ["REL-1"], limitations: ["No outcome is guaranteed."], transition: { currentState: "domestic preparation", desiredState: "international pathway review", preparationActivities: [{ classification: "POSSIBLE_NEXT_STEP", statement: "Review verified documentation requirements", evidenceReferences: ["journey:1"], limitations: [] }], requirementIds: ["REQ-1"], milestones: [{ classification: "RECOMMENDATION", statement: "Schedule a human advisor review", evidenceReferences: ["journey:1"], limitations: [] }], resourceReferences: ["SUPPORT-1"], possibleBarriers: [{ classification: "INFORMATION_GAP", statement: "Eligibility decision remains unknown", evidenceReferences: ["journey:1"], limitations: [] }], supportOptions: ["Verified advisor"] }, opportunityIds: ["OPP-1"], documentIds: ["DOC-1"] }], requirements: [{ requirementId: "REQ-1", category: "DOCUMENTATION", description: "Verify destination documentation requirements", sourceAuthority: "DESTINATION-AUTHORITY", verificationStatus: "VERIFIED", evidenceReferences: ["requirement:1"], limitations: ["Informational only"], legalDetermination: false }], supports: [{ supporterIdentity: "ADVISOR-1", relationshipId: "REL-1", communicationMessageId: "MSG-1", role: "ADVISOR", consentId: "CONSENT-1", permissions: ["VIEW", "CONNECT"], evidenceReferences: ["support:1"] }], documents: [{ documentId: "DOC-1", category: "TRAVEL_AND_ELIGIBILITY", sourceAuthority: "DESTINATION-AUTHORITY", status: "NEEDED", evidenceReferences: ["document:1"], legalAdvice: false }], authorizedPersonIdentities: ["PERSON-1"], generatedAt: "2026-07-26T00:00:00.000Z", guaranteedOutcomeRequested: false, fabricatedPathwayRequested: false, recruitingDecisionRequested: false, admissionsDecisionRequested: false, employmentDecisionRequested: false, legalDeterminationRequested: false, rankingRequested: false, privacyBypassRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(MobilityError); return (error as MobilityError).failures.map(({ code }) => code); } }
describe("PBOS governed Mobility Engine", () => {
  it("preserves person ownership in deterministic reports", () => { const first = createMobilityReport(input()); expect(createMobilityReport(input())).toEqual(first); expect(first.journeys[0]).toMatchObject({ ownerIdentity: "PERSON-1", ownershipStatus: "PERSON_OWNED_PBOS_STEWARD" }); });
  it("preserves transition evidence and classifications", () => { expect(createMobilityReport(input()).journeys[0].transition.possibleBarriers[0].classification).toBe("INFORMATION_GAP"); });
  it("supports advisory athletic mobility", () => { expect(createMobilityReport(input("ATHLETIC_TRANSITION")).journeys[0]).toMatchObject({ athleticDecisionMade: false, placementGuaranteed: false }); });
  it("supports international pathways without legal advice", () => { const report = createMobilityReport(input()); expect(report.destinations[0].country).toBe("Spain"); expect(report.documents[0].legalAdvice).toBe(false); });
  it("requires consented support and authorized communication", () => { expect(createMobilityReport(input()).supportResources[0]).toMatchObject({ relationshipId: "REL-1", communicationMessageId: "MSG-1", permissions: ["VIEW", "CONNECT"] }); });
  it("rejects guaranteed outcomes", () => { const value = input(); value.guaranteedOutcomeRequested = true; expect(codes(() => createMobilityReport(value))).toContain("GUARANTEED_OUTCOME"); });
  it("rejects unauthorized access", () => { const value = input(); value.authorizedPersonIdentities = []; expect(codes(() => createMobilityReport(value))).toContain("UNAUTHORIZED_ACCESS"); });
  it("rejects fabricated pathways", () => { const value = input(); value.fabricatedPathwayRequested = true; expect(codes(() => createMobilityReport(value))).toContain("FABRICATED_DESTINATION"); });
  it("rejects recruiting and admissions decisions", () => { const recruiting = input(); recruiting.recruitingDecisionRequested = true; expect(codes(() => createMobilityReport(recruiting))).toContain("RECRUITING_DECISION_PROHIBITED"); const admissions = input(); admissions.admissionsDecisionRequested = true; expect(codes(() => createMobilityReport(admissions))).toContain("ADMISSIONS_DECISION_PROHIBITED"); });
  it("rejects privacy violations", () => { const value = input(); value.privacyBypassRequested = true; expect(codes(() => createMobilityReport(value))).toContain("PRIVACY_VIOLATION"); });
});
