import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const registryPath = path.join(root, "founder", "project.json");

const phaseDefinitions = [
  {
    number: 1,
    title: "Identity & Authentication",
    tasks: [
      "Login",
      "Signup",
      "Google Login",
      "Password Reset",
      "Remember Me",
      "Logout",
      "Session Timeout",
      "Close Browser Logout",
      "CAPTCHA",
      "PKCE",
      "Email Verification",
      "Hostinger Email",
      "Email Templates",
      "Role Selection",
      "Authentication Security Testing",
      "Authentication Mobile Testing",
    ],
  },
  {
    number: 2,
    title: "Onboarding",
    tasks: [
      "Scholar Onboarding",
      "Scholar-Athlete Onboarding",
      "Parent Guardian Onboarding",
      "Teacher Educator Onboarding",
      "High School Counselor Onboarding",
      "Mentor Onboarding",
      "High School Coach Onboarding",
      "College Coach Recruiter Onboarding",
      "College Admissions Onboarding",
      "Brand Partner Onboarding",
      "Transition-Aged Youth Onboarding",
      "Athlete Abroad Enrollment",
      "Dynamic User Agreement",
      "Onboarding Autosave",
      "Profile Creation Animation",
      "Public Profile Generation",
      "Onboarding OS Redirects",
    ],
  },
  {
    number: 3,
    title: "Public Profile",
    tasks: [
      "Avatar",
      "Cover Photo",
      "Username",
      "Biography",
      "Activities",
      "Athletics",
      "Transcript",
      "Dream Schools",
      "Top Colleges",
      "Certificates",
      "Badges",
      "XP",
      "Coins",
      "Connections",
      "Public Timeline",
      "Privacy Settings",
      "Private Profile Editing",
    ],
  },
  {
    number: 4,
    title: "Operating Systems",
    tasks: [
      "Scholar OS",
      "Scholar-Athlete OS",
      "Parent Guardian OS",
      "Teacher Educator OS",
      "High School Counselor OS",
      "Mentor OS",
      "High School Coach OS",
      "College Coach Recruiter OS",
      "College Admissions OS",
      "Brand Partner OS",
      "Employer OS",
      "Founder OS",
      "Athletes Abroad Hub",
      "Role-Aware Sidebar Navigation",
      "Role Permissions",
    ],
  },
  {
    number: 5,
    title: "Network",
    tasks: [
      "User Search",
      "Suggested Users",
      "Connection Requests",
      "Accept Requests",
      "Decline Requests",
      "Cancel Requests",
      "Remove Connections",
      "Mutual Connections",
      "Public Profile Links",
      "Network Notifications",
      "Network Messaging Integration",
    ],
  },
  {
    number: 6,
    title: "Feed",
    tasks: [
      "Real Author Identity",
      "Create Post",
      "Image Posts",
      "Video Posts",
      "Comments",
      "Likes",
      "Shares",
      "Edit Post",
      "Delete Post",
      "Profile Links",
      "Timeline Visibility",
      "Infinite Scroll",
      "Feed Moderation",
    ],
  },
  {
    number: 7,
    title: "Messaging",
    tasks: [
      "Direct Messages",
      "Group Messages",
      "Conversation Search",
      "Attachments",
      "Read Receipts",
      "Message Notifications",
      "Block User",
      "Report User",
      "Meeting Links",
    ],
  },
  {
    number: 8,
    title: "Courses",
    tasks: [
      "Course Library",
      "Course Search",
      "Course Detail",
      "Module Completion",
      "Progress Tracking",
      "Reflections",
      "Quizzes",
      "XP Rewards",
      "Coin Rewards",
      "Certificates",
      "Community Safety Course",
      "Athletes Abroad Course",
    ],
  },
  {
    number: 9,
    title: "Academic",
    tasks: [
      "Transcript Upload",
      "Transcript Parsing",
      "A-G Tracker",
      "FAFSA Tracker",
      "Scholarships",
      "College Search",
      "Dream Schools",
      "Top Schools",
      "Application Deadlines",
      "Application Tracker",
      "Academic Readiness",
      "Compass Recommendations",
    ],
  },
  {
    number: 10,
    title: "Recruiting",
    tasks: [
      "Athlete Profile",
      "Film",
      "Measurements",
      "Statistics",
      "Eligibility",
      "Coach Connections",
      "Recruiter Search",
      "College Targets",
      "Visits",
      "Offers",
      "Recruiting Timeline",
      "NIL Readiness",
    ],
  },
  {
    number: 11,
    title: "Events",
    tasks: [
      "Browse Events",
      "Event Detail",
      "RSVP",
      "Calendar Integration",
      "Reminders",
      "QR Check-In",
      "Event Networking",
      "Replay Library",
      "Summit Events",
    ],
  },
  {
    number: 12,
    title: "Brand Partner Marketplace",
    tasks: [
      "Organization Profiles",
      "Campaign Builder",
      "Rewards",
      "Internships",
      "Jobs",
      "Sponsorships",
      "NIL Opportunities",
      "Scholarships",
      "Mentorship",
      "Opportunity Applicants",
      "Opportunity Tracking",
      "Compliance Review",
    ],
  },
  {
    number: 13,
    title: "Athletes Abroad Hub",
    tasks: [
      "Go Abroad",
      "Living Abroad",
      "Life After Sport",
      "Global Athlete Profile",
      "Career History",
      "Country Channels",
      "Sport Channels",
      "Global Locker Room",
      "Summit Integration",
      "Summit Meetings",
      "Meetups",
      "Housing Resources",
      "Healthcare Resources",
      "Tax Resources",
      "Contract Resources",
      "Alumni Network",
    ],
  },
  {
    number: 14,
    title: "Founder Dashboard",
    tasks: [
      "Project Intelligence",
      "Analytics",
      "User Management",
      "Verification",
      "Moderation",
      "Feature Flags",
      "Bug Tracking",
      "Release Management",
      "Architecture Viewer",
      "Documentation Center",
      "Content Review",
      "System Health",
    ],
  },
  {
    number: 15,
    title: "Platform QA",
    tasks: [
      "Scholar End-to-End QA",
      "Scholar-Athlete End-to-End QA",
      "Parent Guardian End-to-End QA",
      "Teacher Educator End-to-End QA",
      "Counselor End-to-End QA",
      "Mentor End-to-End QA",
      "High School Coach End-to-End QA",
      "College Coach End-to-End QA",
      "Admissions End-to-End QA",
      "Brand Partner End-to-End QA",
      "Employer End-to-End QA",
      "Founder End-to-End QA",
      "Athlete Abroad End-to-End QA",
      "Desktop QA",
      "Tablet QA",
      "Mobile QA",
      "Accessibility QA",
      "Performance QA",
      "Security QA",
      "RLS Audit",
      "Production Build",
      "Soft Launch",
      "Beta Feedback",
      "Final Launch QA",
    ],
  },
];

function slug(value) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

if (fs.existsSync(registryPath)) {
  console.log("ℹ️ founder/project.json already exists. Bootstrap skipped.");
  process.exit(0);
}

const phases = phaseDefinitions.map((phase) => ({
  id: `phase-${phase.number}`,
  number: phase.number,
  title: phase.title,
  status: "not_started",
  completionPercent: 0,
}));

const tasks = phaseDefinitions.flatMap((phase) =>
  phase.tasks.map((title) => ({
    id: `${slug(phase.title)}--${slug(title)}`,
    phaseId: `phase-${phase.number}`,
    title,
    status: "not_started",
    owner: "",
    notes: "",
    dependencies: [],
    acceptanceCriteria: [
      "UI matches Playbook design language",
      "Data persists and reads correctly",
      "Role permissions are verified",
      "TypeScript passes",
      "Tests pass",
      "Production build passes",
      "End-to-end workflow is verified",
    ],
    filesTouched: [],
    completedAt: null,
  }))
);

const registry = {
  version: 1,
  projectName: "Playbook OS",
  founder: "Stephisha Walton",
  updatedAt: new Date().toISOString(),
  overallCompletionPercent: 0,
  currentPhaseId: "phase-1",
  currentTaskId: tasks[0]?.id || null,
  phases,
  tasks,
  events: [],
  bugs: [],
  decisions: [],
};

fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2) + "\n");
console.log(`✅ Founder Knowledge Base created at ${registryPath}`);
