import type { AcademicReport } from "../academic"; import type { AthleticReport } from "../athletics"; import type { PBOSRuntimeContext } from "../context"; import type { CredentialReport } from "../credential"; import type { EcosystemReport } from "../ecosystem"; import type { IdentityReport } from "../identity"; import type { MasteryReport } from "../mastery"; import type { OpportunityReport } from "../opportunity"; import type { PortfolioReport } from "../portfolio";
export type GoalCategory="ACADEMIC_GOAL"|"ATHLETIC_GOAL"|"CAREER_GOAL"|"ENTREPRENEURSHIP_GOAL"|"PERSONAL_DEVELOPMENT_GOAL"|"COMMUNITY_GOAL"|"LIFELONG_LEARNING_GOAL"; export type GuidanceCategory="ACADEMIC"|"ATHLETIC"|"CAREER"|"FINANCIAL"|"PERSONAL_DEVELOPMENT"; export type InsightKind="FACT"|"PATTERN"|"INFORMATION_GAP"|"RECOMMENDATION"; export type Confidence="HIGH"|"MEDIUM"|"LOW"; export type CompassPermission="VIEW"|"CONNECT"|"SHARE"|"FEEDBACK";
export interface CompassProvenance{runtimeContextDigest:string;personIdentity:string;sourceReportIds:string[];evidenceReferences:string[];generatedAt:string;authorizedActor:string}
export interface GoalDraft{personIdentity:string;category:GoalCategory;statement:string;timeline:string;evidenceReferences:string[];ownerConfirmed:boolean} export interface PersonGoal extends GoalDraft{goalId:string;ownership:"PERSON_OWNED";provenance:CompassProvenance}
export interface JourneyInsight{kind:InsightKind;statement:string;evidenceReferences:string[];limitations:string[]} export interface JourneyState{journeyId:string;personIdentity:string;goalIds:string[];currentStage:string;evidenceReferences:string[];accomplishments:string[];activePathways:string[];challenges:string[];availableResourceIds:string[];insights:JourneyInsight[];limitations:string[]}
export interface Resource{resourceId:string;name:string;category:GuidanceCategory;sourceEngine:string;evidenceReferences:string[];limitations:string[]}
export interface RecommendationDraft{personIdentity:string;relatedGoalStatement:string;category:GuidanceCategory;suggestedAction:string;reason:string;possibleBenefit:string;resourceNames:string[];supporterEntityIds:string[];evidenceReferences:string[];sourceEngine:string;limitations:string[];confidence:Confidence}
export interface NextAction extends RecommendationDraft{recommendationId:string;relatedGoalId:string;availableResourceIds:string[];supportOptions:string[];provenance:CompassProvenance;advisoryOnly:true;actionType:"POSSIBLE_NEXT_STEP";requiredAction:false;outcomeGuaranteed:false;choices:("ACCEPT"|"DISMISS"|"MODIFY"|"REFLECT"|"PROVIDE_FEEDBACK")[]}
export interface SupportConnectionDraft{personIdentity:string;supporterEntityId:string;relationshipId:string;permissions:CompassPermission[];purpose:string;evidenceReferences:string[];consentId:string;identityVerified:boolean}
export interface SupportConnection extends SupportConnectionDraft{connectionId:string;accessAuthorized:true;connectionAutomatic:false}
export interface CompassInput{runtimeContext:PBOSRuntimeContext|null;identityReports:IdentityReport[];portfolioReports:PortfolioReport[];academicReports:AcademicReport[];athleticReports:AthleticReport[];masteryReports:MasteryReport[];credentialReports:CredentialReport[];opportunityReports:OpportunityReport[];ecosystemReports:EcosystemReport[];personIdentity:string;goalDrafts:GoalDraft[];recommendationDrafts:RecommendationDraft[];supportConnectionDrafts:SupportConnectionDraft[];generatedAt:string;authorizedPersonIdentities:string[];fabricatedGoalRequested:boolean;unsupportedGuidanceRequested:boolean;hiddenDecisionRequested:boolean;guaranteedOutcomeRequested:boolean;rankingRequested:boolean;decisionRequested:boolean}
export interface CompassReport{reportId:string;generatedAt:string;runtimeContextDigest:string;personIdentityReference:string;goals:PersonGoal[];journeyState:JourneyState;recommendations:NextAction[];evidence:string[];limitations:string[];supportResources:Resource[];supportConnections:SupportConnection[];provenanceBundle:CompassProvenance}
export type CompassState="CREATED"|"UNDERSTANDING"|"MAPPING"|"IDENTIFYING_OPTIONS"|"PRESENTING_GUIDANCE"|"USER_REVIEW"|"ACTION_SELECTED"|"REFLECTION"|"ARCHIVED"; export interface CompassLifecycleState{currentState:CompassState;transitions:{from:CompassState;to:CompassState;transitionedAt:string;authorityIdentity:string;evidenceReferences:string[]}[]} export type CompassFailureCode="INVALID_CONTEXT"|"UNSUPPORTED_GUIDANCE"|"FABRICATED_GOAL"|"UNAUTHORIZED_ACCESS"|"GUARANTEED_OUTCOME"|"HIDDEN_DECISION"|"MISSING_EVIDENCE"|"RANKING_PROHIBITED"|"DECISION_PROHIBITED"|"INVALID_TRANSITION"|"GOVERNANCE_BYPASS"; export interface CompassFailure{code:CompassFailureCode;message:string}
