import { digestValue, type PBOSRuntimeContext } from "../context";
import type { InstitutionInput } from "./contracts";
import { InstitutionError, institutionFailure } from "./errors";
function valid(context: PBOSRuntimeContext): boolean { const body = { ...context }; delete (body as Partial<PBOSRuntimeContext>).contextDigest; return context.documentInventory.length > 0 && context.contextDigest === digestValue(body); }
function fail(code: Parameters<typeof institutionFailure>[0], message: string): never { throw new InstitutionError([institutionFailure(code, message)]); }
export function validateInstitutionInput(input: InstitutionInput): PBOSRuntimeContext {
  if (!input.runtimeContext || !valid(input.runtimeContext)) fail("INVALID_CONTEXT", "A valid Runtime Context is required."); const context = input.runtimeContext as PBOSRuntimeContext;
  if (input.fakeInstitutionRequested) fail("FAKE_INSTITUTION", "Institutions cannot be fabricated."); if (input.unauthorizedRepresentativeRequested) fail("UNAUTHORIZED_REPRESENTATIVE", "Representatives require verified access."); if (input.privacyBypassRequested) fail("PRIVACY_VIOLATION", "Participant privacy cannot be bypassed."); if (input.unsupportedOutcomeRequested) fail("UNSUPPORTED_OUTCOME", "Unsupported impact claims are prohibited."); if (input.consentBypassRequested) fail("CONSENT_BYPASS", "Participant consent cannot be bypassed."); if (input.participantRankingRequested) fail("RANKING_PROHIBITED", "Institutions cannot rank participants."); if (input.institutionalDecisionRequested) fail("INSTITUTIONAL_DECISION_PROHIBITED", "PBOS cannot make admissions, employment, or recruiting decisions."); if (input.dataSaleRequested) fail("DATA_SALE_PROHIBITED", "Participant data cannot be sold.");
  const reports = [...input.identityReports, ...input.ecosystemReports, ...input.roleReports, ...input.opportunityReports, ...input.academicReports, ...input.athleticReports, ...input.communicationReports, ...input.mobilityReports]; if (reports.some((report) => report.runtimeContextDigest !== context.contextDigest)) fail("PRIVACY_VIOLATION", "All reports must share the active Runtime Context.");
  const roles = new Map(input.roleReports.flatMap((r) => r.roleRecords.map((role) => [role.roleId, role] as const))); const entities = new Set(input.ecosystemReports.flatMap((r) => r.ecosystemEntities.filter(({ verificationStatus }) => verificationStatus === "VERIFIED").map(({ entityId }) => entityId))); const identities = new Map(input.identityReports.map((r) => [r.identityState.personReference, r])); const messages = new Set(input.communicationReports.flatMap((r) => r.messages.map(({ messageId }) => messageId))); const evidence = new Set([...input.identityReports.flatMap((r) => r.provenanceEvidence), ...input.ecosystemReports.flatMap((r) => r.evidenceBundle), ...input.roleReports.flatMap((r) => r.evidenceBundle), ...input.communicationReports.flatMap((r) => r.evidenceBundle)]);
  for (const institution of input.institutionDrafts) { const approval = input.approvals.find((a) => a.approvalId === institution.approvalId && a.institutionIdentity === institution.institutionIdentity && a.scope === "INSTITUTION_VERIFICATION" && a.status === "APPROVED"); if (institution.verificationStatus !== "VERIFIED" || !entities.has(institution.institutionIdentity) || !approval || !institution.evidenceReferences.length || institution.evidenceReferences.some((ref) => !evidence.has(ref))) fail("FAKE_INSTITUTION", "Verified Ecosystem identity, evidence, and human approval are required."); for (const roleId of institution.representativeRoleIds) { const role = roles.get(roleId); if (!role || role.organizationIdentity !== institution.institutionIdentity || role.state !== "ACTIVE" || !input.approvals.some((a) => a.institutionIdentity === institution.institutionIdentity && a.scope === "REPRESENTATIVE_ACCESS" && a.status === "APPROVED")) fail("UNAUTHORIZED_REPRESENTATIVE", "Representatives require active organization-bound roles and approval."); } }
  for (const relationship of input.relationshipDrafts) { const identity = identities.get(relationship.personIdentity); const institution = input.institutionDrafts.find((i) => i.institutionIdentity === relationship.institutionIdentity && i.verificationStatus === "VERIFIED"); const consent = identity?.consentHistory.find((c) => c.consentId === relationship.consentId && c.status === "GRANTED" && c.purpose === relationship.purpose && c.authorizedRecipient === relationship.institutionIdentity); if (!identity?.verificationStatus.some(({ status }) => status === "VERIFIED") || !institution || !consent || !relationship.permissions.length || !relationship.evidenceReferences.length) fail("INVALID_RELATIONSHIP", "Relationships require verified parties, purpose, permission, consent, and evidence."); }
  const relationships = new Set(input.relationshipDrafts.map(({ relationshipId }) => relationshipId)); for (const program of input.programDrafts) if (!input.institutionDrafts.some((i) => i.institutionIdentity === program.institutionIdentity && i.verificationStatus === "VERIFIED") || !program.purpose || !program.evidenceReferences.length || program.participantRelationshipIds.some((id) => !relationships.has(id)) || Date.parse(program.endsAt) <= Date.parse(program.startsAt)) fail("INVALID_PROGRAM", "Programs require verified institutions, purpose, participants, timeline, and evidence.");
  const programs = new Set(input.programDrafts.map(({ programId }) => programId)); for (const cohort of input.cohortDrafts) if (!programs.has(cohort.programId) || cohort.memberRelationshipIds.some((id) => !relationships.has(id)) || cohort.communicationMessageIds.some((id) => !messages.has(id))) fail("INVALID_PROGRAM", "Cohorts require valid programs, relationships, and communication authorization."); for (const impact of input.impactDrafts) if (!programs.has(impact.programId) || !impact.limitations.length || impact.statements.some((s) => !s.evidenceReferences.length) || impact.statements.some((s) => s.classification === "FACT" && !s.evidenceReferences.every((ref) => evidence.has(ref)))) fail("UNSUPPORTED_OUTCOME", "Impact requires evidence and limitations and cannot imply unsupported causality."); return context;
}
