import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { KnowledgeReport } from "../knowledge";
import type { LearningReport } from "../learning";
import type { MasteryInput } from "./contracts";
import { MasteryError } from "./errors";
import { createMasteryReport } from "./reporting";

function input(): MasteryInput {
  const content = "canonical mastery authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-809", title: "Mastery Governance", version: "1.0.0", location: "docs/PPS/PPS-809.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-809", location: "docs/PPS/PPS-809.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const competency = { competencyId: "COMP-1", name: "Evidence Communication", description: "Communicate evidence.", evidenceRequirements: ["project"], relatedSkillNames: ["Presentation"], masteryIndicators: ["Demonstration"], limitations: ["Context-specific"], sourceEvidenceIds: ["LEARN-EVID-1"], provenance: { learnerId: "LEARNER-1", evidenceIds: ["LEARN-EVID-1"], sourceReferences: ["learning:1"], owners: ["LEARNER-1"], runtimeContextDigest: runtimeContext.contextDigest }, developmental: true as const };
  const learning: LearningReport = { reportId: "LEARN-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learner: { learnerId: "LEARNER-1", learningGoals: [], interests: [], currentCompetencyIds: ["COMP-1"], growthAreas: [], evidenceHistory: ["LEARN-EVID-1"], mentorRelationships: ["REVIEWER-1"], learningPreferences: [], agencyStatement: "The learner and authorized humans retain learning decision authority.", potentialAssessment: null }, learnerEvidence: [], competencies: [competency], skills: [], milestones: [], reflections: [], masteryIndicators: [], pathways: [], recommendations: [], evidenceBundle: ["learning:evidence"], limitations: [] };
  const knowledge: KnowledgeReport = { reportId: "KNOW-1", runtimeContextDigest: runtimeContext.contextDigest, generatedAt: "2026-07-25T00:00:00.000Z", knowledgeSources: [], entities: [], relationships: [], precedents: [], lessons: [], evidenceBundle: ["knowledge:evidence"], confidenceClassification: "MEDIUM" };
  return { runtimeContext, learnerId: "LEARNER-1", learningReports: [learning], knowledgeReports: [knowledge], evidence: [{ evidenceId: "EVID-1", learnerId: "LEARNER-1", evidenceType: "PROJECT", description: "Evidence presentation", sourceReference: "portfolio:project:1", owner: "LEARNER-1", occurredAt: "2026-07-24T00:00:00.000Z", verificationStatus: "VERIFIED", permissions: ["PORTFOLIO", "DEMONSTRATION", "ACHIEVEMENT", "CREDENTIAL", "MASTERY_REPORT"] }, { evidenceId: "EVID-2", learnerId: "LEARNER-1", evidenceType: "ACHIEVEMENT", description: "Presentation completion", sourceReference: "achievement:1", owner: "LEARNER-1", occurredAt: "2026-07-25T00:00:00.000Z", verificationStatus: "VERIFIED", permissions: ["PORTFOLIO", "ACHIEVEMENT", "CREDENTIAL", "MASTERY_REPORT"] }], validations: [{ validationId: "VAL-1", evidenceIds: ["EVID-1"], reviewerId: "REVIEWER-1", reviewerRole: "MENTOR", validationDate: "2026-07-25T00:00:00.000Z", validationPurpose: "Review contextual competency demonstration.", status: "VALIDATED", limitations: ["One context only."] }], approvedReviewerIds: ["REVIEWER-1"], demonstrationDrafts: [{ competencyName: "Evidence Communication", activity: "Evidence presentation", category: "ACADEMIC", evidenceIds: ["EVID-1"], validationIds: ["VAL-1"], feedback: ["Sources explained clearly"], context: "Mentor-reviewed project presentation." }], portfolioDraft: { artifactEvidenceIds: ["EVID-1", "EVID-2"], competencyNames: ["Evidence Communication"], achievementDescriptions: ["Presentation completion"], reflectionEvidenceIds: [], validationIds: ["VAL-1"] }, achievementDrafts: [{ description: "Presentation completion", category: "ACADEMIC", date: "2026-07-25T00:00:00.000Z", evidenceIds: ["EVID-2"], associatedCompetencyNames: ["Evidence Communication"] }], credentialDrafts: [{ issuingOrganization: "Example Learning Organization", requirements: ["Complete presentation"], evidenceIds: ["EVID-2"], completionStatus: "COMPLETED", verificationStatus: "VERIFIED", associatedCompetencyNames: ["Evidence Communication"] }], progressionRequests: [{ competencyName: "Evidence Communication", requestedProgression: "DEMONSTRATED", evidenceIds: ["EVID-1"], validationIds: ["VAL-1"] }], generatedAt: "2026-07-26T00:00:00.000Z", authorizedLearnerIds: ["LEARNER-1"], rankingRequested: false, potentialInferenceRequested: false, highImpactDecisionRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(MasteryError); return (error as MasteryError).failures.map(({ code }) => code); } }

describe("PBOS governed mastery intelligence", () => {
  it("creates deterministic mastery records from verified evidence", () => { const first = createMasteryReport(input()); expect(createMasteryReport(input())).toEqual(first); expect(first.reportId).toMatch(/^PBOS-MAST-[A-F0-9]{16}$/); expect(first.masteryProgression[0].statement).toContain("not a measure of human worth"); });
  it("preserves demonstration evidence and human validation provenance", () => { const demonstration = createMasteryReport(input()).demonstrations[0]; expect(demonstration).toMatchObject({ learnerId: "LEARNER-1", reviewers: ["REVIEWER-1"], validationStatus: "VALIDATED" }); expect(demonstration.provenance.evidenceIds).toEqual(["EVID-1"]); });
  it("preserves portfolio ownership and permissions", () => { const portfolio = createMasteryReport(input()).portfolio; expect(portfolio).toMatchObject({ owner: "LEARNER-1", learnerId: "LEARNER-1", manufacturedAchievements: false }); expect(portfolio.permissions).toContain("PORTFOLIO"); });
  it("keeps credential completion distinct from mastery", () => { expect(createMasteryReport(input()).credentials[0]).toMatchObject({ completionStatus: "COMPLETED", demonstrated: false, mastered: false, completionIsNotMastery: true }); });
  it("rejects missing evidence", () => { const value = input(); value.demonstrationDrafts[0].evidenceIds = ["UNKNOWN"]; expect(codes(() => createMasteryReport(value))).toContain("MISSING_EVIDENCE"); });
  it("rejects unsupported mastery progression", () => { const value = input(); value.progressionRequests[0].requestedProgression = "RECOGNIZED_MASTERY"; expect(codes(() => createMasteryReport(value))).toContain("UNSUPPORTED_MASTERY"); });
  it("rejects unauthorized validation", () => { const value = input(); value.approvedReviewerIds = []; expect(codes(() => createMasteryReport(value))).toContain("UNAUTHORIZED_VALIDATION"); });
  it("rejects identity mismatch", () => { const value = input(); value.evidence[0].learnerId = "OTHER"; expect(codes(() => createMasteryReport(value))).toContain("IDENTITY_MISMATCH"); });
  it("rejects privacy violations", () => { const value = input(); value.evidence[0].permissions = ["MASTERY_REPORT"]; expect(codes(() => createMasteryReport(value))).toContain("PRIVACY_VIOLATION"); });
  it("rejects ranking requests", () => { const value = input(); value.rankingRequested = true; expect(codes(() => createMasteryReport(value))).toContain("RANKING_PROHIBITED"); });
});
