import { digestValue } from "../context";
import { assessMastery } from "./assessment";
import { createCredentials } from "./credentials";
import { createDemonstrations } from "./demonstrations";
import type { MasteryInput, MasteryReport } from "./contracts";
import { createAchievements } from "./models";
import { createPortfolio } from "./portfolio";
import { validateMasteryInput } from "./validation";
export function createMasteryReport(input: MasteryInput): MasteryReport { const { context, evidence } = validateMasteryInput(input); const learningCompetencies = input.learningReports.flatMap((report) => report.competencies).filter((item, index, all) => all.findIndex(({ competencyId }) => competencyId === item.competencyId) === index); const demonstrations = createDemonstrations(input.demonstrationDrafts, input.learnerId, evidence, input.validations, context.contextDigest); const achievements = createAchievements(input.achievementDrafts, input.learnerId, evidence, context.contextDigest); const portfolio = createPortfolio(input.portfolioDraft, input.learnerId, evidence, context.contextDigest, input.generatedAt); const credentials = createCredentials(input.credentialDrafts); const masteryProgression = assessMastery(learningCompetencies, demonstrations); const evidenceBundle = [...new Set([...evidence.map(({ evidenceId }) => evidenceId), ...input.learningReports.flatMap((report) => report.evidenceBundle), ...input.knowledgeReports.flatMap((report) => report.evidenceBundle), ...input.validations.flatMap((item) => item.evidenceIds)])].sort(); const body = { generatedAt: input.generatedAt, runtimeContextDigest: context.contextDigest, learnerId: input.learnerId, competencies: learningCompetencies.map(({ competencyId, name: competencyName }) => ({ competencyId, competencyName })).sort((a, b) => a.competencyId.localeCompare(b.competencyId)), demonstrations, achievements, portfolio, credentials, masteryProgression, limitations: ["Mastery records are contextual and developmental, not permanent labels.", "No output measures human worth, intelligence, potential, employability, or admissions eligibility."], confidence: masteryProgression.some(({ validationStatus }) => validationStatus === "HUMAN_VALIDATED") ? "MEDIUM" as const : "LOW" as const, evidenceBundle }; return { reportId: `PBOS-MAST-${digestValue(body).slice(0, 16).toUpperCase()}`, ...body }; }
