import Link from "next/link";

const evidenceAreas = [
  { title:"Transcript", body:"Courses, credits, grades, source, and observation time." },
  { title:"Requirements", body:"Applicable graduation or college requirements and the authority that supplied them." },
  { title:"Readiness", body:"Evidence-backed progress, known gaps, unknowns, and the date of the calculation." },
];

export default function AcademicReadinessPage() {
  return <main style={page}><header style={hero}><p style={eyebrow}>Academic path</p><h1 style={title}>Know what the evidence says—and what it does not.</h1><p style={lead}>Academic readiness connects verified records to understandable progress. It does not infer eligibility, completion, or a recommendation when sources are missing or stale.</p><Link href="/transcript" style={primary}>Review transcript evidence</Link></header><section style={panel} aria-labelledby="readiness-state"><h2 id="readiness-state">Readiness status</h2><div role="status" style={empty}><strong>No verified readiness summary is available on this route.</strong><span>Review your transcript first. Missing evidence is different from zero progress, and consequential guidance remains blocked until its source is current.</span></div></section><section style={panel} aria-labelledby="evidence-required"><h2 id="evidence-required">Evidence required for guidance</h2><div style={grid}>{evidenceAreas.map(area=><article key={area.title} style={card}><h3>{area.title}</h3><p style={copy}>{area.body}</p></article>)}</div></section><section style={panel} aria-labelledby="future-tools"><h2 id="future-tools">Intelligence tools</h2><p style={copy}>Academic DNA, Compass, Oracle, and opportunity matching remain advisory and unavailable here until an authorized capability decision and evidence-backed read model are present.</p><div style={actions}><Link href="/profile" style={secondary}>Review academic profile</Link><Link href="/opportunities" style={secondary}>View opportunity state</Link></div></section><aside style={boundary}><strong>Stale-evidence boundary:</strong> guidance must show when evidence was observed. Outdated or unavailable evidence cannot support a consequential recommendation.</aside></main>;
}
const page:React.CSSProperties={minHeight:"100vh",background:"#F8F7F4",padding:"clamp(22px,5vw,60px)",color:"#0F172A",fontFamily:"system-ui,sans-serif"}; const hero:React.CSSProperties={maxWidth:980,margin:"0 auto",background:"#0F172A",color:"#fff",borderRadius:26,padding:"clamp(28px,5vw,54px)"}; const eyebrow:React.CSSProperties={color:"#FDBA74",fontWeight:800,textTransform:"uppercase",letterSpacing:".15em",fontSize:11}; const title:React.CSSProperties={fontSize:"clamp(38px,6vw,64px)",lineHeight:1.02,margin:"12px 0"}; const lead:React.CSSProperties={fontSize:17,lineHeight:1.65,color:"#CBD5E1",maxWidth:760,marginBottom:24}; const primary:React.CSSProperties={display:"inline-block",background:"#F97316",color:"#fff",textDecoration:"none",padding:"12px 16px",borderRadius:10,fontWeight:800}; const panel:React.CSSProperties={maxWidth:980,margin:"18px auto",background:"#fff",border:"1px solid #E2E8F0",borderRadius:20,padding:24}; const empty:React.CSSProperties={display:"grid",gap:8,background:"#FFF7ED",padding:20,borderRadius:14,color:"#475569"}; const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}; const card:React.CSSProperties={border:"1px solid #E2E8F0",borderRadius:14,padding:18}; const copy:React.CSSProperties={color:"#475569",lineHeight:1.6}; const actions:React.CSSProperties={display:"flex",gap:10,flexWrap:"wrap"}; const secondary:React.CSSProperties={border:"1px solid #CBD5E1",color:"#0F172A",textDecoration:"none",padding:"10px 13px",borderRadius:10,fontWeight:800}; const boundary:React.CSSProperties={maxWidth:980,margin:"18px auto",background:"#EFF6FF",borderLeft:"4px solid #2563EB",padding:18,lineHeight:1.6};
