"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { PlaybookButton, PlaybookCard, PlaybookGrid, PlaybookHero, PlaybookMetric, PlaybookMetrics, PlaybookPage } from "@/components/ui";
import { supabase } from "@/lib/supabaseClient";
import { buildAcademicReadinessSnapshot, type AcademicProgressRow, type AcademicReadinessSnapshot, type ApplicationWorkspaceSummary } from "@/lib/academic-readiness/academicReadiness";

type DecisionState="PENDING"|"ACCEPTED"|"REJECTED"|"MODIFIED"|"COMPLETED";
type EvidenceRecord={id:string;recommendation_key:string|null;decision_state:DecisionState;decision_note:string|null;outcome:Record<string,unknown>|null};
type ReadinessLoadResult={ownerId:string;agProgress:AcademicProgressRow[];applications:ApplicationWorkspaceSummary[];evidenceRecord:EvidenceRecord};
const readinessAreas=[
 {label:"Transcript intelligence",title:"Start with the evidence",body:"Upload or review the academic record that powers A–G calculations and readiness decisions.",href:"/transcript",action:"Open transcript"},
 {label:"Financial aid",title:"Keep FAFSA moving",body:"Track preparation, submission, processing, and action-required milestones without storing unnecessary sensitive financial data.",href:"/fafsa",action:"Open FAFSA tracker"},
 {label:"Application workspace",title:"Move readiness into execution",body:"Use your existing application workspaces for requirements, evidence, documents, review, and submission progress.",href:"/application-workspaces",action:"Open applications"},
 {label:"Scholar Record",title:"Keep the whole story connected",body:"Academic progress remains part of the same Scholar Record as achievements, experiences, goals, and verified evidence.",href:"/record",action:"Open Scholar Record"},
 {label:"Compass",title:"Turn evidence into guidance",body:"Compass can build on the same canonical readiness evidence without replacing your record or your decisions.",href:"/compass",action:"Open Compass"},
 {label:"Support",title:"Bring the right people into the plan",body:"Coordinate counselors, educators, family, mentors, and coaches through authorized relationships.",href:"/support-network",action:"Open support network"},
 {label:"Opportunity",title:"Activate what your progress unlocks",body:"Explore opportunities after current academic blockers and active application work are understood.",href:"/opportunities",action:"Explore opportunities"},
] as const;
async function readAcademicReadiness():Promise<ReadinessLoadResult|null>{const{data:authData,error:authError}=await supabase.auth.getUser();if(authError||!authData.user)return null;const ownerId=authData.user.id;const[agResult,applicationResult]=await Promise.all([supabase.from("ag_progress").select("subject,years_completed,years_required,in_progress").eq("user_id",ownerId),supabase.from("application_workspaces").select("id,opportunity_name,opportunity_type,status,deadline").eq("scholar_id",ownerId).neq("status","archived")]);if(agResult.error||applicationResult.error)throw new Error(agResult.error?.message||applicationResult.error?.message||"Academic readiness could not be loaded.");const agProgress=(agResult.data||[]) as AcademicProgressRow[];const applications=(applicationResult.data||[]) as ApplicationWorkspaceSummary[];const snapshot=buildAcademicReadinessSnapshot({agProgress,applications});const idempotencyKey=`academic-readiness:${ownerId}:${snapshot.primaryRecommendation.key}:${snapshot.readinessScore}`;const now=new Date().toISOString();const{data:record,error:evidenceError}=await supabase.from("academic_journey_evidence").upsert({owner_id:ownerId,readiness_score:snapshot.readinessScore,ag_updates:snapshot.agSubjectsMet,idempotency_key:idempotencyKey,delivery_state:"DELIVERED",delivered_at:now,recommendation_key:snapshot.primaryRecommendation.key,primary_recommendation:snapshot.primaryRecommendation,provenance:[{source:"ag_progress",count:agProgress.length},{source:"application_workspaces",count:applications.length}],updated_at:now},{onConflict:"idempotency_key"}).select("id,recommendation_key,decision_state,decision_note,outcome").single();if(evidenceError||!record)throw new Error(evidenceError?.message||"Academic readiness evidence could not be persisted.");return{ownerId,agProgress,applications,evidenceRecord:record as EvidenceRecord};}
export default function AcademicReadinessPage(){const router=useRouter();const[data,setData]=useState<ReadinessLoadResult|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{let active=true;void readAcademicReadiness().then(result=>{if(!active)return;if(!result){router.replace("/login");return;}setData(result);}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Academic readiness could not be loaded.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[router]);const snapshot=useMemo<AcademicReadinessSnapshot|null>(()=>data?buildAcademicReadinessSnapshot({agProgress:data.agProgress,applications:data.applications}):null,[data]);if(loading)return <PlaybookPage><div style={{maxWidth:1180,margin:"40px auto",padding:28,color:"#64748B"}}>Loading academic readiness…</div></PlaybookPage>;if(error||!snapshot)return <PlaybookPage><div role="alert" style={{maxWidth:1180,margin:"40px auto",padding:28,color:"#991B1B"}}>{error||"Academic readiness unavailable."}</div></PlaybookPage>;return <PlaybookPage><PlaybookHero eyebrow="Scholar Academic Readiness" title="Know what is ready, what is missing, and what to do next" subtitle="A–G progress, applications, transcript evidence, FAFSA readiness, and human-approved guidance stay connected to the Scholar Record."/><PlaybookMetrics><PlaybookMetric label="Readiness" value={`${snapshot.readinessScore}%`}/><PlaybookMetric label="A–G met" value={`${snapshot.agSubjectsMet}/7`}/><PlaybookMetric label="Active applications" value={String(snapshot.activeApplications)}/></PlaybookMetrics><section style={{maxWidth:1180,margin:"0 auto 24px"}}><PlaybookCard eyebrow="Recommended next move" title={snapshot.primaryRecommendation.title}><p style={{color:"#64748B",lineHeight:1.65}}>{snapshot.primaryRecommendation.body}</p><PlaybookButton onClick={()=>router.push(snapshot.primaryRecommendation.href)}>{snapshot.primaryRecommendation.action}</PlaybookButton></PlaybookCard></section><PlaybookGrid min={300}>{readinessAreas.map(area=><PlaybookCard key={area.href} eyebrow={area.label} title={area.title}><p style={{color:"#64748B",lineHeight:1.65}}>{area.body}</p><PlaybookButton onClick={()=>router.push(area.href)}>{area.action}</PlaybookButton></PlaybookCard>)}</PlaybookGrid></PlaybookPage>;}
