import type { OpportunityNode } from "../types";

export const OPPORTUNITY_ONTOLOGY: OpportunityNode[] = [
  {
    id: "stem-scholarship-foundation",
    title: "STEM Scholarship Readiness",
    type: "scholarship",
    description: "Scholarship pathway for students showing math, science, research, or engineering signals.",
    tags: ["stem", "scholarship", "college"],
    skills: ["quantitative reasoning", "scientific thinking", "research", "problem solving"],
    majors: ["Engineering", "Computer Science", "Biology", "Public Health", "Kinesiology"],
    careers: ["Engineer", "Doctor", "Researcher", "Data Analyst", "Physical Therapist"],
    requirements: ["STEM coursework evidence", "Strong academic record", "Reflection or project evidence"],
    nextSteps: ["Add STEM evidence", "Request teacher verification", "Add project or lab reflection"],
    readinessWeight: 90,
  },
  {
    id: "writing-leadership-scholarship",
    title: "Writing and Leadership Scholarship Readiness",
    type: "scholarship",
    description: "Scholarship pathway for students with writing, communication, journalism, or civic leadership signals.",
    tags: ["writing", "leadership", "scholarship"],
    skills: ["writing", "communication", "critical thinking", "leadership"],
    majors: ["English", "Education", "Journalism", "Law"],
    careers: ["Teacher", "Attorney", "Writer", "Journalist"],
    requirements: ["Writing sample", "Leadership evidence", "Reflection"],
    nextSteps: ["Attach writing sample", "Add leadership activity", "Request advisor verification"],
    readinessWeight: 80,
  },
  {
    id: "healthcare-career-pathway",
    title: "Healthcare Career Pathway",
    type: "career",
    description: "Career pathway for students with biology, health, kinesiology, public health, or service signals.",
    tags: ["healthcare", "career", "service"],
    skills: ["scientific thinking", "research", "observation", "analysis"],
    majors: ["Biology", "Public Health", "Medicine", "Kinesiology"],
    careers: ["Doctor", "Researcher", "Physical Therapist", "Public Health Worker"],
    requirements: ["Science coursework", "Service evidence", "Career reflection"],
    nextSteps: ["Add healthcare-related activity", "Find mentor", "Explore summer health programs"],
    readinessWeight: 85,
  },
  {
    id: "mentor-match-academic-growth",
    title: "Academic Growth Mentor Match",
    type: "mentor",
    description: "Mentor pathway based on academic interests, career signals, and next-step readiness.",
    tags: ["mentor", "academic", "career"],
    skills: ["communication", "critical thinking", "problem solving"],
    majors: ["Engineering", "Education", "Business", "Public Health", "Journalism"],
    careers: ["Engineer", "Teacher", "Financial Advisor", "Doctor", "Attorney"],
    requirements: ["Academic interests", "Career direction", "Reflection"],
    nextSteps: ["Write a mentor request", "Add goals", "Add career interests"],
    readinessWeight: 70,
  },
  {
    id: "nil-personal-brand-foundation",
    title: "NIL Personal Brand Foundation",
    type: "nil",
    description: "NIL readiness pathway for scholar-athletes building brand, evidence, financial literacy, and compliance awareness.",
    tags: ["nil", "athletics", "brand", "financial literacy"],
    skills: ["communication", "leadership", "financial literacy", "media"],
    majors: ["Business", "Marketing", "Communications", "Kinesiology"],
    careers: ["Athlete", "Entrepreneur", "Coach", "Sports Marketer"],
    requirements: ["Athletic record", "Media kit", "Financial literacy evidence", "Brand reflection"],
    nextSteps: ["Add athletic evidence", "Create bio", "Add highlight reel", "Complete financial literacy module"],
    readinessWeight: 75,
  }
];
