import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { LearningReport } from "../learning";
import type { MasteryReport } from "../mastery";
import type { CredentialInput } from "./contracts";
import { CredentialError } from "./errors";
import { createPortableCredentials, mayShare } from "./portability";
import { createCredentialReport } from "./reporting";
import { transitionCredential } from "./state-machine";

function input(): CredentialInput {
  const content = "canonical credential authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-809", title: "Credential Governance", version: "1.0.0", location: "docs/PPS/PPS-809.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-809", location: "docs/PPS/PPS-809.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const learning: LearningReport = { reportId: "LEARN-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learner: { learnerId: "LEARNER-1", learningGoals: [], interests: [], currentCompetencyIds: ["COMP-1"], growthAreas: [], evidenceHistory: ["EVID-1"], mentorRelationships: [], learningPreferences: [], agencyStatement: "The learner and authorized humans retain learning decision authority.", potentialAssessment: null }, learnerEvidence: [], competencies: [], skills: [], milestones: [], reflections: [], masteryIndicators: [], pathways: [], recommendations: [], evidenceBundle: ["EVID-1", "learning:evidence"], limitations: [] };
  const mastery: MasteryReport = { reportId: "MAST-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learnerId: "LEARNER-1", competencies: [{ competencyId: "COMP-1", competencyName: "Evidence Communication" }], demonstrations: [], achievements: [], portfolio: { portfolioId: "PORT-1", artifactEvidenceIds: ["EVID-1"], competencyNames: ["Evidence Communication"], achievementDescriptions: [], reflectionEvidenceIds: [], validationIds: ["VAL-1"], owner: "LEARNER-1", learnerId: "LEARNER-1", createdAt: "2026-07-25T00:00:00.000Z", permissions: ["PORTFOLIO", "CREDENTIAL"], provenance: { learnerId: "LEARNER-1", evidenceIds: ["EVID-1"], sourceReferences: ["portfolio:1"], owners: ["LEARNER-1"], validationIds: ["VAL-1"], runtimeContextDigest: runtimeContext.contextDigest }, manufacturedAchievements: false }, credentials: [], masteryProgression: [], limitations: [], confidence: "MEDIUM", evidenceBundle: ["EVID-1", "mastery:evidence"] };
  return { runtimeContext, recipientIdentity: "LEARNER-1", masteryReports: [mastery], learningReports: [learning], issuers: [{ issuerId: "ISSUER-1", organizationIdentity: "Example Learning Organization", classification: "EDUCATIONAL", authorityScope: ["Evidence Communication"], verificationStatus: "VERIFIED", approvalRecords: ["ISSUER-APPROVAL-1"], ownership: "Example Learning Organization", limitations: ["Authorized only for named competency."] }], issuanceApprovals: [{ approvalId: "ISSUE-APPROVAL-1", issuerId: "ISSUER-1", recipientId: "LEARNER-1", approvedCredentialTypes: ["CREDENTIAL", "BADGE", "CERTIFICATE"], approvedCompetencies: ["Evidence Communication"], approverIdentity: "ISSUER-REVIEWER-1", approvedAt: "2026-07-25T00:00:00.000Z", evidenceReferences: ["EVID-1"], status: "APPROVED" }], credentialDrafts: [{ credentialType: "CREDENTIAL", title: "Evidence Communication Recognition", description: "Recognition of a validated demonstration.", recipientIdentity: "LEARNER-1", issuerId: "ISSUER-1", requirements: ["Validated evidence"], evidenceReferences: ["EVID-1"], competencyMappings: ["Evidence Communication"], issueDate: "2026-07-25T00:00:00.000Z", expirationDate: "2027-07-25T00:00:00.000Z", approvalId: "ISSUE-APPROVAL-1" }], badgeDrafts: [{ title: "Evidence Communicator", criteria: ["Submit verified demonstration"], evidenceRequirements: ["EVID-1"], issuerId: "ISSUER-1", recipientIdentity: "LEARNER-1", competenciesRepresented: ["Evidence Communication"], evidenceReferences: ["EVID-1"], metadata: { level: "demonstrated" }, approvalId: "ISSUE-APPROVAL-1" }], certificateDrafts: [{ issuingOrganization: "Example Learning Organization", issuerId: "ISSUER-1", recipientIdentity: "LEARNER-1", achievementRecognized: "Evidence Communication demonstration", requirementsSatisfied: ["Validated evidence"], evidenceReferences: ["EVID-1"], signatureApprovals: ["ISSUER-REVIEWER-1"], issueDate: "2026-07-25T00:00:00.000Z", approvalId: "ISSUE-APPROVAL-1" }], portabilityPermissions: [], historyEvents: [], generatedAt: "2026-07-26T00:00:00.000Z", authorizedRecipientIds: ["LEARNER-1"], fabricatedCredentialRequested: false, rankingRequested: false, opportunityGuaranteeRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(CredentialError); return (error as CredentialError).failures.map(({ code }) => code); } }

describe("PBOS governed credential intelligence", () => {
  it("creates deterministic credentials from valid issuer authority", () => { const first = createCredentialReport(input()); expect(createCredentialReport(input())).toEqual(first); expect(first.reportId).toMatch(/^PBOS-CRED-REPORT-[A-F0-9]{16}$/); expect(first.credentialInventory[0].statement).toContain("not a measure of human worth"); });
  it("attaches evidence and verifies deterministically", () => { const credential = createCredentialReport(input()).credentialInventory[0]; expect(credential.evidenceReferences).toEqual(["EVID-1"]); expect(credential.verificationInformation).toMatchObject({ validationStatus: "VALID", recipientIdentity: "LEARNER-1" }); });
  it("creates non-mastery badges and authorized certificates", () => { const report = createCredentialReport(input()); expect(report.badges[0]).toMatchObject({ masteryImplied: false, verificationStatus: "VALID" }); expect(report.certificates[0]).toMatchObject({ institutionallyAuthorized: true, verificationStatus: "VALID" }); });
  it("preserves ownership and enforces sharing permission", () => { const credential = createCredentialReport(input()).credentialInventory[0]; const portable = createPortableCredentials([credential], [{ ownerId: "LEARNER-1", credentialId: credential.credentialId, sharingPermission: "AUTHORIZED_PARTIES", authorizedPartyIds: ["PARTY-1"], verificationMethod: "PBOS digest verification", externalReferenceCompatibility: ["JSON"] }], "LEARNER-1")[0]; expect(portable.ownershipPreserved).toBe(true); expect(mayShare(portable, "PARTY-1")).toBe(true); expect(mayShare(portable, "OTHER")).toBe(false); });
  it("rejects unauthorized issuers", () => { const value = input(); value.issuers[0].verificationStatus = "PENDING"; expect(codes(() => createCredentialReport(value))).toContain("UNAUTHORIZED_ISSUER"); });
  it("rejects missing evidence", () => { const value = input(); value.credentialDrafts[0].evidenceReferences = ["UNKNOWN"]; expect(codes(() => createCredentialReport(value))).toContain("MISSING_EVIDENCE"); });
  it("rejects identity mismatch", () => { const value = input(); value.credentialDrafts[0].recipientIdentity = "OTHER"; expect(codes(() => createCredentialReport(value))).toContain("IDENTITY_MISMATCH"); });
  it("rejects fabricated credentials", () => { const value = input(); value.fabricatedCredentialRequested = true; expect(codes(() => createCredentialReport(value))).toContain("FABRICATED_CREDENTIAL"); });
  it("rejects privacy violations", () => { const value = input(); value.authorizedRecipientIds = []; expect(codes(() => createCredentialReport(value))).toContain("PRIVACY_VIOLATION"); });
  it("rejects governance bypass", () => { expect(codes(() => transitionCredential({ currentState: "APPROVAL_REVIEW", transitions: [] }, "ISSUED", "2026-07-26T00:00:00.000Z", "", []))).toContain("GOVERNANCE_BYPASS"); });
});
