import { digestValue, type PBOSRuntimeContext } from "../context";
import type { CredentialInput, IssuanceApproval, IssuerAuthority } from "./contracts";
import { CredentialError, credentialFailure } from "./errors";

function validContext(context: PBOSRuntimeContext): boolean { const body = { ...context }; delete (body as Partial<PBOSRuntimeContext>).contextDigest; return context.documentInventory.length > 0 && context.contextDigest === digestValue(body); }
export function validateCredentialInput(input: CredentialInput): { context: PBOSRuntimeContext; issuers: Map<string, IssuerAuthority>; approvals: Map<string, IssuanceApproval>; availableEvidence: Set<string> } {
  if (!input.runtimeContext || !validContext(input.runtimeContext)) throw new CredentialError([credentialFailure("INVALID_CONTEXT", "A valid constitutional Runtime Context is required.")]);
  if (!input.authorizedRecipientIds.includes(input.recipientIdentity)) throw new CredentialError([credentialFailure("PRIVACY_VIOLATION", "Credential processing requires recipient authorization.")]);
  if (input.fabricatedCredentialRequested) throw new CredentialError([credentialFailure("FABRICATED_CREDENTIAL", "Credential records cannot be created without verified evidence and issuer authority.")]);
  if (input.rankingRequested) throw new CredentialError([credentialFailure("RANKING_PROHIBITED", "Credentials cannot rank human value.")]);
  if (input.opportunityGuaranteeRequested) throw new CredentialError([credentialFailure("OPPORTUNITY_GUARANTEE", "Credentials cannot guarantee employment, admission, access, or success.")]);
  if (Number.isNaN(Date.parse(input.generatedAt))) throw new CredentialError([credentialFailure("MISSING_EVIDENCE", "A valid report timestamp is required.")]);
  const digest = input.runtimeContext.contextDigest;
  if (!input.masteryReports.length || !input.learningReports.length || input.masteryReports.some((report) => report.runtimeContextDigest !== digest || report.learnerId !== input.recipientIdentity || !report.evidenceBundle.length) || input.learningReports.some((report) => report.runtimeContextDigest !== digest || report.learner.learnerId !== input.recipientIdentity || !report.evidenceBundle.length)) throw new CredentialError([credentialFailure("IDENTITY_MISMATCH", "Mastery and learning evidence must match the recipient and active context.")]);
  const issuers = new Map(input.issuers.map((issuer) => [issuer.issuerId, issuer]));
  if (!input.issuers.length || input.issuers.some((issuer) => issuer.verificationStatus !== "VERIFIED" || !issuer.authorityScope.length || !issuer.approvalRecords.length || !issuer.ownership || !issuer.limitations.length)) throw new CredentialError([credentialFailure("UNAUTHORIZED_ISSUER", "Issuers require verified identity, scope, approvals, ownership, and limitations.")]);
  const approvals = new Map(input.issuanceApprovals.map((approval) => [approval.approvalId, approval]));
  const allDrafts = [...input.credentialDrafts, ...input.badgeDrafts.map((draft) => ({ ...draft, credentialType: "BADGE" as const, competencyMappings: draft.competenciesRepresented })), ...input.certificateDrafts.map((draft) => ({ ...draft, credentialType: "CERTIFICATE" as const, competencyMappings: [] }))];
  const unauthorized = allDrafts.some((draft) => { const issuer = issuers.get(draft.issuerId); const approval = approvals.get(draft.approvalId); return !issuer || !approval || approval.status !== "APPROVED" || approval.issuerId !== draft.issuerId || approval.recipientId !== input.recipientIdentity || !approval.approvedCredentialTypes.includes(draft.credentialType) || draft.competencyMappings.some((item) => !approval.approvedCompetencies.includes(item) || !issuer.authorityScope.includes(item)); });
  if (unauthorized) throw new CredentialError([credentialFailure("UNAUTHORIZED_ISSUER", "Every credential requires matching verified issuer scope and human issuance approval.")]);
  if (input.certificateDrafts.some((draft) => issuers.get(draft.issuerId)?.organizationIdentity !== draft.issuingOrganization || !draft.signatureApprovals.length)) throw new CredentialError([credentialFailure("UNAUTHORIZED_ISSUER", "Certificates require matching issuing organization identity and signature approval.")]);
  if (allDrafts.some((draft) => draft.recipientIdentity !== input.recipientIdentity)) throw new CredentialError([credentialFailure("IDENTITY_MISMATCH", "Credential recipient identity must match the authorized evidence subject.")]);
  const availableEvidence = new Set([...input.masteryReports.flatMap((report) => report.evidenceBundle), ...input.learningReports.flatMap((report) => report.evidenceBundle)]);
  if (allDrafts.some((draft) => !draft.evidenceReferences.length || draft.evidenceReferences.some((reference) => !availableEvidence.has(reference))) || input.issuanceApprovals.some((approval) => !approval.evidenceReferences.length || approval.evidenceReferences.some((reference) => !availableEvidence.has(reference)) || Number.isNaN(Date.parse(approval.approvedAt)))) throw new CredentialError([credentialFailure("MISSING_EVIDENCE", "Credentials and approvals may only cite evidence from validated mastery and learning reports.")]);
  if (input.credentialDrafts.some((draft) => Number.isNaN(Date.parse(draft.issueDate)) || (draft.expirationDate !== null && (Number.isNaN(Date.parse(draft.expirationDate)) || Date.parse(draft.expirationDate) <= Date.parse(draft.issueDate))))) throw new CredentialError([credentialFailure("MISSING_EVIDENCE", "Credential issue and expiration dates must form a valid interval.")]);
  return { context: input.runtimeContext, issuers, approvals, availableEvidence };
}
