import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { CredentialReport } from "../credential";
import type { IdentityReport } from "../identity";
import type { LearningReport } from "../learning";
import type { MasteryReport } from "../mastery";
import type { OpportunityReport } from "../opportunity";
import type { PortfolioInput } from "./contracts";
import { PortfolioError } from "./errors";
import { createPortfolioReport } from "./reporting";
import { transitionPortfolio } from "./state-machine";

function input(): PortfolioInput {
  const content = "canonical portfolio authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-812", title: "Portfolio Governance", version: "1.0.0", location: "docs/PPS/PPS-812.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-812", location: "docs/PPS/PPS-812.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const evidenceBundle = ["artifact:evidence", "consent:evidence", "identity:evidence"];
  const identityReports: IdentityReport[] = [{ reportId: "IDENT-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, identityState: { identityId: "IDENTITY-1", personReference: "PERSON-1", attributes: [], preferredInformation: {}, ownershipStatus: "PERSON_OWNED_PBOS_STEWARD", permissions: ["VIEW", "SHARE", "EDIT", "EXPORT"], privacySettings: {}, provenance: { sourceReferences: [], createdAt: "2026-07-25T00:00:00.000Z", modificationHistory: [], authorizedActor: "PERSON-1", evidenceReferences: evidenceBundle, consentBasisIds: ["CONSENT-1"], runtimeContextDigest: runtimeContext.contextDigest } }, ownershipInformation: { ownershipId: "OWNER-1", ownerIdentity: "PERSON-1", stewardIdentity: "PBOS", ownedDataCategories: ["portfolio"], accessRights: ["VIEW", "SHARE", "EDIT", "EXPORT"], sharingPermissions: ["SHARE", "EXPORT"], transferRules: [], consentHistoryIds: ["CONSENT-1"], personOwnsRecord: true }, permissions: [], consentHistory: [{ consentId: "CONSENT-1", personReference: "PERSON-1", purpose: "college-application", dataCategories: ["portfolio", "artifacts"], authorizedRecipient: "UNIVERSITY-1", expiresAt: "2027-07-26T00:00:00.000Z", status: "GRANTED", evidenceReferences: ["consent:evidence"], grantedAt: "2026-07-25T00:00:00.000Z" }], verificationStatus: [], privacyControls: {}, portableIdentities: [], accessDecision: { authorized: true, requester: "PERSON-1", purpose: "portfolio-management", permissions: ["VIEW"], dataCategories: ["portfolio"], consentId: "CONSENT-1", limitations: [] }, provenanceEvidence: evidenceBundle, limitations: [] }];
  const learningReports: LearningReport[] = [{ reportId: "LEARN-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learner: { learnerId: "PERSON-1", learningGoals: [], interests: [], currentCompetencyIds: [], growthAreas: [], evidenceHistory: [], mentorRelationships: [], learningPreferences: [], agencyStatement: "The learner and authorized humans retain learning decision authority.", potentialAssessment: null }, learnerEvidence: [], competencies: [], skills: [], milestones: [], reflections: [], masteryIndicators: [], pathways: [], recommendations: [], evidenceBundle, limitations: [] }];
  const masteryReports: MasteryReport[] = [{ reportId: "MAST-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learnerId: "PERSON-1", competencies: [{ competencyId: "COMP-1", competencyName: "Evidence Communication" }], demonstrations: [], achievements: [], portfolio: { portfolioId: "OLD-PORT-1", artifactEvidenceIds: [], competencyNames: [], achievementDescriptions: [], reflectionEvidenceIds: [], validationIds: [], owner: "PERSON-1", learnerId: "PERSON-1", createdAt: "2026-07-25T00:00:00.000Z", permissions: [], provenance: { learnerId: "PERSON-1", evidenceIds: [], sourceReferences: [], owners: [], validationIds: [], runtimeContextDigest: runtimeContext.contextDigest }, manufacturedAchievements: false }, credentials: [], masteryProgression: [], limitations: [], confidence: "MEDIUM", evidenceBundle }];
  const credentialReports: CredentialReport[] = [{ reportId: "CRED-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, recipientIdentity: "PERSON-1", credentialInventory: [], badges: [], certificates: [], issuerInformation: [], verificationState: [], portableCredentials: [], credentialHistory: [], evidenceBundle, competencyMappings: ["Evidence Communication"], limitations: [], provenance: { runtimeContextDigest: runtimeContext.contextDigest, masteryReportIds: ["MAST-1"], learningReportIds: ["LEARN-1"], evidenceReferences: evidenceBundle, issuerApprovalIds: [] } }];
  const opportunityReports: OpportunityReport[] = [{ reportId: "OPP-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, opportunityInventory: [], organizations: [], eligibilityAssessments: [], alignmentRecords: [], recommendations: [], applicationPathways: [], deadlines: [], evidenceBundle, limitations: [], provenance: { runtimeContextDigest: runtimeContext.contextDigest, credentialReportIds: ["CRED-1"], masteryReportIds: ["MAST-1"], learningReportIds: ["LEARN-1"], discoveryReportIds: [], sourceReferences: [], evidenceReferences: evidenceBundle } }];
  return { runtimeContext, identityReports, learningReports, masteryReports, credentialReports, opportunityReports, ownerIdentity: "PERSON-1", purpose: "Present an authentic learning journey", requestedVisibility: "SHARED", requestedPermissions: ["VIEW", "SHARE", "EDIT", "EXPORT", "CURATE", "PRESENT", "ARCHIVE"], evidenceDrafts: [{ sourceReference: "artifact:evidence", classification: "VERIFIED", verificationAuthority: "REVIEWER-1", observedAt: "2026-07-25T00:00:00.000Z", supportingRecordIds: ["MAST-1"], limitations: ["Evidence reflects one project context"] }], artifactDrafts: [{ ownerIdentity: "PERSON-1", artifactType: "PROJECT", title: "Community Research Project", description: "Person-authored project description", createdAt: "2026-07-24T00:00:00.000Z", evidenceSourceReferences: ["artifact:evidence"], relatedCompetencies: ["Evidence Communication"], relatedCredentialIds: [], permissions: ["VIEW", "SHARE", "CURATE"], sourceReference: "person-project" }], reflectionDrafts: [{ authorIdentity: "PERSON-1", experienceReference: "Community Research Project", reflectionText: "I learned to explain evidence with more care.", lessonsLearned: ["Context matters"], growthAreas: ["Source comparison"], futureGoals: ["Continue research"], reflectedAt: "2026-07-25T00:00:00.000Z" }], narrativeDrafts: [{ authorIdentity: "PERSON-1", storySections: ["I began with a community question."], experienceReferences: ["Community Research Project"], achievementArtifactTitles: ["Community Research Project"], goals: ["Continue research"], values: ["Community"], evidenceSourceReferences: ["artifact:evidence"], personalVoiceConfirmed: true }], showcaseDrafts: [{ ownerIdentity: "PERSON-1", selectedArtifactTitles: ["Community Research Project"], audience: "UNIVERSITY-1", permissions: ["VIEW", "PRESENT"], purpose: "college-application", sharingStatus: "AUTHORIZED" }], sharingDrafts: [{ ownerIdentity: "PERSON-1", recipient: "UNIVERSITY-1", purpose: "college-application", dataCategories: ["portfolio", "artifacts"], expiresAt: "2027-07-26T00:00:00.000Z", consentEvidenceReferences: ["consent:evidence"], ownerApproved: true, visibility: "SHARED" }], generatedAt: "2026-07-26T00:00:00.000Z", authorizedOwnerIdentities: ["PERSON-1"], fabricatedArtifactRequested: false, falseAchievementRequested: false, alteredEvidenceRequested: false, ownershipBypassRequested: false, portfolioRankingRequested: false, protectedCharacteristicInferenceRequested: false, guaranteedOutcomeRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(PortfolioError); return (error as PortfolioError).failures.map(({ code }) => code); } }

describe("PBOS governed portfolio intelligence", () => {
  it("preserves portfolio ownership in deterministic reports", () => { const first = createPortfolioReport(input()); expect(createPortfolioReport(input())).toEqual(first); expect(first.reportId).toMatch(/^PBOS-PORT-REPORT-[A-F0-9]{16}$/); expect(first.portfolioState).toMatchObject({ ownerIdentity: "PERSON-1", stewardIdentity: "PBOS", personOwnsPortfolio: true }); });
  it("preserves artifact provenance", () => { expect(createPortfolioReport(input()).artifacts[0].provenance).toMatchObject({ ownerIdentity: "PERSON-1", sourceReferences: ["person-project"], evidenceReferences: ["artifact:evidence"] }); });
  it("keeps evidence traceable and distinct from claims", () => { expect(createPortfolioReport(input()).evidence[0]).toMatchObject({ sourceReference: "artifact:evidence", classification: "VERIFIED", verificationAuthority: "REVIEWER-1", isClaim: false }); });
  it("requires consent for deterministic sharing grants", () => { expect(createPortfolioReport(input()).sharingGrants[0]).toMatchObject({ recipient: "UNIVERSITY-1", consentId: "CONSENT-1", ownerApproved: true, active: true }); });
  it("preserves personal narrative and reflection ownership", () => { const report = createPortfolioReport(input()); expect(report.narrativeElements[0]).toMatchObject({ authorIdentity: "PERSON-1", voiceStandard: "AUTHENTIC_PERSONAL_VOICE", personAuthored: true, fabricatedContent: false }); expect(report.reflections[0]).toMatchObject({ ownerIdentity: "PERSON-1", authoredByPerson: true }); });
  it("creates explainable, non-guaranteed competency connections", () => { expect(createPortfolioReport(input()).competencyConnections[0]).toMatchObject({ explanation: "This artifact demonstrates evidence related to this competency: Evidence Communication.", guaranteedOutcome: false }); });
  it("rejects fabricated artifacts", () => { const value = input(); value.fabricatedArtifactRequested = true; expect(codes(() => createPortfolioReport(value))).toContain("FABRICATED_ARTIFACT"); });
  it("rejects missing evidence", () => { const value = input(); value.evidenceDrafts = []; expect(codes(() => createPortfolioReport(value))).toContain("MISSING_EVIDENCE"); });
  it("rejects unauthorized sharing", () => { const value = input(); value.sharingDrafts[0].ownerApproved = false; expect(codes(() => createPortfolioReport(value))).toContain("UNAUTHORIZED_SHARING"); });
  it("rejects ownership bypass", () => { const value = input(); value.ownershipBypassRequested = true; expect(codes(() => createPortfolioReport(value))).toContain("OWNERSHIP_VIOLATION"); });
  it("rejects false achievements and governance bypass", () => { const falseAchievement = input(); falseAchievement.falseAchievementRequested = true; expect(codes(() => createPortfolioReport(falseAchievement))).toContain("FALSE_ACHIEVEMENT"); expect(codes(() => transitionPortfolio({ currentState: "REVIEWING", transitions: [] }, "SHARING_AUTHORIZED", "2026-07-26T00:00:00.000Z", "", []))).toContain("GOVERNANCE_BYPASS"); });
});
