import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { EcosystemReport } from "../ecosystem";
import type { IdentityReport } from "../identity";
import type { RoleReport } from "../role";
import type { CommunicationInput } from "./contracts";
import { createCommunicationReport } from "./engine";
import { CommunicationError } from "./errors";

function input(): CommunicationInput {
  const content = "canonical communication authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-817", title: "Communication Governance", version: "1.0.0", location: "docs/PPS/PPS-817.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-817", location: "docs/PPS/PPS-817.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const digest = runtimeContext.contextDigest; const evidence = ["relationship:mentor", "consent:mentor", "message:check-in", "notice:milestone"];
  const identityReports = ["SCHOLAR-1", "MENTOR-1"].map((personReference) => ({ reportId: `IDENT-${personReference}`, runtimeContextDigest: digest, identityState: { personReference }, verificationStatus: [{ status: "VERIFIED" }], provenanceEvidence: evidence })) as unknown as IdentityReport[];
  const roleReports = [{ runtimeContextDigest: digest, evidenceBundle: evidence, roleRecords: [{ roleId: "ROLE-SCHOLAR", personIdentity: "SCHOLAR-1", roleType: "SCHOLAR", permissions: ["VIEW", "CONNECT", "SHARE"], state: "ACTIVE" }, { roleId: "ROLE-MENTOR", personIdentity: "MENTOR-1", roleType: "MENTOR", permissions: ["VIEW", "CONNECT", "MENTOR"], state: "ACTIVE" }] }] as unknown as RoleReport[];
  const ecosystemReports = [{ runtimeContextDigest: digest, evidenceBundle: evidence, relationships: [{ relationshipId: "REL-1", sourceEntityId: "SCHOLAR-1", targetEntityId: "MENTOR-1", consentStatus: "CONSENTED", status: "ACTIVE", evidenceReferences: ["relationship:mentor"] }] }] as unknown as EcosystemReport[];
  const preference = (participantIdentity: string) => ({ participantIdentity, channels: ["IN_APP" as const], frequency: "IMMEDIATE" as const, categories: ["MENTORSHIP" as const, "MILESTONE" as const], consent: true as const });
  return { runtimeContext, identityReports, roleReports, ecosystemReports, participants: [{ personIdentity: "SCHOLAR-1", roleId: "ROLE-SCHOLAR", roleType: "SCHOLAR", organizationIdentity: null, permissions: ["VIEW", "CONNECT", "SHARE"], consentId: "CONSENT-1", preference: preference("SCHOLAR-1"), identityReportId: "IDENT-SCHOLAR-1", provenance: evidence }, { personIdentity: "MENTOR-1", roleId: "ROLE-MENTOR", roleType: "MENTOR", organizationIdentity: null, permissions: ["VIEW", "CONNECT"], consentId: "CONSENT-1", preference: preference("MENTOR-1"), identityReportId: "IDENT-MENTOR-1", provenance: evidence }], consents: [{ consentId: "CONSENT-1", personIdentity: "SCHOLAR-1", recipientIdentity: "MENTOR-1", purpose: "mentor-check-in", dataScope: ["MENTORSHIP"], expiresAt: "2027-01-01T00:00:00.000Z", status: "GRANTED", evidenceReferences: ["message:check-in"], visibility: "PRIVATE" }], messageDrafts: [{ senderIdentity: "MENTOR-1", recipientIdentity: "SCHOLAR-1", purpose: "mentor-check-in", category: "MENTORSHIP", contentReference: "CONTENT-1", relationshipId: "REL-1", consentId: "CONSENT-1", channel: "IN_APP", timestamp: "2026-07-26T00:00:00.000Z", evidenceReferences: ["message:check-in"], external: false, sensitive: false }], notificationDrafts: [{ recipientIdentity: "SCHOLAR-1", sourceReference: "MILESTONE-1", reason: "Milestone update", kind: "INFORMATION", category: "MILESTONE", permission: "VIEW", timestamp: "2026-07-26T00:00:00.000Z", messageContentReference: null, evidenceReferences: ["notice:milestone"] }], reminderDrafts: [{ recipientIdentity: "SCHOLAR-1", category: "ACADEMIC", subjectReference: "DEADLINE-1", dueAt: "2026-08-01T00:00:00.000Z", reason: "Review upcoming deadline", evidenceReferences: ["notice:milestone"], supportive: true, coercive: false }], workflowDrafts: [{ workflowType: "MENTOR_CHECK_IN", triggerReference: "MILESTONE-1", recipientIdentity: "SCHOLAR-1", senderIdentity: "MENTOR-1", purpose: "mentor-check-in", consentId: "CONSENT-1", relationshipId: "REL-1", evidenceReferences: ["message:check-in"] }], generatedAt: "2026-07-26T00:00:00.000Z", humanApprovals: [], inferredRelationshipRequested: false, impersonationRequested: false, privacyBypassRequested: false, spamRequested: false, manipulationRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(CommunicationError); return (error as CommunicationError).failures.map(({ code }) => code); } }
describe("PBOS governed Communication Engine", () => {
  it("creates deterministic authorized messages", () => { const first = createCommunicationReport(input()); expect(createCommunicationReport(input())).toEqual(first); expect(first.messages[0]).toMatchObject({ state: "AUTHORIZED", relationshipId: "REL-1", consentId: "CONSENT-1" }); });
  it("enforces consent and private visibility", () => { expect(createCommunicationReport(input()).consentRecords[0]).toMatchObject({ status: "GRANTED", visibility: "PRIVATE" }); });
  it("honors channel and category preferences", () => { expect(createCommunicationReport(input()).participants[0].preference).toMatchObject({ channels: ["IN_APP"], consent: true }); });
  it("validates support relationships", () => { expect(createCommunicationReport(input()).relationshipIds).toEqual(["REL-1"]); });
  it("preserves notification provenance and non-coercive reminders", () => { const report = createCommunicationReport(input()); expect(report.notifications[0].provenance).toContain("notice:milestone"); expect(report.reminders[0]).toMatchObject({ supportive: true, coercive: false }); });
  it("rejects unauthorized communication", () => { const value = input(); value.participants[0].permissions = ["VIEW"]; expect(codes(() => createCommunicationReport(value))).toContain("UNAUTHORIZED_COMMUNICATION"); });
  it("rejects missing consent", () => { const value = input(); value.consents[0].status = "REVOKED"; expect(codes(() => createCommunicationReport(value))).toContain("MISSING_CONSENT"); });
  it("rejects impersonation", () => { const value = input(); value.impersonationRequested = true; expect(codes(() => createCommunicationReport(value))).toContain("IMPERSONATION"); });
  it("rejects privacy violations", () => { const value = input(); value.privacyBypassRequested = true; expect(codes(() => createCommunicationReport(value))).toContain("PRIVACY_VIOLATION"); });
  it("rejects invalid relationships", () => { const value = input(); value.ecosystemReports[0].relationships[0].consentStatus = "REVOKED"; expect(codes(() => createCommunicationReport(value))).toContain("INVALID_RELATIONSHIP"); });
});
