import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { CredentialReport } from "../credential";
import type { EcosystemReport } from "../ecosystem";
import type { LearningReport } from "../learning";
import type { MasteryReport } from "../mastery";
import type { IdentityInput } from "./contracts";
import { IdentityError } from "./errors";
import { createIdentityReport } from "./reporting";
import { transitionIdentity } from "./state-machine";

function input(): IdentityInput {
  const content = "canonical identity authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-811", title: "Identity Governance", version: "1.0.0", location: "docs/PPS/PPS-811.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-811", location: "docs/PPS/PPS-811.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const evidenceBundle = ["identity:evidence", "consent:evidence", "verification:evidence", "edit:evidence"];
  const ecosystemReports: EcosystemReport[] = [{ reportId: "ECO-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, ecosystemEntities: [], relationships: [], mentorships: [], supportNetworks: [], resources: [], organizations: [], alignments: [], evidenceBundle, permissions: [], limitations: [], provenance: { runtimeContextDigest: runtimeContext.contextDigest, sourceReferences: [], evidenceReferences: evidenceBundle, opportunityReportIds: [], knowledgeReportIds: [], credentialReportIds: [] } }];
  const credentialReports: CredentialReport[] = [{ reportId: "CRED-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, recipientIdentity: "PERSON-1", credentialInventory: [], badges: [], certificates: [], issuerInformation: [], verificationState: [], portableCredentials: [], credentialHistory: [], evidenceBundle, competencyMappings: [], limitations: [], provenance: { runtimeContextDigest: runtimeContext.contextDigest, masteryReportIds: [], learningReportIds: [], evidenceReferences: evidenceBundle, issuerApprovalIds: [] } }];
  const learningReports: LearningReport[] = [{ reportId: "LEARN-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learner: { learnerId: "PERSON-1", learningGoals: [], interests: [], currentCompetencyIds: [], growthAreas: [], evidenceHistory: [], mentorRelationships: [], learningPreferences: [], agencyStatement: "The learner and authorized humans retain learning decision authority.", potentialAssessment: null }, learnerEvidence: [], competencies: [], skills: [], milestones: [], reflections: [], masteryIndicators: [], pathways: [], recommendations: [], evidenceBundle, limitations: [] }];
  const masteryReports: MasteryReport[] = [{ reportId: "MAST-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learnerId: "PERSON-1", competencies: [], demonstrations: [], achievements: [], portfolio: { portfolioId: "PORT-1", artifactEvidenceIds: [], competencyNames: [], achievementDescriptions: [], reflectionEvidenceIds: [], validationIds: [], owner: "PERSON-1", learnerId: "PERSON-1", createdAt: "2026-07-25T00:00:00.000Z", permissions: [], provenance: { learnerId: "PERSON-1", evidenceIds: [], sourceReferences: [], owners: [], validationIds: [], runtimeContextDigest: runtimeContext.contextDigest }, manufacturedAchievements: false }, credentials: [], masteryProgression: [], limitations: [], confidence: "MEDIUM", evidenceBundle }];
  return { runtimeContext, ecosystemReports, credentialReports, learningReports, masteryReports, identityData: { personReference: "PERSON-1", preferredInformation: { displayName: "Scholar One" }, goals: ["Control my identity"], preferences: ["Private by default"], attributes: [{ name: "displayName", value: "Scholar One", informationClass: "USER_PROVIDED_INFORMATION", sourceReference: "profile", evidenceReferences: ["identity:evidence"], verified: false, privacy: "PRIVATE" }], privacySettings: { displayName: "PRIVATE" }, requestedPermissions: ["VIEW", "SHARE", "EDIT", "EXPORT", "REVOKE"], evidenceReferences: ["identity:evidence"] }, consentDrafts: [{ personReference: "PERSON-1", purpose: "portfolio-export", dataCategories: ["displayName"], authorizedRecipient: "PERSON-1", expiresAt: "2027-07-26T00:00:00.000Z", status: "GRANTED", evidenceReferences: ["consent:evidence"], grantedAt: "2026-07-25T00:00:00.000Z" }], verificationDrafts: [{ personReference: "PERSON-1", verificationMethod: "human-reviewed evidence", verificationAuthority: "REVIEWER-1", verifiedAt: "2026-07-25T00:00:00.000Z", evidenceReferences: ["verification:evidence"], status: "VERIFIED" }], portabilityRequests: [{ requestId: "PORT-REQ-1", personReference: "PERSON-1", requestedCategories: ["displayName"], receivingSystem: "person-controlled archive", permissions: ["EXPORT"], consentEvidenceReferences: ["consent:evidence"] }], modificationHistory: [{ modificationId: "MOD-1", category: "displayName", changedAt: "2026-07-25T00:00:00.000Z", authorizedActor: "PERSON-1", evidenceReferences: ["edit:evidence"], permission: "EDIT" }], authorizedPersonReferences: ["PERSON-1"], generatedAt: "2026-07-26T00:00:00.000Z", accessRequester: "PERSON-1", accessPurpose: "portfolio-export", requestedDataCategories: ["displayName"], requestedPermissions: ["VIEW", "EXPORT"], falseIdentityClaimRequested: false, ownershipBypassRequested: false, identityRankingRequested: false, protectedCharacteristicInferenceRequested: false, dataSaleRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(IdentityError); return (error as IdentityError).failures.map(({ code }) => code); } }

describe("PBOS governed identity intelligence", () => {
  it("creates deterministic identity reports that preserve ownership", () => { const first = createIdentityReport(input()); expect(createIdentityReport(input())).toEqual(first); expect(first.reportId).toMatch(/^PBOS-ID-REPORT-[A-F0-9]{16}$/); expect(first.ownershipInformation).toMatchObject({ ownerIdentity: "PERSON-1", stewardIdentity: "PBOS", personOwnsRecord: true }); });
  it("uses active consent to authorize purpose-limited access", () => { expect(createIdentityReport(input()).accessDecision).toMatchObject({ authorized: true, requester: "PERSON-1", purpose: "portfolio-export", dataCategories: ["displayName"] }); });
  it("enforces explicit permissions and private defaults", () => { expect(createIdentityReport(input()).permissions[0]).toMatchObject({ defaultVisibility: "PRIVATE", permissions: ["EXPORT", "VIEW"] }); });
  it("preserves verification provenance", () => { expect(createIdentityReport(input()).verificationStatus[0]).toMatchObject({ verificationAuthority: "REVIEWER-1", evidenceReferences: ["verification:evidence"], status: "VERIFIED" }); });
  it("creates person-controlled portable identity data", () => { expect(createIdentityReport(input()).portableIdentities[0]).toMatchObject({ receivingSystemInformation: "person-controlled archive", controlledByPerson: true }); });
  it("rejects unauthorized access", () => { const value = input(); value.authorizedPersonReferences = []; expect(codes(() => createIdentityReport(value))).toContain("UNAUTHORIZED_ACCESS"); });
  it("rejects missing consent", () => { const value = input(); value.consentDrafts[0].status = "REVOKED"; expect(codes(() => createIdentityReport(value))).toContain("MISSING_CONSENT"); });
  it("rejects false identity claims", () => { const value = input(); value.falseIdentityClaimRequested = true; expect(codes(() => createIdentityReport(value))).toContain("FALSE_IDENTITY"); });
  it("rejects privacy violations", () => { const value = input(); value.identityData.attributes[0].privacy = "SENSITIVE"; value.accessRequester = "EXTERNAL-1"; value.consentDrafts[0].authorizedRecipient = "EXTERNAL-1"; expect(codes(() => createIdentityReport(value))).toContain("PRIVACY_VIOLATION"); });
  it("rejects ownership bypass and prohibited inference", () => { const bypass = input(); bypass.ownershipBypassRequested = true; expect(codes(() => createIdentityReport(bypass))).toContain("OWNERSHIP_BYPASS"); const inference = input(); inference.protectedCharacteristicInferenceRequested = true; expect(codes(() => createIdentityReport(inference))).toContain("INFERENCE_PROHIBITED"); });
  it("rejects skipped lifecycle states and governance bypass", () => { expect(codes(() => transitionIdentity({ currentState: "CREATED", transitions: [] }, "ACTIVE", "2026-07-26T00:00:00.000Z", "owner", ["approval"]))).toContain("INVALID_TRANSITION"); expect(codes(() => transitionIdentity({ currentState: "VERIFYING", transitions: [] }, "VERIFIED", "2026-07-26T00:00:00.000Z", "", []))).toContain("GOVERNANCE_BYPASS"); });
});
