import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { GovernedKnowledgeGraph, KnowledgeReport } from "../knowledge";
import type { SimulationInput } from "./contracts";
import { SimulationError } from "./errors";
import { createSimulationReport } from "./reporting";
import { transitionSimulation } from "./state-machine";

function input(): SimulationInput {
  const content = "canonical simulation authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-809", title: "Simulation Governance", version: "1.0.0", location: "docs/PPS/PPS-809.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-809", location: "docs/PPS/PPS-809.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const evidence = ["knowledge:evidence:1", "knowledge:evidence:2", "knowledge:evidence:3"];
  const knowledgeReport: KnowledgeReport = { reportId: "PBOS-KNOW-1234567890ABCDEF", runtimeContextDigest: runtimeContext.contextDigest, generatedAt: "2026-07-26T00:00:00.000Z", knowledgeSources: ["HIST-1"], entities: [], relationships: [], precedents: [], lessons: [], evidenceBundle: evidence, confidenceClassification: "HIGH" };
  const knowledgeGraph: GovernedKnowledgeGraph = { graphId: "PBOS-KNOW-GRAPH-1234567890ABCDEF", contextDigest: runtimeContext.contextDigest, generatedAt: "2026-07-26T00:00:00.000Z", nodes: [], relationships: [], evidenceReferences: evidence, historicalStates: [] };
  return { runtimeContext, simulationQuestion: "What possible evidence-review pathways could be considered?", knowledgeReports: [knowledgeReport], knowledgeGraphs: [knowledgeGraph], strategyReports: [], discoveryReports: [], metaReports: [], scenarioDrafts: [{ description: "Explore alternative evidence-review capacity states.", supportingEvidence: evidence, assumptions: [{ statement: "Review capacity may remain available.", sourceEvidence: ["knowledge:evidence:1"], confidence: "MEDIUM", validationStatus: "SUPPORTED", limitations: ["Future capacity is not established."] }, { statement: "Demand may change.", sourceEvidence: ["knowledge:evidence:2"], confidence: "LOW", validationStatus: "UNCERTAIN", limitations: ["Demand data is incomplete."] }], constraints: ["Human approval is required."], variables: ["Review capacity", "Evidence demand"], pathways: [{ name: "Maintain current review path", startingConditions: ["Current process remains active."], actionsConsidered: ["Continue current process."], dependencies: ["Existing reviewers"], requiredResources: ["Current capacity"], possibleOutcomes: ["Queue may remain stable."], risks: ["Queue may grow."], unknownFactors: ["Future demand"], supportingEvidence: ["knowledge:evidence:1"] }, { name: "Evaluate additional review capacity", startingConditions: ["Leadership authorizes evaluation."], actionsConsidered: ["Assess capacity options."], dependencies: ["Governance review"], requiredResources: ["Analysis time"], possibleOutcomes: ["Additional options may be identified."], risks: ["Opportunity cost"], unknownFactors: ["Available resources"], supportingEvidence: ["knowledge:evidence:2"] }], outcomes: [{ pathwayName: "Maintain current review path", evidenceBasis: ["knowledge:evidence:1"], possibleResult: "The queue may remain stable.", assumptionStatements: ["Review capacity may remain available."], classification: "POSSIBLE", limitations: ["Demand is unknown."] }, { pathwayName: "Evaluate additional review capacity", evidenceBasis: ["knowledge:evidence:3"], possibleResult: "Capacity options may be documented.", assumptionStatements: ["Demand may change."], classification: "UNCERTAIN", limitations: ["Resource availability is unknown."] }], risks: ["Resource diversion"], limitations: ["The model does not predict demand or capacity."] }], generatedAt: "2026-07-26T01:00:00.000Z", unsupportedSimulationRequested: false, guaranteedOutcomeRequested: false, unauthorizedDecisionRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(SimulationError); return (error as SimulationError).failures.map(({ code }) => code); } }

describe("PBOS governed future scenario simulation", () => {
  it("creates deterministic evidence-backed scenarios and reports", () => { const first = createSimulationReport(input()); expect(createSimulationReport(input())).toEqual(first); expect(first.reportId).toMatch(/^PBOS-SIM-[A-F0-9]{16}$/); expect(first.scenariosAnalyzed[0].disclaimer).toContain("not a prediction"); });
  it("preserves assumptions as non-factual uncertainty", () => { const assumptions = createSimulationReport(input()).assumptions; expect(assumptions.every(({ artifactType }) => artifactType === "ASSUMPTION_NOT_FACT")).toBe(true); expect(assumptions.map(({ validationStatus }) => validationStatus)).toEqual(["SUPPORTED", "UNCERTAIN"]); });
  it("preserves multiple pathways without selecting one", () => { const report = createSimulationReport(input()); expect(report.pathways).toHaveLength(2); expect(report.comparisons[0].selectedPathway).toBeNull(); });
  it("preserves comparison method, evidence, and limitations", () => { const comparison = createSimulationReport(input()).comparisons[0]; expect(comparison.comparisonMethod).toContain("no weighted winner"); expect(comparison.evidenceUsed).toHaveLength(2); expect(comparison.limitations).toHaveLength(2); });
  it("classifies outcomes without certainty", () => { const outcomes = createSimulationReport(input()).outcomes; expect(outcomes.map(({ classification }) => classification).sort()).toEqual(["POSSIBLE", "UNCERTAIN"]); expect(outcomes.every(({ uncertaintyStatement }) => uncertaintyStatement.includes("not a prediction"))).toBe(true); });
  it("rejects missing context", () => { const value = input(); value.runtimeContext = null; expect(codes(() => createSimulationReport(value))).toContain("MISSING_CONTEXT"); });
  it("rejects unsupported assumptions", () => { const value = input(); value.scenarioDrafts[0].assumptions[0].limitations = []; expect(codes(() => createSimulationReport(value))).toContain("INVALID_ASSUMPTION"); });
  it("rejects guaranteed outcomes", () => { const value = input(); value.guaranteedOutcomeRequested = true; expect(codes(() => createSimulationReport(value))).toContain("GUARANTEED_OUTCOME"); });
  it("rejects invalid evidence", () => { const value = input(); value.scenarioDrafts[0].supportingEvidence = ["invented:evidence"]; expect(codes(() => createSimulationReport(value))).toContain("MISSING_EVIDENCE"); });
  it("rejects unauthorized decisions", () => { const value = input(); value.unauthorizedDecisionRequested = true; expect(codes(() => createSimulationReport(value))).toContain("UNAUTHORIZED_DECISION"); });
  it("rejects governance bypass", () => { const pending = { status: "pending" as const, approvalIdentifier: null, evidenceReferences: [] }; expect(codes(() => transitionSimulation({ currentState: "GOVERNANCE_REVIEW", transitions: [] }, "ARCHIVED", "2026-07-26T00:00:00.000Z", pending))).toContain("GOVERNANCE_BYPASS"); });
});
