"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { PlaybookCard, PlaybookGrid, PlaybookHero, PlaybookMetric, PlaybookMetrics, PlaybookPage, PlaybookPill } from "@/components/ui";

type College={id:string;unit_id:string|null;name:string;city:string|null;state:string|null;school_url:string|null;ownership:string|null;highest_degree:string|null};
type SavedCollege={id:string;college_name:string;college_type:string|null;status:string|null;deadline:string|null;notes:string|null;created_at:string};
const STATUSES=["considering","researching","applying","applied","accepted","waitlisted","denied","enrolled"] as const;

export default function CollegeSearchPage(){
 const router=useRouter();
 const[catalog,setCatalog]=useState<College[]>([]);const[saved,setSaved]=useState<SavedCollege[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState("");const[state,setState]=useState("all");const[manualName,setManualName]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState("");
 const load=useCallback(async()=>{setLoading(true);setMessage("");const auth=await supabase.auth.getUser();if(!auth.data.user){router.replace("/login");return;}const[catalogResult,savedResult]=await Promise.all([supabase.from("colleges").select("id,unit_id,name,city,state,school_url,ownership,highest_degree").order("name").limit(5000),supabase.from("college_list").select("id,college_name,college_type,status,deadline,notes,created_at").eq("user_id",auth.data.user.id).order("created_at",{ascending:false})]);if(catalogResult.error||savedResult.error)setMessage(catalogResult.error?.message||savedResult.error?.message||"College Search could not be loaded.");else{setCatalog((catalogResult.data||[]) as College[]);setSaved((savedResult.data||[]) as SavedCollege[]);}setLoading(false);},[router]);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)void load();});return()=>{active=false;};},[load]);
 const states=useMemo(()=>Array.from(new Set(catalog.map(item=>item.state).filter((value):value is string=>Boolean(value)))).sort(),[catalog]);
 const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return catalog.filter(item=>(state==="all"||item.state===state)&&(!needle||`${item.name} ${item.city||""} ${item.state||""} ${item.ownership||""} ${item.highest_degree||""}`.toLowerCase().includes(needle)));},[catalog,query,state]);
 const savedNames=useMemo(()=>new Set(saved.map(item=>item.college_name.toLowerCase())),[saved]);
 async function saveCollege(name:string,type:string|null="catalog"){setBusy(name);setMessage("");const auth=await supabase.auth.getUser();if(!auth.data.user){setBusy("");return;}const result=await supabase.from("college_list").upsert({user_id:auth.data.user.id,college_name:name.trim(),college_type:type||"catalog",status:"considering"},{onConflict:"user_id,college_name"});if(result.error)setMessage(result.error.message);else{setMessage(`${name} added to your college list.`);await load();}setBusy("");}
 async function addManual(event:FormEvent){event.preventDefault();const name=manualName.trim();if(!name)return;await saveCollege(name,"manual");setManualName("");}
 async function updateStatus(item:SavedCollege,status:string){setBusy(item.id);const auth=await supabase.auth.getUser();if(!auth.data.user){setBusy("");return;}const result=await supabase.from("college_list").update({status}).eq("id",item.id).eq("user_id",auth.data.user.id);if(result.error)setMessage(result.error.message);else await load();setBusy("");}
 async function remove(item:SavedCollege){setBusy(item.id);const auth=await supabase.auth.getUser();if(!auth.data.user){setBusy("");return;}const result=await supabase.from("college_list").delete().eq("id",item.id).eq("user_id",auth.data.user.id);if(result.error)setMessage(result.error.message);else await load();setBusy("");}
 return <PlaybookPage>
  <PlaybookHero eyebrow="Academic · College Planning" title="College Search" subtitle="Search Playbook's governed college reference catalog, build your personal college list, and carry the schools you are considering into the rest of your academic planning journey." />
  <PlaybookMetrics><PlaybookMetric label="Catalog schools" value={loading?"…":String(catalog.length)}/><PlaybookMetric label="Saved schools" value={loading?"…":String(saved.length)}/><PlaybookMetric label="Search authority" value="Canonical catalog"/></PlaybookMetrics>
  <section style={notice}><PlaybookPill>Truthful catalog</PlaybookPill><h2 style={noticeTitle}>No invented schools or admissions facts.</h2><p style={noticeCopy}>The directory only displays records actually present in Playbook&apos;s college catalog. If the catalog has not been populated yet, you can still save a school manually to your private list while the governed reference dataset is being loaded.</p></section>
  <section style={section}><div style={toolbar}><label style={field}>Search colleges<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="School, city, state…" style={input}/></label><label style={field}>State<select value={state} onChange={e=>setState(e.target.value)} style={input}><option value="all">All states</option>{states.map(value=><option key={value}>{value}</option>)}</select></label></div><p role="status" aria-live="polite" style={status}>{message||(!loading?`${visible.length} catalog school${visible.length===1?"":"s"} found.`:"Loading college catalog…")}</p>{!loading&&catalog.length===0?<PlaybookCard eyebrow="College catalog" title="The governed catalog is not populated yet"><p style={copy}>Your personal list is still functional. Add schools below without creating fake directory records.</p></PlaybookCard>:<PlaybookGrid min={330}>{visible.slice(0,100).map(college=><PlaybookCard key={college.id} eyebrow={[college.city,college.state].filter(Boolean).join(", ")||"College"} title={college.name}><div style={pills}>{college.ownership?<PlaybookPill>{college.ownership}</PlaybookPill>:null}{college.highest_degree?<PlaybookPill>{college.highest_degree}</PlaybookPill>:null}</div><div style={actions}><button type="button" disabled={busy===college.name||savedNames.has(college.name.toLowerCase())} onClick={()=>void saveCollege(college.name,"catalog")} style={primary}>{savedNames.has(college.name.toLowerCase())?"Saved ✓":"Save school"}</button>{college.school_url?<Link href={college.school_url} target="_blank" rel="noreferrer" style={secondary}>Official site ↗</Link>:null}</div></PlaybookCard>)}</PlaybookGrid>}</section>
  <section style={section}><PlaybookCard eyebrow="Manual fallback" title="Add a school that is not in the catalog yet"><form onSubmit={addManual} style={manual}><label style={field}>College name<input value={manualName} onChange={e=>setManualName(e.target.value)} maxLength={200} placeholder="College or university name" style={input}/></label><button type="submit" disabled={!manualName.trim()||Boolean(busy)} style={primary}>Add to my list</button></form></PlaybookCard></section>
  <section style={section}><div style={sectionHeader}><div><p style={eyebrow}>My college list</p><h2 style={heading}>Schools I&apos;m considering</h2></div><Link href="/application-workspaces" style={secondary}>Application Workspaces →</Link></div>{saved.length===0?<PlaybookCard eyebrow="College list" title="No schools saved yet"><p style={copy}>Search the catalog or add a school manually to start your list.</p></PlaybookCard>:<PlaybookGrid min={320}>{saved.map(item=><PlaybookCard key={item.id} eyebrow={item.college_type||"saved school"} title={item.college_name}><label style={field}>Planning status<select value={item.status||"considering"} disabled={busy===item.id} onChange={e=>void updateStatus(item,e.target.value)} style={input}>{STATUSES.map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label>{item.deadline?<PlaybookPill>Deadline {item.deadline}</PlaybookPill>:null}<div style={actions}><Link href={`/application-workspaces?${new URLSearchParams({opportunityName:item.college_name,opportunityType:"college"}).toString()}`} style={primary}>Open Application Workspace →</Link><button type="button" disabled={busy===item.id} onClick={()=>void remove(item)} style={danger}>Remove</button></div></PlaybookCard>)}</PlaybookGrid>}</section>
 </PlaybookPage>;
}
const section:React.CSSProperties={maxWidth:1180,margin:"0 auto 30px"};const notice:React.CSSProperties={maxWidth:1180,margin:"0 auto 24px",padding:"clamp(20px,4vw,32px)",borderRadius:"8px 28px 8px 28px",background:"#081D34",color:"#fff"};const noticeTitle:React.CSSProperties={fontSize:"clamp(24px,4vw,34px)",margin:"10px 0 8px"};const noticeCopy:React.CSSProperties={color:"#C9D8E8",lineHeight:1.65};const toolbar:React.CSSProperties={display:"grid",gridTemplateColumns:"minmax(0,2fr) minmax(180px,1fr)",gap:12};const field:React.CSSProperties={display:"grid",gap:6,fontWeight:800,color:"#334155"};const input:React.CSSProperties={border:"1px solid #CBD5E1",borderRadius:12,padding:"11px 12px",font:"inherit",background:"#fff"};const status:React.CSSProperties={color:"#475569",minHeight:24};const pills:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap"};const actions:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",marginTop:14};const base:React.CSSProperties={borderRadius:999,padding:"10px 14px",fontWeight:900,textDecoration:"none",cursor:"pointer"};const primary:React.CSSProperties={...base,border:0,background:"#F97316",color:"#fff"};const secondary:React.CSSProperties={...base,display:"inline-flex",alignItems:"center",border:"1px solid #CBD5E1",background:"#fff",color:"#0F172A"};const danger:React.CSSProperties={...base,border:"1px solid #FCA5A5",background:"#fff",color:"#B91C1C"};const manual:React.CSSProperties={display:"flex",gap:12,alignItems:"end",flexWrap:"wrap"};const copy:React.CSSProperties={color:"#475569",lineHeight:1.65};const sectionHeader:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,flexWrap:"wrap",marginBottom:14};const eyebrow:React.CSSProperties={margin:0,color:"#EA580C",textTransform:"uppercase",letterSpacing:".1em",fontSize:11,fontWeight:900};const heading:React.CSSProperties={margin:"5px 0 0",fontSize:"clamp(26px,4vw,38px)",color:"#0F172A"};
