export enum PlaybookEvent {

  PLAYBOOK_RECORD_UPDATED = "PLAYBOOK_RECORD_UPDATED",

  SCHOLAR_RECORD_UPDATED = "SCHOLAR_RECORD_UPDATED",

  PROFILE_UPDATED = "PROFILE_UPDATED",

  TRANSCRIPT_UPDATED = "TRANSCRIPT_UPDATED",

  ACHIEVEMENT_CREATED = "ACHIEVEMENT_CREATED",

  EVIDENCE_CREATED = "EVIDENCE_CREATED",

  TRUST_UPDATED = "TRUST_UPDATED",

  OPPORTUNITY_UNLOCKED = "OPPORTUNITY_UNLOCKED",

}
