-- Durable curriculum and Store inventory. Store inventory uses the existing
-- governed store_products/store_redemptions authority.
insert into public.learning_courses (slug,title,description,pillar,image_url,status,xp_per_module,coins_per_module,certificate_name,sort_order) values
('college-application-playbook','College Application Playbook','Build a balanced college list, prepare financial-aid milestones, write with evidence, and track applications.','College','https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80','published',50,20,'College Application Playbook Certificate',10),
('captains-mindset','Captain''s Mindset','Build accountable, trustworthy, resilient leadership habits on and off the court.','Leadership','https://images.unsplash.com/photo-1546519638405-a4c8b5bd3c5e?w=1200&q=80','published',50,20,'Captain''s Mindset Certificate',20),
('money-in-the-game','Money in the Game','Budgeting, saving, credit, taxes, investing, and NIL money fundamentals.','Finance','https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80','published',50,20,'Money in the Game Certificate',30),
('mind-of-an-athlete','Mind of an Athlete','Build resilience, process pressure, and strengthen identity beyond sport.','SEL','https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&q=80','published',50,20,'Mind of an Athlete Certificate',40),
('social-emotional-foundations','Social-Emotional Foundations','Build emotional intelligence, self-awareness, communication, and resilience.','SEL',null,'coming_soon',50,20,'Social-Emotional Foundations Certificate',50),
('nil-readiness-for-athletes','NIL Readiness for Athletes','Learn personal branding, opportunity evaluation, contracts, taxes, and compliance.','NIL',null,'coming_soon',50,20,'NIL Readiness for Athletes Certificate',60),
('civic-engagement-for-young-leaders','Civic Engagement for Young Leaders','Develop advocacy skills and learn how to create durable community change.','Civic',null,'coming_soon',50,20,'Civic Engagement for Young Leaders Certificate',70)
on conflict (slug) do update set title=excluded.title,description=excluded.description,pillar=excluded.pillar,image_url=excluded.image_url,status=excluded.status,xp_per_module=excluded.xp_per_module,coins_per_module=excluded.coins_per_module,certificate_name=excluded.certificate_name,sort_order=excluded.sort_order,updated_at=now();

insert into public.learning_modules (course_slug,module_key,position,title,duration_minutes,module_type,summary,content,completion_mode) values
('college-application-playbook','college-list',1,'Build Your College List',15,'planning','Build a balanced list around fit.','Compare academic fit, affordability, location, campus culture, intended major, and opportunity. Record reach, match, and likely schools with a reason for each choice.','reflection'),
('college-application-playbook','accounts',2,'Create Your Application Accounts',20,'action','Create and secure application accounts.','Create required portals, use a password manager, record deadlines, and use an email address you check consistently.','acknowledge'),
('college-application-playbook','financial-aid',3,'FAFSA and Financial Aid',18,'milestone','Prepare financial-aid evidence.','Identify household contributors, gather required identity and tax information, and record official deadlines you still need to verify.','reflection'),
('college-application-playbook','college-savings',4,'College Savings and CalKIDS',14,'milestone','Connect savings resources.','Record college-savings resources that are already connected and those that still need to be claimed or verified.','reflection'),
('college-application-playbook','personal-statement',5,'Personal Statement Prep',22,'writing','Write from specific evidence.','Choose a concrete experience that reveals how you think, grow, contribute, or persist. Outline the moment, meaning, and change.','reflection'),
('college-application-playbook','submit-track',6,'Submit and Track Applications',20,'project','Build your application operating system.','Track deadline, documents, recommendations, financial-aid steps, submission confirmation, and final outcome for each application.','reflection'),
('captains-mindset','captain',1,'What Makes a Captain?',12,'lesson','Separate title from leadership behavior.','A captain models standards before enforcing them. Define three behaviors teammates should be able to expect from you.','reflection'),
('captains-mindset','accountability',2,'Accountability Starts With You',15,'lesson','Lead with self-accountability.','Set personal standards for preparation, communication, repair after mistakes, and follow-through.','reflection'),
('captains-mindset','trust',3,'Building Trust With Your Team',18,'activity','Build trust intentionally.','Trust grows from honesty, reliability, competence, repair, and respect. Choose one trust behavior to practice this week.','reflection'),
('captains-mindset','adversity',4,'Leading Through Adversity',14,'reflection','Lead when the plan breaks.','Describe how you will respond when losing, benched, injured, or in conflict. Focus on controllable leadership behavior.','reflection'),
('captains-mindset','communication',5,'Communication On and Off the Court',16,'lesson','Match communication to the moment.','Practice clear, specific, respectful communication. Separate correction from humiliation and urgency from panic.','reflection'),
('captains-mindset','leadership-playbook',6,'Your Leadership Playbook',20,'project','Turn lessons into a personal plan.','Write your standards, communication habits, accountability routine, and contribution to team culture.','reflection'),
('money-in-the-game','money-101',1,'Money 101 for Athletes',10,'lesson','Understand cash flow before lifestyle.','Know what comes in, required expenses, tax obligations, and savings priorities before increasing spending.','acknowledge'),
('money-in-the-game','budget',2,'Build Your First Budget',18,'activity','Create a budget from real numbers.','List income, required expenses, flexible spending, saving, giving, and investing so money has a plan before it is spent.','reflection'),
('money-in-the-game','saving-investing',3,'Saving vs Investing',15,'lesson','Match money to time horizon.','Keep near-term needs liquid and separate them from long-term investing goals. Define one of each.','reflection'),
('money-in-the-game','nil-basics',4,'NIL Basics for Under 18',20,'lesson','Understand obligations before signing.','NIL income can create tax, contract, eligibility, guardian, school, and disclosure obligations. Treat offers as contracts, not free money.','acknowledge'),
('money-in-the-game','taxes',5,'Taxes — Athletes Pay Them Too',14,'lesson','Plan for taxes before spending gross income.','Keep income records, reserve money for taxes, and involve a qualified tax professional when the situation requires it.','acknowledge'),
('money-in-the-game','credit',6,'Credit Scores Explained',12,'lesson','Build credit without confusing it with income.','Payment history, utilization, account age, mix, and inquiries can affect credit. Borrow only for a valid purpose you can repay.','acknowledge'),
('money-in-the-game','traps',7,'Avoiding Financial Traps',16,'activity','Recognize expensive mistakes.','Identify predatory lending, lifestyle inflation, fees, pressure purchases, bad contracts, and secrecy around money.','reflection'),
('money-in-the-game','financial-plan',8,'Your Financial Game Plan',22,'project','Build a personal money operating plan.','Document your budget, emergency-fund target, tax routine, credit rules, savings goals, and who you consult before major decisions.','reflection'),
('mind-of-an-athlete','emotions',1,'Understanding Your Emotions',12,'reflection','Name emotion before choosing action.','Notice the emotion, identify the trigger, and choose the response that serves your goals rather than reacting automatically.','reflection'),
('mind-of-an-athlete','pressure',2,'Pressure and Performance',15,'activity','Create a repeatable pressure reset.','Build a short routine using breathing, cue words, body position, and attention to the next controllable action.','reflection'),
('mind-of-an-athlete','resilience',3,'Building Resilience',14,'lesson','Recover with evidence instead of slogans.','Resilience includes support, honest evaluation, rest, learning, and returning with a revised plan.','reflection'),
('mind-of-an-athlete','identity',4,'Identity Beyond the Sport',18,'reflection','Strengthen identity beyond performance.','List roles, values, relationships, interests, and contributions that matter even when sport is not going well.','reflection'),
('mind-of-an-athlete','mental-plan',5,'Your Mental Performance Plan',20,'project','Build a personal mental-performance toolkit.','Document your pressure reset, recovery routine, support people, warning signs, identity anchors, and next action when stuck.','reflection')
on conflict (course_slug,module_key) do update set position=excluded.position,title=excluded.title,duration_minutes=excluded.duration_minutes,module_type=excluded.module_type,summary=excluded.summary,content=excluded.content,completion_mode=excluded.completion_mode,updated_at=now();

insert into public.store_products (product_key,name,category,coin_price,inventory,requires_approval,active) values
('profile-spotlight','Profile Spotlight','digital',250,100,true,true),
('mentor-office-hour','Mentor Office Hour','experience',500,25,true,true),
('playbook-merch-credit','Playbook Merch Credit','merch',750,100,true,true)
on conflict (product_key) do update set name=excluded.name,category=excluded.category,coin_price=excluded.coin_price,inventory=excluded.inventory,requires_approval=excluded.requires_approval,active=excluded.active;
