-- Durable Playbook curriculum and initial reward inventory.
insert into public.learning_courses (slug,title,description,pillar,image_url,status,xp_per_module,coins_per_module,certificate_name,sort_order) values
('college-application-playbook','College Application Playbook','Build your college list, prepare applications, connect financial-aid milestones, and submit with confidence.','College','https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80','published',50,20,'College Application Playbook Certificate',10),
('captains-mindset','Captain''s Mindset','Lead by example on and off the court with practical captaincy frameworks.','Leadership','https://images.unsplash.com/photo-1546519638405-a4c8b5bd3c5e?w=1200&q=80','published',50,20,'Captain''s Mindset Certificate',20),
('money-in-the-game','Money in the Game','Budgeting, saving, credit, taxes, investing, and NIL fundamentals for young athletes.','Finance','https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80','published',50,20,'Money in the Game Certificate',30),
('mind-of-an-athlete','Mind of an Athlete','Build resilience, process pressure, and strengthen identity beyond sport.','SEL','https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&q=80','published',50,20,'Mind of an Athlete Certificate',40),
('social-emotional-foundations','Social-Emotional Foundations','Build emotional intelligence, self-awareness, communication, and resilience.','SEL',null,'coming_soon',50,20,'Social-Emotional Foundations Certificate',50),
('nil-readiness-for-athletes','NIL Readiness for Athletes','Learn personal branding, NIL opportunity evaluation, contracts, taxes, and compliance.','NIL',null,'coming_soon',50,20,'NIL Readiness for Athletes Certificate',60),
('civic-engagement-for-young-leaders','Civic Engagement for Young Leaders','Develop advocacy skills and learn how to create durable community change.','Civic',null,'coming_soon',50,20,'Civic Engagement for Young Leaders Certificate',70)
on conflict (slug) do update set title=excluded.title,description=excluded.description,pillar=excluded.pillar,image_url=excluded.image_url,status=excluded.status,xp_per_module=excluded.xp_per_module,coins_per_module=excluded.coins_per_module,certificate_name=excluded.certificate_name,sort_order=excluded.sort_order,updated_at=now();

insert into public.learning_modules (course_slug,module_key,position,title,duration_minutes,module_type,summary,content,completion_mode) values
('college-application-playbook','college-list',1,'Build Your College List',15,'planning','Identify reach, match, and likely schools that fit your goals.','Start with academic fit, affordability, location, campus culture, intended major, and opportunity. Build a balanced list rather than chasing rankings alone.','reflection'),
('college-application-playbook','accounts',2,'Create Your Application Accounts',20,'action','Create and secure the accounts used for applications.','Create your application portals, use a password manager, record deadlines, and make sure the email address attached to each account is one you check consistently.','acknowledge'),
('college-application-playbook','financial-aid',3,'FAFSA and Financial Aid',18,'milestone','Prepare the information needed for financial aid.','Identify the FAFSA contributors in your household, gather tax and identity documents, and record the date you expect to submit. Verify current deadlines directly with official sources.','reflection'),
('college-application-playbook','college-savings',4,'College Savings and CalKIDS',14,'milestone','Connect college-savings resources to your plan.','Review any existing college savings resources available to you and record what still needs to be claimed, connected, or verified.','reflection'),
('college-application-playbook','personal-statement',5,'Personal Statement Prep',22,'writing','Build a personal statement from evidence and reflection.','Choose a story that reveals how you think, grow, contribute, or persist. Draft around specific moments rather than generic claims.','reflection'),
('college-application-playbook','submit-track',6,'Submit and Track Applications',20,'project','Create your final application tracking routine.','For every application, track deadline, required documents, recommendation status, financial-aid steps, submission confirmation, and decision outcome.','reflection'),
('captains-mindset','captain',1,'What Makes a Captain?',12,'lesson','Separate title from leadership behavior.','A captain models standards before enforcing them. Identify the behaviors your teammates should be able to expect from you consistently.','reflection'),
('captains-mindset','accountability',2,'Accountability Starts With You',15,'lesson','Use self-accountability before team accountability.','Create a personal standard for preparation, communication, recovery after mistakes, and follow-through.','reflection'),
('captains-mindset','trust',3,'Building Trust With Your Team',18,'activity','Build trust intentionally.','Trust grows from repeated evidence: honesty, reliability, competence, repair after mistakes, and respect. Choose one trust behavior to practice this week.','reflection'),
('captains-mindset','adversity',4,'Leading Through Adversity',14,'reflection','Lead when the plan breaks.','Describe how you want to respond when your team is losing, when you are benched, or when conflict appears. Focus on controllable leadership behaviors.','reflection'),
('captains-mindset','communication',5,'Communication On and Off the Court',16,'lesson','Match communication to the moment.','Practice clear, specific, respectful communication. Separate correction from humiliation and urgency from panic.','reflection'),
('captains-mindset','leadership-playbook',6,'Your Leadership Playbook',20,'project','Turn the course into a personal leadership plan.','Write the standards, communication habits, accountability practices, and team contribution you will carry forward.','reflection'),
('money-in-the-game','money-101',1,'Money 101 for Athletes',10,'lesson','Understand cash flow before lifestyle.','Know what comes in, what must go out, what you owe in taxes, and what you are building for the future before increasing spending.','acknowledge'),
('money-in-the-game','budget',2,'Build Your First Budget',18,'activity','Create a budget based on your real numbers.','List monthly income, required expenses, flexible spending, saving, giving, and investing. Your budget should tell your money where to go before it disappears.','reflection'),
('money-in-the-game','saving-investing',3,'Saving vs Investing',15,'lesson','Use the right tool for the right time horizon.','Emergency and near-term money needs liquidity. Long-term wealth can take more market risk. Define one savings goal and one long-term investing goal.','reflection'),
('money-in-the-game','nil-basics',4,'NIL Basics for Under 18',20,'lesson','Understand NIL responsibilities before signing.','NIL income can create tax, contract, eligibility, guardian, school, and disclosure obligations. Never treat a social-media offer as risk-free money.','acknowledge'),
('money-in-the-game','taxes',5,'Taxes — Athletes Pay Them Too',14,'lesson','Prepare for taxes before spending gross income.','Set aside a percentage of self-employment or NIL income, keep records, and involve a qualified tax professional when needed.','acknowledge'),
('money-in-the-game','credit',6,'Credit Scores Explained',12,'lesson','Build credit without confusing credit with income.','Payment history, utilization, account age, credit mix, and new inquiries can affect credit. Never borrow simply to create a score.','acknowledge'),
('money-in-the-game','traps',7,'Avoiding Financial Traps',16,'activity','Recognize high-cost money mistakes.','Watch for predatory lending, lifestyle inflation, unnecessary fees, pressure purchases, bad contracts, and anyone demanding secrecy around money.','reflection'),
('money-in-the-game','financial-plan',8,'Your Financial Game Plan',22,'project','Turn the course into a personal financial plan.','Write your monthly budget, emergency-fund target, tax routine, credit rules, savings goals, investing questions, and people you will consult before major decisions.','reflection'),
('mind-of-an-athlete','emotions',1,'Understanding Your Emotions',12,'reflection','Name emotions without letting them drive every action.','Notice the emotion, name it, locate what triggered it, and choose the response that serves your goals rather than reacting automatically.','reflection'),
('mind-of-an-athlete','pressure',2,'Pressure and Performance',15,'activity','Create a repeatable pressure routine.','Build a short reset routine using breathing, cue words, body position, and attention to the next controllable action.','reflection'),
('mind-of-an-athlete','resilience',3,'Building Resilience',14,'lesson','Recover with evidence instead of slogans.','Resilience includes recovery, support, honest evaluation, rest, learning, and returning with a new plan.','reflection'),
('mind-of-an-athlete','identity',4,'Identity Beyond the Sport',18,'reflection','Strengthen identity beyond performance.','List the roles, values, relationships, interests, and contributions that still matter when your sport is not going well.','reflection'),
('mind-of-an-athlete','mental-plan',5,'Your Mental Performance Plan',20,'project','Build your personal mental-performance toolkit.','Document your pressure reset, recovery routine, support people, warning signs, identity anchors, and next action when you feel stuck.','reflection')
on conflict (course_slug,module_key) do update set position=excluded.position,title=excluded.title,duration_minutes=excluded.duration_minutes,module_type=excluded.module_type,summary=excluded.summary,content=excluded.content,completion_mode=excluded.completion_mode,updated_at=now();

insert into public.reward_store_items (id,name,description,coin_cost,inventory,fulfillment_type,status,sort_order) values
('profile-spotlight','Profile Spotlight','Feature your public Playbook profile in a rotating community spotlight after moderation review.',250,null,'digital','active',10),
('mentor-office-hour','Mentor Office Hour','Redeem for a request to schedule a 30-minute governed mentor office hour when capacity is available.',500,25,'experience','active',20),
('playbook-merch-credit','Playbook Merch Credit','A $10 merchandise credit fulfilled manually after eligibility and inventory confirmation.',750,100,'manual','active',30)
on conflict (id) do update set name=excluded.name,description=excluded.description,coin_cost=excluded.coin_cost,inventory=excluded.inventory,fulfillment_type=excluded.fulfillment_type,status=excluded.status,sort_order=excluded.sort_order,updated_at=now();
