-- Historical application-field parity baseline reconstructed read-only from the
-- hosted Playbook profiles table. No user data is copied. This exists so a fresh
-- local certification database exercises the same profile columns/defaults that
-- current application code expects before later hardening migrations run.

alter table public.profiles
  add column if not exists username text,
  add column if not exists full_name text,
  add column if not exists avatar_url text,
  add column if not exists cover_url text,
  add column if not exists bio text,
  add column if not exists location text,
  add column if not exists school text,
  add column if not exists sport text,
  add column if not exists grad_year integer,
  add column if not exists gpa numeric(3,2),
  add column if not exists instagram text,
  add column if not exists twitter text,
  add column if not exists linkedin text,
  add column if not exists onboarding_complete boolean default false,
  add column if not exists coin_balance integer default 0,
  add column if not exists is_active boolean default true,
  add column if not exists last_seen timestamptz,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now(),
  add column if not exists gender text,
  add column if not exists badges text[] default '{}'::text[],
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists date_of_birth date,
  add column if not exists xp integer default 0,
  add column if not exists level integer default 1,
  add column if not exists streak integer default 0,
  add column if not exists last_login date,
  add column if not exists "position" text,
  add column if not exists height text,
  add column if not exists weight text,
  add column if not exists dominant_hand text,
  add column if not exists jersey_number text,
  add column if not exists travel_team text,
  add column if not exists club_team text,
  add column if not exists coach_name text,
  add column if not exists coach_email text,
  add column if not exists sat_score text,
  add column if not exists act_score text,
  add column if not exists intended_major text,
  add column if not exists dream_school text,
  add column if not exists tiktok text,
  add column if not exists hudl text,
  add column if not exists youtube text,
  add column if not exists highlight_reel_url text,
  add column if not exists verification_status text default 'approved'::text,
  add column if not exists verification_requested_at timestamptz,
  add column if not exists verification_expires_at timestamptz,
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by text,
  add column if not exists edu_email text,
  add column if not exists is_admin boolean default false,
  add column if not exists onboarded boolean default false,
  add column if not exists pillars text[] default '{}'::text[],
  add column if not exists has_iep boolean default false,
  add column if not exists unhoused boolean default false,
  add column if not exists foster_youth boolean default false,
  add column if not exists migrant_student boolean default false,
  add column if not exists free_reduced_lunch boolean default false,
  add column if not exists first_generation boolean default false,
  add column if not exists household_income text,
  add column if not exists english_language_learner boolean default false,
  add column if not exists school_district text,
  add column if not exists zip_code text,
  add column if not exists team_level text,
  add column if not exists registration_type text,
  add column if not exists academic_gpa text,
  add column if not exists weighted_gpa text,
  add column if not exists unweighted_gpa text,
  add column if not exists current_math text,
  add column if not exists current_english text,
  add column if not exists current_science text,
  add column if not exists college_goal text,
  add column if not exists ideal_profession text,
  add column if not exists desired_salary_range text,
  add column if not exists recruiting_status text,
  add column if not exists desired_college_level text,
  add column if not exists athlete_email text,
  add column if not exists camps_attended text,
  add column if not exists nil_instagram text,
  add column if not exists nil_tiktok text,
  add column if not exists nil_twitter text,
  add column if not exists nil_follower_range text,
  add column if not exists nil_brand_interests text[],
  add column if not exists nil_worked_with_brands boolean default false,
  add column if not exists nil_deal_types text[],
  add column if not exists dream_school_name text,
  add column if not exists dream_school_id text,
  add column if not exists favorite_quote text,
  add column if not exists college_list_2 text,
  add column if not exists college_list_3 text,
  add column if not exists college_list_4 text,
  add column if not exists college_list_5 text,
  add column if not exists college_list_6 text,
  add column if not exists college_list_7 text,
  add column if not exists college_list_8 text,
  add column if not exists college_list_9 text,
  add column if not exists college_list_10 text,
  add column if not exists grade text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists profile_visibility text default 'public'::text,
  add column if not exists onboarding_data jsonb default '{}'::jsonb,
  add column if not exists onboarding_completed boolean default false,
  add column if not exists onboarding_completed_at timestamptz,
  add column if not exists public_profile_complete boolean default false,
  add column if not exists community_safety_agreed boolean default false,
  add column if not exists community_safety_agreed_at timestamptz,
  add column if not exists community_safety_policy_version text,
  add column if not exists profile_mode text,
  add column if not exists email text,
  add column if not exists requested_role text;
