import { describe, expect, it } from "vitest";
import { compileContext, sha256 } from "../context";
import type { CredentialReport } from "../credential";
import type { DiscoveryReport } from "../discovery";
import type { LearningReport } from "../learning";
import type { MasteryReport } from "../mastery";
import type { OpportunityInput } from "./contracts";
import { OpportunityError } from "./errors";
import { createOpportunityReport } from "./reporting";

function input(): OpportunityInput {
  const content = "canonical opportunity authority";
  const runtimeContext = compileContext({ sources: [{ identifier: "PPS-809", title: "Opportunity Governance", version: "1.0.0", location: "docs/PPS/PPS-809.md", status: "Canonical", owner: "PBOS", dependencies: [], content, digest: sha256(content), validationState: "verified" }], governanceDecisions: [], registry: { version: "1.0.0", validationState: "verified", documents: [{ identifier: "PPS-809", location: "docs/PPS/PPS-809.md", owner: "PBOS", version: "1.0.0" }] }, compilationTimestamp: "2026-07-26T00:00:00.000Z" });
  const learning: LearningReport = { reportId: "LEARN-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learner: { learnerId: "PERSON-1", learningGoals: ["Develop evidence communication"], interests: ["research"], currentCompetencyIds: ["COMP-1"], growthAreas: [], evidenceHistory: ["EVID-1"], mentorRelationships: [], learningPreferences: [], agencyStatement: "The learner and authorized humans retain learning decision authority.", potentialAssessment: null }, learnerEvidence: [], competencies: [], skills: [], milestones: [], reflections: [], masteryIndicators: [], pathways: [], recommendations: [], evidenceBundle: ["EVID-1", "learning:evidence"], limitations: [] };
  const mastery: MasteryReport = { reportId: "MAST-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, learnerId: "PERSON-1", competencies: [{ competencyId: "COMP-1", competencyName: "Evidence Communication" }], demonstrations: [], achievements: [], portfolio: { portfolioId: "PORT-1", artifactEvidenceIds: [], competencyNames: [], achievementDescriptions: [], reflectionEvidenceIds: [], validationIds: [], owner: "PERSON-1", learnerId: "PERSON-1", createdAt: "2026-07-25T00:00:00.000Z", permissions: [], provenance: { learnerId: "PERSON-1", evidenceIds: [], sourceReferences: [], owners: [], validationIds: [], runtimeContextDigest: runtimeContext.contextDigest }, manufacturedAchievements: false }, credentials: [], masteryProgression: [], limitations: [], confidence: "MEDIUM", evidenceBundle: ["EVID-1", "mastery:evidence"] };
  const credential: CredentialReport = { reportId: "CRED-1", generatedAt: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, recipientIdentity: "PERSON-1", credentialInventory: [], badges: [], certificates: [], issuerInformation: [], verificationState: [], portableCredentials: [], credentialHistory: [], evidenceBundle: ["CRED-1", "EVID-1"], competencyMappings: ["Evidence Communication"], limitations: [], provenance: { runtimeContextDigest: runtimeContext.contextDigest, masteryReportIds: ["MAST-1"], learningReportIds: ["LEARN-1"], evidenceReferences: ["EVID-1"], issuerApprovalIds: [] } };
  const discovery: DiscoveryReport = { reportId: "DISC-1", observationTimestamp: "2026-07-25T00:00:00.000Z", runtimeContextDigest: runtimeContext.contextDigest, sourceInventory: [], discoveredSignals: [], opportunities: [], risks: [], informationGaps: [], recommendations: [], confidenceClassifications: ["HIGH"], evidenceBundle: ["source:organization", "source:opportunity"] };
  return { runtimeContext, personContext: { personId: "PERSON-1", goals: ["Develop evidence communication"], interests: ["research"], competencies: ["Evidence Communication"], credentialIds: ["CRED-1"], location: "Remote", evidenceReferences: ["EVID-1", "CRED-1"] }, credentialReports: [credential], masteryReports: [mastery], learningReports: [learning], discoveryReports: [discovery], organizationDrafts: [{ name: "Verified Research Foundation", organizationType: "NONPROFIT", mission: "Support research learning.", authority: ["Offer scholarship"], verificationStatus: "VERIFIED", ownership: "Verified Research Foundation", contactInformation: ["https://example.invalid/opportunity"], sourceReference: "source:organization", evidenceReferences: ["source:organization"] }], opportunityDrafts: [{ title: "Research Evidence Scholarship", description: "Scholarship supporting research and Evidence Communication.", organizationName: "Verified Research Foundation", opportunityType: "SCHOLARSHIP", location: "Remote", requirements: ["Evidence Communication"], deadlines: [{ deadlineType: "APPLICATION", date: "2026-09-01T00:00:00.000Z", sourceReference: "source:opportunity", verificationStatus: "VERIFIED", reminderEligible: true }], applicationProcess: ["Review official criteria", "Human applicant chooses whether to apply"], eligibilityCriteria: [{ criterionId: "CRIT-1", category: "CREDENTIAL", description: "Provide verified evidence.", requiredEvidence: ["EVID-1"], sourceReference: "source:opportunity", verificationStatus: "VERIFIED" }], evidenceRequirements: ["CRED-1"], sourceReference: "source:opportunity", sourceEvidence: ["source:opportunity"], verificationStatus: "VERIFIED" }], eligibilityAssertions: [], generatedAt: "2026-07-26T00:00:00.000Z", authorizedPersonIds: ["PERSON-1"], fabricatedOpportunityRequested: false, guaranteedOutcomeRequested: false, unauthorizedDecisionRequested: false, rankingRequested: false };
}
function codes(action: () => unknown): string[] { try { action(); return []; } catch (error) { expect(error).toBeInstanceOf(OpportunityError); return (error as OpportunityError).failures.map(({ code }) => code); } }

describe("PBOS governed opportunity intelligence", () => {
  it("creates deterministic verified opportunities and reports", () => { const first = createOpportunityReport(input()); expect(createOpportunityReport(input())).toEqual(first); expect(first.reportId).toMatch(/^PBOS-OPP-REPORT-[A-F0-9]{16}$/); expect(first.opportunityInventory[0].verificationStatus).toBe("VERIFIED"); });
  it("preserves requirement and organization provenance", () => { const report = createOpportunityReport(input()); expect(report.organizations[0].provenance.evidenceReferences).toEqual(["source:organization"]); expect(report.opportunityInventory[0].eligibilityCriteria[0].sourceReference).toBe("source:opportunity"); });
  it("creates explainable alignment without guarantees", () => { const alignment = createOpportunityReport(input()).alignmentRecords[0]; expect(alignment.whyIdentified.some((item) => item.includes("Competency"))).toBe(true); expect(alignment.statement).toContain("not guaranteed success"); });
  it("keeps recommendations advisory", () => { expect(createOpportunityReport(input()).recommendations[0]).toMatchObject({ advisoryOnly: true, applicationSubmitted: false, acceptanceGuaranteed: false }); });
  it("preserves verified deadlines and human application control", () => { const report = createOpportunityReport(input()); expect(report.deadlines[0]).toMatchObject({ verificationStatus: "VERIFIED", reminderEligible: true }); expect(report.applicationPathways[0].humanCompletionRequired).toBe(true); });
  it("rejects fabricated opportunities", () => { const value = input(); value.opportunityDrafts[0].sourceEvidence = ["invented"]; expect(codes(() => createOpportunityReport(value))).toContain("FABRICATED_OPPORTUNITY"); });
  it("rejects unknown organizations", () => { const value = input(); value.opportunityDrafts[0].organizationName = "Unknown"; expect(codes(() => createOpportunityReport(value))).toContain("UNKNOWN_ORGANIZATION"); });
  it("rejects unsupported eligibility assertions", () => { const value = input(); value.personContext.evidenceReferences = []; value.eligibilityAssertions = [{ opportunitySourceReference: "source:opportunity", assertedStatus: "MEETS_REQUIREMENTS" }]; expect(codes(() => createOpportunityReport(value))).toContain("UNSUPPORTED_ELIGIBILITY"); });
  it("rejects guaranteed outcomes and unauthorized decisions", () => { const guaranteed = input(); guaranteed.guaranteedOutcomeRequested = true; expect(codes(() => createOpportunityReport(guaranteed))).toContain("GUARANTEED_OUTCOME"); const decided = input(); decided.unauthorizedDecisionRequested = true; expect(codes(() => createOpportunityReport(decided))).toContain("UNAUTHORIZED_DECISION"); });
  it("rejects privacy violations", () => { const value = input(); value.authorizedPersonIds = []; expect(codes(() => createOpportunityReport(value))).toContain("PRIVACY_VIOLATION"); });
});
