import { digestValue } from "../context";
import { alignOpportunity } from "./alignment";
import type { OpportunityInput, OpportunityProvenance, OpportunityReport } from "./contracts";
import { assessEligibility } from "./eligibility";
import { createOrganizations } from "./models";
import { createOpportunities } from "./opportunities";
import { createApplicationPathways } from "./pathways";
import { createRecommendations } from "./recommendations";
import { validateOpportunityInput } from "./validation";
export function createOpportunityReport(input: OpportunityInput): OpportunityReport { const context = validateOpportunityInput(input); const evidenceBundle = [...new Set([...input.personContext.evidenceReferences, ...input.credentialReports.flatMap((report) => report.evidenceBundle), ...input.masteryReports.flatMap((report) => report.evidenceBundle), ...input.learningReports.flatMap((report) => report.evidenceBundle), ...input.discoveryReports.flatMap((report) => report.evidenceBundle), ...input.organizationDrafts.flatMap((organization) => organization.evidenceReferences), ...input.opportunityDrafts.flatMap((opportunity) => opportunity.sourceEvidence)])].sort(); const provenance: OpportunityProvenance = { runtimeContextDigest: context.contextDigest, sourceReferences: [...new Set([...input.organizationDrafts.map(({ sourceReference }) => sourceReference), ...input.opportunityDrafts.map(({ sourceReference }) => sourceReference)])].sort(), evidenceReferences: evidenceBundle, credentialReportIds: input.credentialReports.map(({ reportId }) => reportId).sort(), masteryReportIds: input.masteryReports.map(({ reportId }) => reportId).sort(), learningReportIds: input.learningReports.map(({ reportId }) => reportId).sort(), discoveryReportIds: input.discoveryReports.map(({ reportId }) => reportId).sort() }; const organizations = createOrganizations(input.organizationDrafts, provenance); const opportunityInventory = createOpportunities(input.opportunityDrafts, organizations, provenance); const eligibilityAssessments = opportunityInventory.map((opportunity) => assessEligibility(opportunity, input.personContext)); const alignmentRecords = opportunityInventory.map((opportunity) => alignOpportunity(opportunity, input.personContext)); const recommendations = createRecommendations(opportunityInventory, alignmentRecords, eligibilityAssessments); const applicationPathways = createApplicationPathways(opportunityInventory); const deadlines = opportunityInventory.flatMap((opportunity) => opportunity.deadlines).sort((a, b) => `${a.date}:${a.deadlineId}`.localeCompare(`${b.date}:${b.deadlineId}`)); const body = { generatedAt: input.generatedAt, runtimeContextDigest: context.contextDigest, opportunityInventory, organizations, eligibilityAssessments, alignmentRecords, recommendations, applicationPathways, deadlines, evidenceBundle, limitations: ["Opportunity alignment is advisory and does not confer eligibility, entitlement, acceptance, employment, or success.", "Organizations and authorized humans retain all admissions, hiring, selection, and acceptance authority."], provenance }; return { reportId: `PBOS-OPP-REPORT-${digestValue(body).slice(0, 16).toUpperCase()}`, ...body }; }
